"""Exact source-owned environment for model-native seq513 training.

Readiness used to advertise direction-balance, path-quality and tail-direction
settings that were not all admitted by the launch recipe.  The wrappers clear
every ambient ``ENTRY_*``/``GX1_*`` variable, so an omitted key silently fell
back to a trainer default.  This contract is now the one complete owner of the
values that readiness advertises and the trainer actually receives.
"""

from __future__ import annotations

import hashlib
import json
from typing import Any, Mapping


SCHEMA_VERSION = "entry_model_native_seq513_train_recipe_env_v1"

_RECIPE_ENV_TEXT = """
ENTRY_AUX_BAD_PATH_POS_WEIGHT_CAP=20.0
ENTRY_AUX_BAD_PATH_WEIGHT=1.25
ENTRY_AUX_CLEAN_EDGE_POS_WEIGHT_CAP=16.0
ENTRY_AUX_CLEAN_EDGE_WEIGHT=0.45
ENTRY_AUX_MFE_SCALE_BPS=20.0
ENTRY_AUX_MFE_WEIGHT=0.25
ENTRY_AUX_PATH_SCALE_BPS=50.0
ENTRY_AUX_PATH_WEIGHT=0.90
ENTRY_AUX_SURVIVAL_POS_WEIGHT_CAP=10.0
ENTRY_AUX_SURVIVAL_WEIGHT=0.10
ENTRY_AUX_TRADABLE_POS_WEIGHT_CAP=12.0
ENTRY_AUX_TRADABLE_WEIGHT=1.15
ENTRY_BAD_PATH_CE_MULTIPLIER=1.50
ENTRY_BAD_PATH_PROB_PENALTY=0.24
ENTRY_BAD_PATH_QUALITY_RANK_MARGIN=0.25
ENTRY_BAD_PATH_QUALITY_RANK_QUANTILE=0.25
ENTRY_BAD_PATH_QUALITY_RANK_WEIGHT=2.00
ENTRY_CKPT_CLASS_BALANCE_GUARD_WEIGHT=0.50
ENTRY_CKPT_CLASS_BALANCE_MIN_PRED_RATE=0.05
ENTRY_CKPT_CLASS_BALANCE_MIN_PRED_TO_LABEL=0.35
ENTRY_CKPT_DIRECTION_SLICE_GUARD=1
ENTRY_CLEAN_EDGE_RANKING_MARGIN=0.12
ENTRY_CLEAN_EDGE_RANKING_WEIGHT=0.25
ENTRY_COST_FLAT_TO_LONG=1.60
ENTRY_COST_FLAT_TO_SHORT=1.60
ENTRY_COST_LONG_TO_FLAT=0.45
ENTRY_COST_LONG_TO_SHORT=2.00
ENTRY_COST_SENSITIVE_LOSS=1
ENTRY_COST_SENSITIVE_SCALE=0.25
ENTRY_COST_SHORT_TO_FLAT=0.45
ENTRY_COST_SHORT_TO_LONG=2.00
ENTRY_DEAD_LONG_CE_MULTIPLIER=1.80
ENTRY_DEAD_LONG_PROB_PENALTY=0.40
ENTRY_DIRECTION_CE_SCALE=12.00
ENTRY_DIRECTION_CLASS_WEIGHT_CAP=8.0
ENTRY_DIRECTION_FLAT_STARVATION_LOGIT_MARGIN=0.10
ENTRY_DIRECTION_FLAT_STARVATION_MIN_LABEL_RATE=0.10
ENTRY_DIRECTION_FLAT_STARVATION_MIN_ROWS=8
ENTRY_DIRECTION_FLAT_STARVATION_PRED_FLOOR=0.10
ENTRY_DIRECTION_FLAT_STARVATION_PRED_FRACTION=0.50
ENTRY_DIRECTION_FLAT_STARVATION_WEIGHT=8.00
ENTRY_DIRECTION_GLOBAL_PRIOR_MATCH_MIN_LABEL_RATE=0.10
ENTRY_DIRECTION_GLOBAL_PRIOR_MATCH_TOLERANCE=0.02
ENTRY_DIRECTION_GLOBAL_PRIOR_MATCH_WEIGHT=8.00
ENTRY_DIRECTION_MIN_PRED_RATE_FLOOR=0.05
ENTRY_DIRECTION_MIN_PRED_RATE_FRACTION=0.50
ENTRY_DIRECTION_MIN_PRED_RATE_LOSS_WEIGHT=12.00
ENTRY_DIRECTION_MIN_PRED_RATE_SOFTMAX_TEMPERATURE=0.05
ENTRY_DIRECTION_SIDE_UTILITY_CONVICTION_LOGIT_MARGIN=0.10
ENTRY_DIRECTION_SIDE_UTILITY_CONVICTION_MIN_GAP_BPS=15.0
ENTRY_DIRECTION_SIDE_UTILITY_CONVICTION_WEIGHT=2.00
ENTRY_DIRECTION_SLICE_ACCURACY_EDGE_MARGIN=0.02
ENTRY_DIRECTION_SLICE_ACCURACY_EDGE_MIN_LABEL_RATE=0.10
ENTRY_DIRECTION_SLICE_ACCURACY_EDGE_MIN_ROWS=8
ENTRY_DIRECTION_SLICE_ACCURACY_EDGE_WEIGHT=4.00
ENTRY_DIRECTION_SLICE_BALANCED_CE_MIN_LABEL_RATE=0.10
ENTRY_DIRECTION_SLICE_BALANCED_CE_MIN_ROWS=8
ENTRY_DIRECTION_SLICE_BALANCED_CE_WEIGHT=2.00
ENTRY_DIRECTION_SLICE_BALANCED_SAMPLER=0
ENTRY_DIRECTION_SLICE_BALANCED_SAMPLER_MIN_ROWS=8
ENTRY_DIRECTION_SLICE_CONFUSION_PAIR_MARGIN=0.02
ENTRY_DIRECTION_SLICE_CONFUSION_PAIR_WEIGHT=4.00
ENTRY_DIRECTION_SLICE_CTX_CAT_INDICES=0,1,2,3,4
ENTRY_DIRECTION_SLICE_HARD_RED_STOP_MIN_EPOCHS=6
ENTRY_DIRECTION_SLICE_HARD_RED_STOP_PATIENCE=3
ENTRY_DIRECTION_SLICE_LOSS_AGGREGATION=mean_max
ENTRY_DIRECTION_SLICE_MIN_LABEL_RATE=0.10
ENTRY_DIRECTION_SLICE_MIN_PRED_RATE_FLOOR=0.05
ENTRY_DIRECTION_SLICE_MIN_PRED_RATE_FRACTION=0.50
ENTRY_DIRECTION_SLICE_MIN_PRED_RATE_LOSS_WEIGHT=8.00
ENTRY_DIRECTION_SLICE_MIN_ROWS=8
ENTRY_DIRECTION_SLICE_PRIOR_MATCH_MIN_LABEL_RATE=0.10
ENTRY_DIRECTION_SLICE_PRIOR_MATCH_MIN_ROWS=8
ENTRY_DIRECTION_SLICE_PRIOR_MATCH_TOLERANCE=0.02
ENTRY_DIRECTION_SLICE_PRIOR_MATCH_WEIGHT=3.00
ENTRY_DIRECTION_SLICE_RECALL_LOSS_WEIGHT=4.00
ENTRY_DIRECTION_SLICE_RECALL_MIN_LABEL_RATE=0.10
ENTRY_DIRECTION_SLICE_RECALL_MIN_ROWS=8
ENTRY_DIRECTION_SLICE_RECALL_PROB_FLOOR=0.30
ENTRY_DIRECTION_SLICE_TRUE_MARGIN=0.10
ENTRY_DIRECTION_SLICE_TRUE_MARGIN_MIN_LABEL_RATE=0.10
ENTRY_DIRECTION_SLICE_TRUE_MARGIN_MIN_ROWS=8
ENTRY_DIRECTION_SLICE_TRUE_MARGIN_WEIGHT=2.00
ENTRY_DIRECTION_UTILITY_LOGIT_MARGIN=0.10
ENTRY_DIRECTION_UTILITY_MARGIN_WEIGHT=4.00
ENTRY_DIRECTION_UTILITY_MIN_GAP_BPS=15.0
ENTRY_DIRECTION_UTILITY_TRADE_CONVICTION_LOGIT_MARGIN=0.10
ENTRY_DIRECTION_UTILITY_TRADE_CONVICTION_MAX_BAD_PATH=0.50
ENTRY_DIRECTION_UTILITY_TRADE_CONVICTION_MIN_GAP_BPS=15.0
ENTRY_DIRECTION_UTILITY_TRADE_CONVICTION_MIN_UTILITY_BPS=0.0
ENTRY_DIRECTION_UTILITY_TRADE_CONVICTION_WEIGHT=2.00
ENTRY_DIRECTION_UTILITY_TRIAD_CE_CLASS_WEIGHT_CAP=4.0
ENTRY_DIRECTION_UTILITY_TRIAD_CE_MAX_BAD_PATH=0.50
ENTRY_DIRECTION_UTILITY_TRIAD_CE_MIN_GAP_BPS=15.0
ENTRY_DIRECTION_UTILITY_TRIAD_CE_MIN_UTILITY_BPS=0.0
ENTRY_DIRECTION_UTILITY_TRIAD_CE_WEIGHT=2.00
ENTRY_DIRECTION_VS_FLAT_MARGIN=0.10
ENTRY_DIRECTION_VS_FLAT_MARGIN_WEIGHT=4.00
ENTRY_FLAT_CLASS_WEIGHT_FLOOR=1.0
ENTRY_HARD_NEG_LONG_CE_MULTIPLIER=1.35
ENTRY_HARD_NEG_LONG_PROB_PENALTY=0.20
ENTRY_HIER_BAD_PATH_POS_WEIGHT_CAP=20.0
ENTRY_HIER_BAD_PATH_WEIGHT=1.25
ENTRY_HIER_FLAT_LOGIT_MARGIN=0.10
ENTRY_HIER_FLAT_LOGIT_MARGIN_MIN_LABEL_RATE=0.10
ENTRY_HIER_FLAT_LOGIT_MARGIN_WEIGHT=8.00
ENTRY_HIER_MAE_WEIGHT=0.35
ENTRY_HIER_SIDE_GLOBAL_PRIOR_MATCH_MIN_LABEL_RATE=0.10
ENTRY_HIER_SIDE_GLOBAL_PRIOR_MATCH_TOLERANCE=0.02
ENTRY_HIER_SIDE_GLOBAL_PRIOR_MATCH_WEIGHT=4.00
ENTRY_HIER_SIDE_VALIDITY_MIN_UTILITY_BPS=15.0
ENTRY_HIER_SIDE_VALIDITY_POS_WEIGHT_CAP=8.0
ENTRY_HIER_SIDE_VALIDITY_WEIGHT=1.50
ENTRY_HIER_SIDE_WEIGHT=1.75
ENTRY_HIER_SLICE_FLAT_LOGIT_MARGIN=0.10
ENTRY_HIER_SLICE_FLAT_LOGIT_MARGIN_MIN_LABEL_RATE=0.10
ENTRY_HIER_SLICE_FLAT_LOGIT_MARGIN_MIN_ROWS=8
ENTRY_HIER_SLICE_FLAT_LOGIT_MARGIN_WEIGHT=8.00
ENTRY_HIER_SLICE_SIDE_ACCURACY_EDGE_MARGIN=0.02
ENTRY_HIER_SLICE_SIDE_ACCURACY_EDGE_WEIGHT=4.00
ENTRY_HIER_SLICE_SIDE_CE_WEIGHT=4.00
ENTRY_HIER_SLICE_SIDE_MIN_LABEL_RATE=0.10
ENTRY_HIER_SLICE_SIDE_MIN_ROWS=8
ENTRY_HIER_SLICE_SIDE_PRIOR_MATCH_MIN_LABEL_RATE=0.10
ENTRY_HIER_SLICE_SIDE_PRIOR_MATCH_MIN_ROWS=8
ENTRY_HIER_SLICE_SIDE_PRIOR_MATCH_TOLERANCE=0.02
ENTRY_HIER_SLICE_SIDE_PRIOR_MATCH_WEIGHT=4.00
ENTRY_HIER_SLICE_SIDE_TRUE_MARGIN=0.10
ENTRY_HIER_SLICE_SIDE_TRUE_MARGIN_WEIGHT=3.00
ENTRY_HIER_SLICE_TRADE_ACCURACY_EDGE_MARGIN=0.02
ENTRY_HIER_SLICE_TRADE_ACCURACY_EDGE_WEIGHT=4.00
ENTRY_HIER_SLICE_TRADE_PRIOR_MATCH_MIN_LABEL_RATE=0.10
ENTRY_HIER_SLICE_TRADE_PRIOR_MATCH_MIN_ROWS=8
ENTRY_HIER_SLICE_TRADE_PRIOR_MATCH_TOLERANCE=0.02
ENTRY_HIER_SLICE_TRADE_PRIOR_MATCH_WEIGHT=4.00
ENTRY_HIER_TRADE_GLOBAL_PRIOR_MATCH_MIN_LABEL_RATE=0.10
ENTRY_HIER_TRADE_GLOBAL_PRIOR_MATCH_TOLERANCE=0.02
ENTRY_HIER_TRADE_GLOBAL_PRIOR_MATCH_WEIGHT=4.00
ENTRY_HIER_TRADE_WEIGHT=2.00
ENTRY_HIER_UTILITY_WEIGHT=1.00
ENTRY_MTF_DIR_AUX_WEIGHT=0.30
ENTRY_OFFLINE_RL_Q_WEIGHT=0.50
ENTRY_OFFLINE_RL_RANK_WEIGHT=0.05
ENTRY_OFFLINE_RL_V_WEIGHT=0.20
ENTRY_PATH_QUALITY_RANK_MARGIN=0.25
ENTRY_PATH_QUALITY_RANK_QUANTILE=0.25
ENTRY_PATH_QUALITY_RANK_WEIGHT=2.00
ENTRY_PRED_BALANCE_ALPHA=0.50
ENTRY_PRED_BALANCE_CLASS_WEIGHTS=1.0,1.0,1.0
ENTRY_PRED_BALANCE_TARGET=label
ENTRY_SPECIALIST_GATE_BALANCE_WEIGHT=0.50
ENTRY_SPECIALIST_GATE_ENTROPY_WEIGHT=0.05
ENTRY_SPECIALIST_GATE_MIN_MEAN=0.01
ENTRY_SYMMETRIC_NEGATIVES=1
ENTRY_TAIL_DIRECTION_CE_WEIGHT=0.35
ENTRY_TAIL_DIRECTION_MIN_BATCH=8
ENTRY_TAIL_DIRECTION_QUALITY_QUANTILE=0.70
ENTRY_TEASER_LONG_CE_MULTIPLIER=1.35
ENTRY_TEASER_LONG_PROB_PENALTY=0.16
ENTRY_TRENDLINE_RAIL_AUX_WEIGHT=1.00
GX1_CTX_CONTRACT=V_NEXT
GX1_V10_CKPT_MONITOR=dir_acc
""".strip()


def _parse_recipe_env(text: str) -> dict[str, str]:
    result: dict[str, str] = {}
    for row in text.splitlines():
        key, separator, value = row.partition("=")
        if separator != "=" or not key or not value or key in result:
            raise RuntimeError(f"MODEL_NATIVE_RECIPE_ENV_ROW_INVALID: {row!r}")
        if not (key.startswith("ENTRY_") or key.startswith("GX1_")):
            raise RuntimeError(f"MODEL_NATIVE_RECIPE_ENV_KEY_INVALID: {key}")
        result[key] = value
    return result


MODEL_NATIVE_RECIPE_ENV = _parse_recipe_env(_RECIPE_ENV_TEXT)
MODEL_NATIVE_RECIPE_ENV_KEYS = tuple(sorted(MODEL_NATIVE_RECIPE_ENV))
MODEL_NATIVE_RECIPE_ENV_SHA256 = hashlib.sha256(
    json.dumps(
        MODEL_NATIVE_RECIPE_ENV,
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=True,
    ).encode("utf-8")
).hexdigest()

if len(MODEL_NATIVE_RECIPE_ENV) != 162:
    raise RuntimeError(
        "MODEL_NATIVE_RECIPE_ENV_COUNT_INVALID: "
        f"observed={len(MODEL_NATIVE_RECIPE_ENV)} expected=162"
    )


def require_model_native_recipe_env(value: Mapping[str, Any]) -> dict[str, str]:
    """Require the exact source-owned key/value surface without pass-through."""

    if not isinstance(value, Mapping):
        raise RuntimeError("MODEL_NATIVE_RECIPE_ENV_MISSING")
    normalized = {str(key): str(item) for key, item in value.items()}
    if normalized != MODEL_NATIVE_RECIPE_ENV:
        missing = sorted(set(MODEL_NATIVE_RECIPE_ENV) - set(normalized))
        extra = sorted(set(normalized) - set(MODEL_NATIVE_RECIPE_ENV))
        changed = sorted(
            key
            for key in set(normalized).intersection(MODEL_NATIVE_RECIPE_ENV)
            if normalized[key] != MODEL_NATIVE_RECIPE_ENV[key]
        )
        raise RuntimeError(
            "MODEL_NATIVE_RECIPE_ENV_MISMATCH: "
            f"missing={missing} extra={extra} changed={changed}"
        )
    return dict(MODEL_NATIVE_RECIPE_ENV)


def model_native_recipe_env_contract_metadata() -> dict[str, Any]:
    return {
        "schema_version": SCHEMA_VERSION,
        "count": len(MODEL_NATIVE_RECIPE_ENV),
        "sha256": MODEL_NATIVE_RECIPE_ENV_SHA256,
        "keys": list(MODEL_NATIVE_RECIPE_ENV_KEYS),
    }
