"""V4-only per-bar multi-timeframe feature, routing, and clock contract.

V29 Phase A stage 2 (2026-08-11): the per-TF surface carries the 21 event
fields plus the 11 level-registry and 30 trendline-registry fields; every
expected count below is DERIVED from the declared owner tuples.  The V29
registry blocks require an explicit constants payload (no default exists);
tests use the shared synthetic-execution payload from
``tests.htf_v29_registry_test_support`` (proves the code runs; never a
production value).
"""
from __future__ import annotations

import numpy as np
import pandas as pd
import pytest

from gx1.features import htf_features as htf
from tests.htf_v29_registry_test_support import (
    synthetic_v29_registry_constants,
)
from tests.volatility_squeeze_test_support import (
    make_volatility_squeeze_artifact_set,
)

V29_TEST_REGISTRY_CONSTANTS = synthetic_v29_registry_constants()
_SQUEEZE_TEST_ARTIFACTS = None


@pytest.fixture(scope="module", autouse=True)
def _bind_squeeze_artifacts(tmp_path_factory):
    global _SQUEEZE_TEST_ARTIFACTS
    _SQUEEZE_TEST_ARTIFACTS = make_volatility_squeeze_artifact_set(
        tmp_path_factory.mktemp("squeeze-artifacts")
    )


def _compute_v4(bars: pd.DataFrame, *, timeframe: str) -> pd.DataFrame:
    return htf.compute_per_bar_features_v4(
        bars,
        timeframe=timeframe,
        v29_registry_constants=V29_TEST_REGISTRY_CONSTANTS,
        volatility_squeeze_artifacts=_SQUEEZE_TEST_ARTIFACTS,
    )


def _bars(n: int, *, seed: int) -> pd.DataFrame:
    rng = np.random.default_rng(seed)
    close = 2000.0 + np.cumsum(rng.normal(0.0, 1.5, size=n))
    high = close + np.abs(rng.normal(0.0, 1.0, size=n))
    low = close - np.abs(rng.normal(0.0, 1.0, size=n))
    open_ = np.concatenate([[close[0]], close[:-1]])
    index = pd.date_range("2021-01-04", periods=n, freq="5min", tz="UTC")
    return pd.DataFrame(
        {
            "open": open_,
            "high": np.maximum.reduce([high, open_, close]),
            "low": np.minimum.reduce([low, open_, close]),
            "close": close,
            "volume": rng.integers(400, 601, size=n, dtype=np.int64),
        },
        index=index,
    )


def test_rsi_uses_classic_wilder_seed_and_recursion() -> None:
    # Wilder's canonical worksheet series: the first 14-period RSI and the
    # next recursive observations are independent reference values, not
    # values generated by the implementation under test.
    close = pd.Series(
        [
            44.34, 44.09, 44.15, 43.61, 44.33, 44.83, 45.10, 45.42,
            45.84, 46.08, 45.89, 46.03, 45.61, 46.28, 46.28, 46.00,
            46.03, 46.41, 46.22, 45.64, 46.21,
        ],
        dtype=np.float64,
    )
    observed = htf._rsi(close, 14)
    assert observed.iloc[:14].isna().all()
    np.testing.assert_allclose(
        observed.iloc[14:21].to_numpy(),
        [70.464135, 66.249619, 66.480942, 69.346853, 66.294713, 57.915021, 62.880718],
        rtol=0.0,
        atol=1e-6,
    )
    flat = htf._rsi(pd.Series(np.ones(20)), 14)
    assert (flat.iloc[14:] == 50.0).all()


def test_rolling_vwap_requires_the_complete_declared_window() -> None:
    close = pd.Series([1.0, 2.0, 3.0, 4.0, 5.0])
    volume = pd.Series(np.ones(5))
    observed = htf._rolling_vwap(close, volume, 3)
    np.testing.assert_array_equal(
        observed.to_numpy(),
        np.asarray([np.nan, np.nan, 2.0, 3.0, 4.0]),
    )


def test_adx14_has_classic_wilder_seed_and_raw_scale() -> None:
    rows = 10
    high = pd.Series(10.0 + np.arange(rows, dtype=np.float64))
    low = high - 1.0
    close = low + 0.5
    adx, signed_di = htf._adx14(high, low, close, 3)

    assert adx.iloc[:5].isna().all()
    np.testing.assert_array_equal(
        adx.iloc[5:].to_numpy(), np.full(rows - 5, 100.0)
    )
    assert signed_di.iloc[:3].isna().all()
    np.testing.assert_array_equal(
        signed_di.iloc[3:].to_numpy(), np.ones(rows - 3)
    )


def test_session_vwap_resets_at_trading_day_not_midnight() -> None:
    index = pd.DatetimeIndex(
        [
            "2026-01-01T21:00:00Z",
            "2026-01-01T22:00:00Z",
            "2026-01-01T23:00:00Z",
            "2026-01-02T00:00:00Z",
        ]
    )
    close = pd.Series([10.0, 20.0, 30.0, 40.0], index=index)
    volume = pd.Series(np.ones(4), index=index)
    observed = htf._session_vwap(
        close,
        volume,
        bar_duration=pd.Timedelta(hours=1),
    )
    np.testing.assert_array_equal(observed.to_numpy(), [10.0, 20.0, 25.0, 30.0])


EXPECTED_V4_GROUP_A_BASE_FEATURES = (
    "atr_bps_14",
    "rsi14_centered",
    # V30 (2026-08-13): raw Wilder RSI 5-bar velocity.
    "rsi14_delta_5",
    "mom_5_atr",
    "mom_20_atr",
    "close_open_atr",
    # 2026-08-19: ``body_pct`` is RETIRED from the per-TF lane. It was exactly
    # ``abs(mtf_candle_raw_body_signed_range)`` on every post-warmup row of
    # every lane. The identity itself is asserted from raw OHLC in
    # ``test_retired_per_tf_body_pct_is_exactly_the_unsigned_signed_twin``.
    "ema20_dist_atr",
    "ema50_dist_atr",
    "ema100_dist_atr",
    "ema200_dist_atr",
    "ema20_slope_atr",
    "ema50_slope_atr",
    "ema200_slope_atr",
    "ema_stack_aligned_v2",
    # V30 (2026-08-14): the handwritten `regime_class_id` discretization is
    # retired; the raw EMA-stack alignment and trend-state age remain.
    "vwap_local_cycle_dist_atr",
    "vwap20_dist_atr",
    "vwap96_dist_atr",
    "vwap_rolling5_slope_atr",
    "bb_position",
    "bb_width_atr",
    "adx14",
    # V30 (2026-08-13): signed DI spread from the _adx14 producer.
    "di_spread_signed",
    "trend_state_age_bars",
)


EXPECTED_V29_TREND_EVENT_FEATURES = (
    "ema50_200_spread_atr",
    "ema50_200_bull_state",
    "ema50_200_cross_up",
    "ema50_200_cross_down",
    "ema50_200_state_age_bars",
    "price_x_ema50_cross_up",
    "price_x_ema50_cross_down",
    "price_x_ema200_cross_up",
    "price_x_ema200_cross_down",
    "price_vs_ema50_state_age_bars",
    "price_vs_ema200_state_age_bars",
)
EXPECTED_V29_MOMENTUM_EVENT_FEATURES = (
    "rsi_cross_up_30",
    "rsi_cross_down_70",
    "rsi_cross_up_50",
    "rsi_cross_down_50",
    "rsi_extreme_event_age_bars",
    "mom20_sign_flip_up",
    "mom20_sign_flip_down",
    "bear_divergence_event",
    "bull_divergence_event",
    # V30 (2026-08-13): the event-gated divergence strengths.
    "bear_divergence_strength",
    "bull_divergence_strength",
    "divergence_event_age_bars",
)


def test_v4_is_one_exact_derived_field_contract() -> None:
    from gx1.features.level_registry_v1 import LEVEL_REGISTRY_MTF_FEATURE_NAMES
    from gx1.features.trendline_registry_v1 import (
        TRENDLINE_REGISTRY_FEATURE_NAMES_V1,
    )

    from gx1.features.smc_v1 import SMC_MTF_FEATURE_NAMES_V1

    expected_width = (
            len(htf.MULTI_TF_V4_GROUP_A_BASE_FEATURES)
            + len(htf.MULTI_TF_V4_VOLUME_FEATURES)
            + len(htf.MULTI_TF_V4_VOLATILITY_SQUEEZE_FEATURES)
        + len(htf.MULTI_TF_V4_CANDLE_PRIMITIVE_FEATURES)
        + len(htf.MULTI_TF_V4_SWING_FEATURES)
        + len(SMC_MTF_FEATURE_NAMES_V1)
        + len(htf.SMC_MTF_GEOMETRY_FEATURE_NAMES_V1)
        + len(EXPECTED_V29_TREND_EVENT_FEATURES)
        + len(EXPECTED_V29_MOMENTUM_EVENT_FEATURES)
        + len(LEVEL_REGISTRY_MTF_FEATURE_NAMES)
        + len(TRENDLINE_REGISTRY_FEATURE_NAMES_V1)
    )
    assert htf.MULTI_TF_FEATURE_COUNT_V4 == expected_width
    assert htf.MULTI_TF_V4_GROUP_A_BASE_FEATURES == (
        EXPECTED_V4_GROUP_A_BASE_FEATURES
    )
    assert (
        htf.MULTI_TF_PER_BAR_FEATURES_V4[
            : len(EXPECTED_V4_GROUP_A_BASE_FEATURES)
        ]
        == EXPECTED_V4_GROUP_A_BASE_FEATURES
    )
    volume_start = len(EXPECTED_V4_GROUP_A_BASE_FEATURES)
    assert htf.MULTI_TF_PER_BAR_FEATURES_V4[
        volume_start : volume_start + len(htf.MULTI_TF_V4_VOLUME_FEATURES)
    ] == htf.MULTI_TF_V4_VOLUME_FEATURES
    assert len(set(htf.MULTI_TF_PER_BAR_FEATURES_V4)) == expected_width
    assert htf.MULTI_TF_V4_TREND_EVENT_FEATURES == (
        EXPECTED_V29_TREND_EVENT_FEATURES
    )
    assert htf.MULTI_TF_V4_MOMENTUM_EVENT_FEATURES == (
        EXPECTED_V29_MOMENTUM_EVENT_FEATURES
    )
    registry_tail = tuple(LEVEL_REGISTRY_MTF_FEATURE_NAMES) + tuple(
        TRENDLINE_REGISTRY_FEATURE_NAMES_V1
    )
    assert htf.MULTI_TF_PER_BAR_FEATURES_V4[-len(registry_tail):] == (
        registry_tail
    )
    event_block = (
        EXPECTED_V29_TREND_EVENT_FEATURES
        + EXPECTED_V29_MOMENTUM_EVENT_FEATURES
    )
    tail_start = -(len(registry_tail) + len(event_block))
    assert (
        htf.MULTI_TF_PER_BAR_FEATURES_V4[tail_start : -len(registry_tail)]
        == event_block
    )


def test_active_technical_outputs_are_raw_owner_formulas() -> None:
    bars = _bars(500, seed=91)
    observed = _compute_v4(bars, timeframe="M5")
    close = bars["close"].astype(np.float64)
    high = bars["high"].astype(np.float64)
    low = bars["low"].astype(np.float64)
    atr = htf._atr(high, low, close, 14)
    atr_positive = atr.where(atr > 0.0)

    expected = {
        "atr_bps_14": atr / close * 1e4,
        "mom_5_atr": (close - close.shift(5)) / atr_positive,
        "mom_20_atr": (close - close.shift(20)) / atr_positive,
        "close_open_atr": (close - bars["open"]) / atr_positive,
    }
    adx, _signed_di = htf._adx14(high, low, close, 14)
    expected["adx14"] = adx
    for name, raw in expected.items():
        np.testing.assert_array_equal(
            observed[name].to_numpy(dtype=np.float32),
            raw.to_numpy(dtype=np.float32),
        )


def test_raw_technical_formulas_are_identical_on_all_five_native_clocks() -> None:
    bars = _bars(400, seed=92)
    technical_names = (
        "atr_bps_14",
        "rsi14_centered",
        "rsi14_delta_5",
        "mom_5_atr",
        "mom_20_atr",
        "close_open_atr",
        "ema20_dist_atr",
        "ema50_dist_atr",
        "ema100_dist_atr",
        "ema200_dist_atr",
        "ema20_slope_atr",
        "ema50_slope_atr",
        "ema200_slope_atr",
        "bb_position",
        "bb_width_atr",
        "adx14",
        "di_spread_signed",
    )
    observed: dict[str, pd.DataFrame] = {}
    for timeframe, frequency in htf.MULTI_TF_RESAMPLE_RULES.items():
        native = bars.copy()
        native.index = pd.date_range(
            "2021-01-01T22:00:00Z",
            periods=len(native),
            freq=frequency,
        )
        observed[timeframe] = _compute_v4(native, timeframe=timeframe).loc[
            :, technical_names
        ]
    reference = observed["M5"].to_numpy(dtype=np.float32)
    for timeframe in htf.MULTI_TF_RESAMPLE_RULES:
        np.testing.assert_array_equal(
            observed[timeframe].to_numpy(dtype=np.float32),
            reference,
        )


def test_technical_owner_source_has_no_retired_saturation_or_warmup_route() -> None:
    import inspect

    per_bar_source = inspect.getsource(htf.compute_per_bar_features_v4)
    rolling_vwap_source = inspect.getsource(htf._rolling_vwap)
    assert "atr_floor" not in per_bar_source
    assert "adx_centered" not in per_bar_source
    for token in (
        ".clip(-10.0, 10.0)",
        ".clip(-15.0, 15.0)",
        ".clip(-20.0, 20.0)",
        ".clip(-30.0, 30.0)",
        ".clip(-5.0, 5.0)",
        ".clip(0.0, 1.0)",
        ".clip(0.0, 20.0)",
        ".clip(0, 500)",
        "np.maximum(bb_width",
    ):
        assert token not in per_bar_source
    assert "min_periods=1" not in rolling_vwap_source
    assert ".ewm(" not in inspect.getsource(htf._ema)


def test_v4_candlestick_names_come_from_the_owner() -> None:
    from gx1.features.entry_candle_primitives_v1 import (
        CANDLE_PRIMITIVE_FEATURE_NAMES,
    )

    expected = tuple(
        f"mtf_{name.replace('.', '_')}"
        for name in CANDLE_PRIMITIVE_FEATURE_NAMES
    )
    assert htf.MULTI_TF_V4_CANDLE_PRIMITIVE_FEATURES == expected


def test_v4_rejects_missing_volume_and_non_m5_cache_source() -> None:
    bars = _bars(400, seed=3)
    with np.testing.assert_raises_regex(RuntimeError, "volume"):
        _compute_v4(bars.drop(columns="volume"), timeframe="M5")

    off_grid = bars.copy()
    off_grid.index = off_grid.index + pd.Timedelta(minutes=1)
    with np.testing.assert_raises_regex(
        RuntimeError,
        "HTF_INPUT_FAIL|HTF_V4_SOURCE_TIMESTAMP_GEOMETRY_INVALID",
    ):
        htf.build_multi_tf_per_bar_features_v4(
            off_grid,
            v29_registry_constants=V29_TEST_REGISTRY_CONSTANTS,
            volatility_squeeze_artifacts=_SQUEEZE_TEST_ARTIFACTS,
        )


@pytest.mark.parametrize("bad_volume", [0.0, -1.0, 1.5, True])
def test_v4_rejects_non_positive_or_noninteger_tick_volume(
    bad_volume: object,
) -> None:
    bars = _bars(400, seed=4)
    bars["volume"] = bars["volume"].astype(object)
    bars.iloc[200, bars.columns.get_loc("volume")] = bad_volume

    with pytest.raises(RuntimeError, match="HTF_V4_VOLUME_SOURCE_INVALID"):
        _compute_v4(bars, timeframe="M5")


def test_v4_volume_fields_are_exact_shared_owner_outputs_on_each_tf_clock() -> None:
    from gx1.features.volume_features import compute_volume_features

    bars = _bars(600, seed=5)
    closed_indices = htf.build_multi_tf_v4_closed_timestamp_indices(bars.index)
    for timeframe in htf.MULTI_TF_RESAMPLE_RULES:
        resampled = htf._resample_ohlcv(bars, timeframe).loc[
            closed_indices[timeframe]
        ]
        observed = _compute_v4(resampled, timeframe=timeframe)
        expected = compute_volume_features(resampled[["volume"]])
        for name in htf.MULTI_TF_V4_VOLUME_FEATURES:
            np.testing.assert_array_equal(observed[name].to_numpy(), expected[name])


def test_v4_candle_fields_are_recomputed_by_the_owner_on_each_closed_tf_clock() -> None:
    from gx1.features.entry_candle_primitives_v1 import (
        build_entry_candle_primitive_layer,
    )

    bars = _bars(600, seed=51)
    closed_indices = htf.build_multi_tf_v4_closed_timestamp_indices(bars.index)
    for timeframe in htf.MULTI_TF_RESAMPLE_RULES:
        resampled = htf._resample_ohlcv(bars, timeframe).loc[
            closed_indices[timeframe]
        ]
        observed = _compute_v4(resampled, timeframe=timeframe)
        candle_source = resampled[["open", "high", "low", "close"]].copy()
        candle_source.index.name = "time"
        expected, owner_names = build_entry_candle_primitive_layer(
            candle_source.reset_index()
        )
        mtf_names = [f"mtf_{name.replace('.', '_')}" for name in owner_names]
        np.testing.assert_array_equal(
            observed.loc[:, mtf_names].to_numpy(dtype=np.float32),
            expected,
        )


def test_v4_ohlcv_resampling_sums_tick_counts_before_feature_computation() -> None:
    bars = _bars(6, seed=6)
    bars["volume"] = np.arange(1, 7, dtype=np.int64)
    observed = htf._resample_ohlcv(bars, "M15")

    np.testing.assert_array_equal(
        observed["volume"].to_numpy(dtype=np.float64),
        np.asarray([6.0, 15.0]),
    )
    assert np.equal(
        observed["volume"].to_numpy(dtype=np.float64),
        np.floor(observed["volume"].to_numpy(dtype=np.float64)),
    ).all()


def test_v4_routes_every_field_to_all_eight_specialists() -> None:
    from gx1.features.entry_specialist_feature_groups_v1 import (
        MODEL_NATIVE_TRAINING_SPECIALISTS,
        require_multi_tf_specialist_routing_v4,
    )
    from gx1.features import smc_v1
    from gx1.features.level_registry_v1 import LEVEL_REGISTRY_MTF_FEATURE_NAMES
    from gx1.features.trendline_registry_v1 import (
        TRENDLINE_REGISTRY_FEATURE_NAMES_V1,
    )

    routing = require_multi_tf_specialist_routing_v4(
        htf.MULTI_TF_PER_BAR_FEATURES_V4
    )
    assert htf.MULTI_TF_FEATURE_COUNT_V4 == len(
        htf.MULTI_TF_PER_BAR_FEATURES_V4
    )
    assert tuple(routing) == MODEL_NATIVE_TRAINING_SPECIALISTS
    # Pre-V29 audited per-specialist widths plus the V29 additions, derived
    # from the declared owner tuples (design doc §5.2.3).
    assert {name: len(indices) for name, indices in routing.items()} == {
        # V30 package 2 (2026-08-13): the per-TF swing block is the 5 V1 names
        # plus the 9 adopted V29 swing-event names; the routing tuple is the
        # feature tuple itself, so the count derives from the owner.
        "structure_swing_encoder": len(htf.MULTI_TF_V4_SWING_FEATURES),
        # V30 package 8A (2026-08-13): the mtf_smc block count derives from
        # its owner tuple (it grew by mtf_smc_bos_displacement_atr and the two
        # de-duplicated sweep events).
        "smc_liquidity_encoder": len(smc_v1.SMC_MTF_FEATURE_NAMES_V1)
        + len(LEVEL_REGISTRY_MTF_FEATURE_NAMES),
        # V30 (2026-08-13): + di_spread_signed (trend) and rsi14_delta_5
        # (momentum) in the explicit non-event routing tuples.
        "trend_ema_encoder": 11
        + len(htf.MULTI_TF_V4_TREND_EVENT_FEATURES),
            "vol_compression_encoder": 2
            + len(htf.MULTI_TF_V4_VOLATILITY_SQUEEZE_FEATURES),
        "momentum_flow_encoder": 5
        + len(htf.MULTI_TF_V4_MOMENTUM_EVENT_FEATURES)
        + len(htf.MULTI_TF_V4_VOLUME_FEATURES),
        # V30 (2026-08-14): the handwritten `regime_class_id` discretization is
        # retired, leaving the four raw VWAP session-cycle fields.
        "session_regime_encoder": 4,
        # 2026-08-18 (V30 wave 2): the geometry block count derives from its
        # owner tuple, which lost the two *_break_displacement_atr ReLUs and
        # nearest_level_abs (each an exact continuous function of the two
        # distance columns beside them). A restated literal here is exactly
        # what CLAUDE.md rule 13 forbids.
        "chart_geometry_encoder": len(smc_v1.SMC_MTF_GEOMETRY_FEATURE_NAMES_V1)
        + len(TRENDLINE_REGISTRY_FEATURE_NAMES_V1),
        # 2026-08-19: the hand-counted head of this group drops from 2 to 1.
        # ``body_pct`` is retired as an exact duplicate of the candle owner's
        # ``mtf_candle_raw_body_signed_range`` (already counted by the owner
        # tuple below), leaving ``close_open_atr`` as the only non-owner name.
        "price_action_candle_encoder": 1
        + len(htf.MULTI_TF_V4_CANDLE_PRIMITIVE_FEATURES),
    }
    flattened = [index for indices in routing.values() for index in indices]
    assert sorted(flattened) == list(range(htf.MULTI_TF_FEATURE_COUNT_V4))
    assert "vwap_session_dist_atr" not in htf.MULTI_TF_PER_BAR_FEATURES_V4
    assert "vwap_session_slope_atr" not in htf.MULTI_TF_PER_BAR_FEATURES_V4
    assert "vwap_local_cycle_dist_atr" in htf.MULTI_TF_PER_BAR_FEATURES_V4


def test_v4_smc_and_geometry_are_causal_and_have_one_warmup_prefix() -> None:
    bars = _bars(4000, seed=23)
    original = _compute_v4(bars, timeframe="M5")
    matrix = original.to_numpy(dtype=np.float64)
    warmup = htf.validate_causal_feature_matrix(
        matrix,
        expected_width=htf.MULTI_TF_FEATURE_COUNT_V4,
        context="HTF_V4_TEST",
    )
    assert warmup > 0
    assert np.isfinite(matrix[warmup:]).all()

    cutoff = 2500
    changed = bars.copy()
    changed.iloc[cutoff:, changed.columns.get_loc("open")] *= 1.1
    changed.iloc[cutoff:, changed.columns.get_loc("high")] *= 1.1
    changed.iloc[cutoff:, changed.columns.get_loc("low")] *= 1.1
    changed.iloc[cutoff:, changed.columns.get_loc("close")] *= 1.1
    changed.iloc[cutoff:, changed.columns.get_loc("volume")] *= 7
    future_changed = _compute_v4(changed, timeframe="M5")
    assert np.array_equal(
        original.iloc[:cutoff].to_numpy(),
        future_changed.iloc[:cutoff].to_numpy(),
        equal_nan=True,
    )

    # A valid trend can place the latest confirmed low above an older
    # confirmed high. That remains available structure evidence.
    trending = _compute_v4(_bars(4000, seed=0), timeframe="M5")
    trending_matrix = trending.to_numpy(dtype=np.float64)
    trending_warmup = htf.validate_causal_feature_matrix(
        trending_matrix,
        expected_width=htf.MULTI_TF_FEATURE_COUNT_V4,
        context="HTF_V4_TRENDING_TEST",
    )
    assert np.isfinite(trending_matrix[trending_warmup:]).all()


def test_v4_equal_latest_high_low_pivots_use_confirmed_pivot_envelope(
    monkeypatch,
) -> None:
    """Equal latest pivots are valid XAU structure, not an interior data gap."""
    from gx1.features import smc_v1 as smc

    rows = 12
    high = np.full(rows, 101.0)
    low = np.full(rows, 99.0)
    close = np.full(rows, 100.0)
    high[1] = 105.0
    high[3] = 100.0
    low[2] = 95.0
    low[4] = 100.0
    close[3] = 100.0
    close[4] = 100.0
    frame = pd.DataFrame(
        {"high": high, "low": low, "close": close, "atr": np.ones(rows)}
    )

    def fixed_pivots(_high, _low, _lookback):
        swing_high = np.zeros(rows, dtype=bool)
        swing_low = np.zeros(rows, dtype=bool)
        swing_high[[1, 3]] = True
        swing_low[[2, 4]] = True
        return swing_high, swing_low

    monkeypatch.setattr(smc, "_detect_swing_pivots", fixed_pivots)
    built = smc.compute_smc_mtf_primitives_v1(frame, swing_lookback=1)
    matrix = built.to_numpy(dtype=np.float64)

    # At row 5 both latest confirmed pivots equal 100. The causal envelope of
    # the four already-confirmed pivots remains [95,105], so every subsequent
    # row is finite and carries a mathematically defined 0.5 position.
    assert np.isfinite(matrix[5:]).all()
    assert built.loc[5, "mtf_smc_pivot_envelope_position"] == 0.5
    assert built.loc[5, "mtf_smc_range_width_atr"] == 10.0


def test_v30_package_8a_smc_owner_parity_emissions() -> None:
    """V30 package 8A (2026-08-13): sided sweep depth, de-duplicated sweep
    events and signed BOS displacement, in BOTH smc owners.

    The M5 owner lagged its own MTF sibling on all three (fidelity audit §4b).
    Nothing accepted changes: the M5 additions are opt-in behind an explicit
    call-site contract switch and the MTF additions are appended after the
    pre-existing per-TF column order.
    """
    import numpy as np

    from gx1.features.smc_v1 import (
        SMC_FEATURE_NAMES,
        SMC_MTF_FEATURE_NAMES_V1,
        SMC_V30_ADDITION_NAMES_V1,
        compute_smc_features,
        compute_smc_mtf_primitives_v1,
    )

    bars = _bars(4000, seed=23)
    frame = bars[["high", "low", "close"]].copy()
    frame["atr"] = htf._atr(frame["high"], frame["low"], frame["close"], 14)
    frame = frame.iloc[20:].reset_index(drop=True)

    # ── M5 owner: the accepted 9-column surface is byte-identical with the
    # additions on, and the flag is a bool contract switch.
    base = compute_smc_features(frame)
    extended = compute_smc_features(frame, include_v30_additions=True)
    assert list(base.columns) == SMC_FEATURE_NAMES
    assert tuple(extended.columns) == tuple(SMC_FEATURE_NAMES) + (
        SMC_V30_ADDITION_NAMES_V1
    )
    for name in SMC_FEATURE_NAMES:
        np.testing.assert_array_equal(base[name].to_numpy(), extended[name].to_numpy())
    with pytest.raises(RuntimeError, match="SMC_V30_ADDITION_FLAG_INVALID"):
        compute_smc_features(frame, include_v30_additions=1)  # type: ignore[arg-type]

    # Sided depths preserve double-sided sweep evidence and are flag-gated.
    up_depth = extended["smc_sweep_up_depth_atr"].to_numpy()
    down_depth = extended["smc_sweep_down_depth_atr"].to_numpy()
    assert (
        up_depth[extended["smc_sweep_up_state"].to_numpy() == 0.0] == 0.0
    ).all()
    assert (
        down_depth[extended["smc_sweep_down_state"].to_numpy() == 0.0] == 0.0
    ).all()
    assert (up_depth >= 0.0).all() and (down_depth >= 0.0).all()

    # Events are a subset of conditions. They consume confirmed level identity
    # once, so a later rising edge on the same pivot is deliberately not a new
    # event; only a newly confirmed level can rearm it.
    for flag_name, event_name in (
        ("smc_sweep_up_state", "smc_sweep_up_event"),
        ("smc_sweep_down_state", "smc_sweep_down_event"),
    ):
        flag = extended[flag_name].to_numpy() > 0.0
        event = extended[event_name].to_numpy() > 0.0
        assert np.logical_or(~event, flag).all()
        assert event.sum() <= flag.sum()
    assert (
        (extended["smc_sweep_up_state"].to_numpy() > 0.0).sum()
        > (extended["smc_sweep_up_event"].to_numpy() > 0.0).sum()
    ), "the fixture must actually contain a repeated sweep run"

    # Signed BOS displacement: zero off-event, sign = break side.
    disp = extended["smc_bos_displacement_atr"].to_numpy()
    up = extended["smc_bos_up"].to_numpy() > 0.0
    down = extended["smc_bos_down"].to_numpy() > 0.0
    assert (disp[~(up | down)] == 0.0).all()
    assert (disp[up & ~down] > 0.0).all()
    assert (disp[down & ~up] < 0.0).all()

    age = extended["smc_sweep_event_age_bars"].to_numpy()
    assert np.isnan(age[: int(np.argmax(np.isfinite(age)))]).all()
    assert (age[np.isfinite(age)] >= 0.0).all()
    assert (age == 0.0).any()

    # ── MTF owner: the three additions are appended, so the pre-existing
    # per-TF column order is byte-stable ahead of them.
    assert SMC_MTF_FEATURE_NAMES_V1[-4:] == (
        "mtf_smc_bos_displacement_atr",
        "mtf_smc_sweep_up_event",
        "mtf_smc_sweep_down_event",
        "mtf_smc_sweep_event_age_bars",
    )
    mtf = compute_smc_mtf_primitives_v1(frame)
    valid = np.isfinite(mtf["mtf_smc_pivot_envelope_position"].to_numpy())
    m_disp = mtf["mtf_smc_bos_displacement_atr"].to_numpy()[valid]
    m_up = mtf["mtf_smc_bos_up"].to_numpy()[valid] > 0.0
    m_down = mtf["mtf_smc_bos_down"].to_numpy()[valid] > 0.0
    assert (m_disp[~(m_up | m_down)] == 0.0).all()
    assert (m_disp[m_up & ~m_down] > 0.0).all()
    assert (m_disp[m_down & ~m_up] < 0.0).all()
    for flag_name, event_name in (
        ("mtf_smc_sweep_up_state", "mtf_smc_sweep_up_event"),
        ("mtf_smc_sweep_down_state", "mtf_smc_sweep_down_event"),
    ):
        flag = np.nan_to_num(mtf[flag_name].to_numpy()) > 0.0
        event = np.nan_to_num(mtf[event_name].to_numpy()) > 0.0
        assert np.logical_or(~event, flag).all()
        assert event.sum() < flag.sum()
    np.testing.assert_array_equal(
        mtf["mtf_smc_sweep_event_age_bars"].to_numpy()[valid],
        extended["smc_sweep_event_age_bars"].to_numpy()[valid],
    )


def test_smc_owner_is_value_identical_on_all_five_native_tf_routes() -> None:
    from gx1.features.smc_v1 import (
        SMC_MTF_FEATURE_NAMES_V1,
        SMC_MTF_GEOMETRY_FEATURE_NAMES_V1,
        compute_smc_mtf_primitives_v1,
    )

    bars = _bars(800, seed=611)
    direct_source = bars[["high", "low", "close"]].copy()
    direct_source["atr"] = htf._atr(
        direct_source["high"],
        direct_source["low"],
        direct_source["close"],
        14,
    )
    direct = compute_smc_mtf_primitives_v1(direct_source)
    names = SMC_MTF_FEATURE_NAMES_V1 + SMC_MTF_GEOMETRY_FEATURE_NAMES_V1
    frequencies = {
        "M5": "5min",
        "M15": "15min",
        "H1": "1h",
        "H4": "4h",
        "D1": "1D",
    }
    for timeframe, frequency in frequencies.items():
        native_bars = bars.copy()
        native_bars.index = pd.date_range(
            "2021-01-04T22:00:00Z",
            periods=len(native_bars),
            freq=frequency,
        )
        routed = _compute_v4(native_bars, timeframe=timeframe)
        np.testing.assert_array_equal(
            routed.loc[:, list(names)].to_numpy(dtype=np.float32),
            direct.loc[:, list(names)].to_numpy(dtype=np.float32),
            err_msg=timeframe,
        )


def test_native_momentum_primitives_match_the_per_tf_owner() -> None:
    bars = _bars(800, seed=117)
    local = htf.compute_v29_momentum_event_block_from_ohlc(
        bars[["high", "low", "close"]],
        include_v30_primitives=True,
    )
    per_tf = _compute_v4(bars, timeframe="M5")
    expected_names = (
        *htf.MULTI_TF_V4_MOMENTUM_EVENT_FEATURES,
        *htf.LOCAL_MOMENTUM_V30_PRIMITIVE_FEATURES,
    )
    assert tuple(local.columns) == expected_names
    for name in htf.LOCAL_MOMENTUM_V30_PRIMITIVE_FEATURES:
        np.testing.assert_array_equal(
            local[name].to_numpy(dtype=np.float32),
            per_tf[name].to_numpy(dtype=np.float32),
        )
    with pytest.raises(
        RuntimeError,
        match="HTF_V4_LOCAL_MOMENTUM_PRIMITIVE_FLAG_INVALID",
    ):
        htf.compute_v29_momentum_event_block_from_ohlc(
            bars[["high", "low", "close"]],
            include_v30_primitives=1,  # type: ignore[arg-type]
        )


def test_divergence_strength_is_nonnegative_side_magnitude() -> None:
    events = htf.compute_v29_momentum_event_block_from_ohlc(
        _bars(5000, seed=131)[["high", "low", "close"]]
    )
    for event_name, strength_name in (
        ("bear_divergence_event", "bear_divergence_strength"),
        ("bull_divergence_event", "bull_divergence_strength"),
    ):
        event = events[event_name].fillna(0.0).to_numpy() > 0.0
        strength = events[strength_name].fillna(0.0).to_numpy()
        assert event.any()
        assert (strength >= 0.0).all()
        assert (strength[event] > 0.0).all()
        assert (strength[~event] == 0.0).all()


def test_v4_removes_cross_owner_duplicate_smc_geometry_fields() -> None:
    from gx1.features.smc_v1 import (
        SMC_MTF_FEATURE_NAMES_V1,
        SMC_MTF_GEOMETRY_FEATURE_NAMES_V1,
    )

    assert "mtf_smc_pivot_envelope_position" in SMC_MTF_FEATURE_NAMES_V1
    assert "mtf_smc_range_width_atr" in SMC_MTF_FEATURE_NAMES_V1
    assert "mtf_geometry_channel_position" not in (
        SMC_MTF_GEOMETRY_FEATURE_NAMES_V1
    )
    assert "mtf_geometry_channel_width_atr" not in (
        SMC_MTF_GEOMETRY_FEATURE_NAMES_V1
    )
    matrix = _compute_v4(_bars(4000, seed=31), timeframe="M5")
    assert (
        matrix["mtf_smc_choch_up"].sum()
        + matrix["mtf_smc_choch_down"].sum()
    ) > 0.0


def test_resolution_windows_must_form_strict_wall_clock_pyramid() -> None:
    accepted = htf.require_multi_tf_resolution_pyramid(
        {"M5": 16, "M15": 16, "H1": 16, "H4": 8, "D1": 8}
    )
    spans = list(accepted["coverage_seconds"].values())
    assert all(left < right for left, right in zip(spans, spans[1:]))

    with np.testing.assert_raises_regex(
        RuntimeError,
        "MULTI_TF_RESOLUTION_PYRAMID_COVERAGE_INVALID",
    ):
        htf.require_multi_tf_resolution_pyramid(
            {"M5": 500, "M15": 16, "H1": 16, "H4": 8, "D1": 8}
        )


def test_exact_resolution_pyramid_is_sliceable_across_all_split_boundaries() -> None:
    features: dict[str, pd.DataFrame] = {}
    end = pd.Timestamp("2026-01-21T00:00:00Z")
    for timeframe, rule in htf.MULTI_TF_RESAMPLE_RULES.items():
        index = pd.date_range(end=end, periods=400, freq=rule)
        values = np.ones(
            (len(index), htf.MULTI_TF_FEATURE_COUNT_V4),
            dtype=np.float32,
        )
        values[:10] = np.nan
        frame = pd.DataFrame(
            values,
            index=index,
            columns=htf.MULTI_TF_PER_BAR_FEATURES_V4,
        )
        frame.attrs["ts_int64"] = index.asi8.astype(np.int64, copy=True)
        frame.attrs["feats_np"] = values
        frame.attrs["causal_warmup_rows"] = 10
        frame.attrs["htf_feature_contract"] = htf.HTF_V4_MATRIX_CONTRACT
        features[timeframe] = frame

    route_split_times = {
        "entry": {
            "train": pd.date_range(
                "2026-01-20T00:00:00Z", periods=2, freq="5min"
            ),
            "val": pd.date_range(
                "2026-01-20T00:10:00Z", periods=2, freq="5min"
            ),
        },
        "exit": {
            "train": pd.date_range(
                "2026-01-20T00:00:00Z", periods=2, freq="1min"
            ),
            "val": pd.date_range(
                "2026-01-20T00:02:00Z", periods=2, freq="1min"
            ),
        },
    }
    lengths = {"M5": 2, "M15": 2, "H1": 2, "H4": 2, "D1": 2}
    proof = htf.require_multi_tf_decision_window_coverage(
        features,
        per_tf_seq_lens=lengths,
        decision_times_by_route_split=route_split_times,
    )

    assert proof["all_route_split_boundaries_sliceable"] is True
    assert proof["schema_version"] == (
        "entry_exit_multi_tf_decision_window_coverage_v2"
    )
    assert proof["routes"]["entry"][
        "target_availability_shift_seconds"
    ] == 300
    assert proof["routes"]["exit"][
        "target_availability_shift_seconds"
    ] == 60
    assert proof["per_tf"]["M5"]["routes"]["entry"] == {
        "enabled": False,
        "boundaries": {},
    }
    assert proof["per_tf"]["M5"]["routes"]["exit"]["enabled"] is True
    assert "test" not in str(proof).lower()
    assert proof["resolution_pyramid"]["per_tf_seq_lens"] == lengths
    assert set(proof["per_tf"]) == set(htf.MULTI_TF_RESAMPLE_RULES)
    assert len(proof["contract_sha256"]) == 64

    features["D1"].attrs["feats_np"][:399] = np.nan
    features["D1"].attrs["causal_warmup_rows"] = 399
    with np.testing.assert_raises_regex(
        RuntimeError,
        "MULTI_TF_DECISION_COVERAGE_UNAVAILABLE",
    ):
        htf.require_multi_tf_decision_window_coverage(
            features,
            per_tf_seq_lens=lengths,
            decision_times_by_route_split=route_split_times,
        )

    stale = dict(proof)
    stale["schema_version"] = "entry_multi_tf_decision_window_coverage_v1"
    with np.testing.assert_raises_regex(
        RuntimeError,
        "MULTI_TF_DECISION_COVERAGE_METADATA_INVALID",
    ):
        htf.require_multi_tf_decision_window_coverage_metadata(
            stale,
            per_tf_seq_lens=lengths,
        )


def test_shared_v4_cache_has_exact_entry_and_exit_routes_and_clocks() -> None:
    from gx1.contracts.entry_exit_feature_base_v1 import (
        ENTRY_DECISION_BAR_SECONDS,
        ENTRY_MTF_CONTEXT_TIMEFRAMES,
        EXIT_DECISION_BAR_SECONDS,
        EXIT_MTF_CONTEXT_TIMEFRAMES,
    )

    decision = pd.Timestamp("2026-01-20T18:00:00Z")
    features: dict[str, pd.DataFrame] = {}
    for timeframe, rule in htf.MULTI_TF_RESAMPLE_RULES.items():
        index = pd.date_range(end=decision, periods=400, freq=rule)
        values = np.repeat(
            np.arange(len(index), dtype=np.float32).reshape(-1, 1),
            htf.MULTI_TF_FEATURE_COUNT_V4,
            axis=1,
        )
        frame = pd.DataFrame(
            values,
            index=index,
            columns=htf.MULTI_TF_PER_BAR_FEATURES_V4,
        )
        frame.attrs["ts_int64"] = index.asi8.astype(np.int64, copy=True)
        frame.attrs["feats_np"] = values
        frame.attrs["causal_warmup_rows"] = 0
        frame.attrs["htf_feature_contract"] = htf.HTF_V4_MATRIX_CONTRACT
        features[timeframe] = frame
    lengths = {tf: 2 for tf in features}

    entry = htf.get_model_native_multi_tf_route_windows(
        features,
        decision_bar_start=decision,
        per_tf_seq_lens=lengths,
        route_timeframes=ENTRY_MTF_CONTEXT_TIMEFRAMES,
        base_bar_duration=pd.Timedelta(seconds=ENTRY_DECISION_BAR_SECONDS),
    )
    exit_route = htf.get_model_native_multi_tf_route_windows(
        features,
        decision_bar_start=decision,
        per_tf_seq_lens=lengths,
        route_timeframes=EXIT_MTF_CONTEXT_TIMEFRAMES,
        base_bar_duration=pd.Timedelta(seconds=EXIT_DECISION_BAR_SECONDS),
    )

    assert tuple(entry) == ENTRY_MTF_CONTEXT_TIMEFRAMES
    assert tuple(exit_route) == EXIT_MTF_CONTEXT_TIMEFRAMES
    assert "M5" not in entry
    assert exit_route["M5"][-1, 0] == 398.0

    with np.testing.assert_raises_regex(
        RuntimeError,
        "MODEL_NATIVE_MTF_LOCAL_CLOCK_INVALID",
    ):
        htf.get_model_native_multi_tf_route_windows(
            features,
            decision_bar_start=decision,
            per_tf_seq_lens=lengths,
            route_timeframes=ENTRY_MTF_CONTEXT_TIMEFRAMES,
            base_bar_duration=pd.Timedelta(seconds=EXIT_DECISION_BAR_SECONDS),
        )
    with np.testing.assert_raises_regex(
        RuntimeError,
        "MODEL_NATIVE_MTF_ROUTE_INVALID",
    ):
        htf.get_model_native_multi_tf_route_windows(
            features,
            decision_bar_start=decision,
            per_tf_seq_lens=lengths,
            route_timeframes=("M5", "M15", "H1", "H4"),
            base_bar_duration=pd.Timedelta(seconds=EXIT_DECISION_BAR_SECONDS),
        )


def test_v4_cache_surface_excludes_every_open_trailing_resample_bucket(
    monkeypatch,
) -> None:
    # V30 package 3 (2026-08-13): the D1 bin opens on the trading day (22:00
    # UTC), so a fixture that starts at 2021-01-04T00:00Z has no COMPLETE D1
    # bar until the 2021-01-04T22:00Z bin closes at 2021-01-05T22:00Z. 419 M5
    # bars (ending 2021-01-05T10:50Z) no longer contain one; 560 bars end at
    # 2021-01-05T22:35Z and contain exactly one, keeping this test's subject
    # (the OPEN trailing bucket must be excluded on every TF) intact.
    source = _bars(560, seed=37)

    def finite_contract(
        frame: pd.DataFrame, *, timeframe: str, **_kwargs
    ) -> pd.DataFrame:
        assert timeframe in htf.MULTI_TF_RESAMPLE_RULES
        values = np.ones(
            (len(frame), htf.MULTI_TF_FEATURE_COUNT_V4),
            dtype=np.float32,
        )
        return pd.DataFrame(
            values,
            index=frame.index,
            columns=htf.MULTI_TF_PER_BAR_FEATURES_V4,
        )

    monkeypatch.setattr(htf, "compute_per_bar_features_v4", finite_contract)
    built = htf.build_multi_tf_per_bar_features_v4(
        source,
        v29_registry_constants=V29_TEST_REGISTRY_CONSTANTS,
        volatility_squeeze_artifacts=_SQUEEZE_TEST_ARTIFACTS,
    )

    assert source.index[-1] == pd.Timestamp("2021-01-05T22:35:00Z")
    assert built["M5"].index[-1] == pd.Timestamp("2021-01-05T22:35:00Z")
    assert built["M15"].index[-1] == pd.Timestamp("2021-01-05T22:15:00Z")
    assert built["H1"].index[-1] == pd.Timestamp("2021-01-05T21:00:00Z")
    assert built["H4"].index[-1] == pd.Timestamp("2021-01-05T18:00:00Z")
    # Trading-day D1 label, not the retired midnight one (V30 package 3).
    assert built["D1"].index[-1] == pd.Timestamp("2021-01-04T22:00:00Z")


def test_v4_closed_geometry_floors_friday_h4_and_d1_to_real_labels() -> None:
    source_index = pd.date_range(
        "2026-07-20T00:00:00Z",
        "2026-07-24T20:55:00Z",
        freq="5min",
    )

    expected = htf.build_multi_tf_v4_closed_timestamp_indices(source_index)

    assert expected["M5"][-1] == pd.Timestamp("2026-07-24T20:55:00Z")
    assert expected["M15"][-1] == pd.Timestamp("2026-07-24T20:45:00Z")
    assert expected["H1"][-1] == pd.Timestamp("2026-07-24T20:00:00Z")
    assert expected["H4"][-1] == pd.Timestamp("2026-07-24T14:00:00Z")
    # V30 package 3 (2026-08-13): the D1 grid is anchored at 22:00 UTC, so the
    # last bar closed by the Friday 20:55Z decision (available 21:00Z) is the
    # bin opened Wednesday 22:00Z, which closed Thursday 22:00Z. The Thursday
    # 22:00Z bin is still open at 21:00Z Friday and is correctly excluded.
    assert expected["D1"][-1] == pd.Timestamp("2026-07-22T22:00:00Z")


# ---------------------------------------------------------------------------
# V29 Phase A per-TF event additions (trend_ema GAP-1/2/3 + momentum G1/G2).
# ---------------------------------------------------------------------------


def test_v29_edge_helpers_fire_exactly_once_per_crossing() -> None:
    series = pd.Series(
        [np.nan, np.nan, -1.0, -0.5, 0.5, 1.0, 0.0, -2.0, 3.0, 3.0]
    )
    up = htf._cross_up_event(series).to_numpy(dtype=np.float64)
    down = htf._cross_down_event(series).to_numpy(dtype=np.float64)
    # One fire per crossing; a touch of exactly zero does not fire the
    # opposite side until the sign actually flips.
    assert np.array_equal(
        up,
        np.array(
            [np.nan, np.nan, np.nan, 0, 1, 0, 0, 0, 1, 0], dtype=np.float64
        ),
        equal_nan=True,
    )
    assert np.array_equal(
        down,
        np.array(
            [np.nan, np.nan, np.nan, 0, 0, 0, 0, 1, 0, 0], dtype=np.float64
        ),
        equal_nan=True,
    )


def test_v29_bars_since_event_counts_on_the_valid_suffix() -> None:
    from gx1.features.event_age_v1 import raw_event_age_bars

    event = np.array([False, False, False, True, False, False, True, False])
    valid = np.array([False, False, True, True, True, True, True, True])
    ages = raw_event_age_bars(event, valid)
    assert np.array_equal(
        ages,
        np.array([np.nan, np.nan, np.nan, 0, 1, 2, 0, 1], dtype=np.float64),
        equal_nan=True,
    )
    with np.testing.assert_raises_regex(
        RuntimeError,
        "RAW_EVENT_AGE_VALIDITY_NOT_ONE_PREFIX",
    ):
        raw_event_age_bars(
            event,
            np.array([True, False, True, True, True, True, True, True]),
        )


def test_v29_trend_events_bit_identical_to_local_layer_formula() -> None:
    """The per-TF 50/200 fields must equal the local price-derived layer's
    exact formulas (shared classic SMA-seeded EMA,
    spread = ema50 - ema200, cross = (spread>0)&(spread.shift(1)<=0))."""
    bars = _bars(4000, seed=23)
    matrix = _compute_v4(bars, timeframe="M5")
    close = bars["close"].astype(np.float64)
    ema50 = htf._ema(close, 50)
    ema200 = htf._ema(close, 200)
    spread = ema50 - ema200

    def check_cross_pair(gap: pd.Series, up_name: str, down_name: str) -> None:
        previous = gap.shift(1)
        valid = (gap.notna() & previous.notna()).to_numpy()
        expected_up = ((gap > 0) & (previous <= 0)).astype(np.float64)
        expected_down = ((gap < 0) & (previous >= 0)).astype(np.float64)
        observed_up = matrix[up_name].to_numpy(dtype=np.float64)
        observed_down = matrix[down_name].to_numpy(dtype=np.float64)
        assert np.array_equal(
            observed_up[valid], expected_up.to_numpy()[valid]
        ), up_name
        assert np.array_equal(
            observed_down[valid], expected_down.to_numpy()[valid]
        ), down_name
        assert not np.isfinite(observed_up[~valid]).any(), up_name
        assert not np.isfinite(observed_down[~valid]).any(), down_name
        assert observed_up[valid].sum() > 0, up_name
        assert observed_down[valid].sum() > 0, down_name

    check_cross_pair(spread, "ema50_200_cross_up", "ema50_200_cross_down")
    check_cross_pair(
        close - ema50, "price_x_ema50_cross_up", "price_x_ema50_cross_down"
    )
    check_cross_pair(
        close - ema200, "price_x_ema200_cross_up", "price_x_ema200_cross_down"
    )

    state_valid = spread.notna().to_numpy()
    expected_state = (spread > 0).astype(np.float64).to_numpy()
    observed_state = matrix["ema50_200_bull_state"].to_numpy(dtype=np.float64)
    assert np.array_equal(observed_state[state_valid], expected_state[state_valid])
    assert not np.isfinite(observed_state[~state_valid]).any()

    atr14 = htf._atr(
        bars["high"].astype(np.float64),
        bars["low"].astype(np.float64),
        close,
        14,
    )
    atr_positive = atr14.where(atr14 > 0.0)
    expected_spread_atr = (
        (spread / atr_positive).to_numpy(dtype=np.float64)
    ).astype(np.float32)
    observed_spread_atr = matrix["ema50_200_spread_atr"].to_numpy(
        dtype=np.float32
    )
    assert np.array_equal(
        observed_spread_atr, expected_spread_atr, equal_nan=True
    )


def test_v29_rsi_threshold_events_use_raw_wilder_series() -> None:
    bars = _bars(4000, seed=7)
    matrix = _compute_v4(bars, timeframe="M5")
    close = bars["close"].astype(np.float64)
    rsi = htf._rsi(close, 14)
    rsi.iloc[:14] = np.nan
    previous = rsi.shift(1)
    valid = (rsi.notna() & previous.notna()).to_numpy()
    assert htf.RSI_WILDER_OVERSOLD == 30.0
    assert htf.RSI_WILDER_OVERBOUGHT == 70.0
    assert htf.RSI_WILDER_MIDLINE == 50.0
    assert htf.RSI_EXTREME_BAND_WIDTH == 20.0
    cases = (
        ("rsi_cross_up_30", (rsi > 30.0) & (previous <= 30.0)),
        ("rsi_cross_down_70", (rsi < 70.0) & (previous >= 70.0)),
        ("rsi_cross_up_50", (rsi > 50.0) & (previous <= 50.0)),
        ("rsi_cross_down_50", (rsi < 50.0) & (previous >= 50.0)),
    )
    for name, expected in cases:
        observed = matrix[name].to_numpy(dtype=np.float64)
        assert np.array_equal(
            observed[valid],
            expected.astype(np.float64).to_numpy()[valid],
        ), name
        assert not np.isfinite(observed[~valid]).any(), name
        assert observed[valid].sum() > 0, name

    # Raw age is unavailable before the first actual extreme and uncapped after.
    n = len(bars)
    rsi_np = rsi.to_numpy(dtype=np.float64)
    rsi_valid = np.isfinite(rsi_np)
    extreme = rsi_valid & (np.abs(rsi_np - 50.0) >= 20.0)
    assert extreme.any()
    expected_age = np.full(n, np.nan, dtype=np.float64)
    anchor = None
    for i in range(n):
        if not rsi_valid[i]:
            continue
        if extreme[i]:
            anchor = i
        if anchor is not None:
            expected_age[i] = float(i - anchor)
    observed_age = matrix["rsi_extreme_event_age_bars"].to_numpy(dtype=np.float64)
    assert np.array_equal(
        observed_age.astype(np.float32),
        expected_age.astype(np.float32),
        equal_nan=True,
    )
    assert np.all(observed_age[extreme] == 0.0)


def test_v29_mom20_flips_and_cross_age_semantics() -> None:
    bars = _bars(4000, seed=23)
    matrix = _compute_v4(bars, timeframe="M5")
    close = bars["close"].astype(np.float64)
    atr14 = htf._atr(
        bars["high"].astype(np.float64),
        bars["low"].astype(np.float64),
        close,
        14,
    )
    atr_positive = atr14.where(atr14 > 0.0)
    mom20 = (close - close.shift(20)) / atr_positive
    previous = mom20.shift(1)
    valid = (mom20.notna() & previous.notna()).to_numpy()
    expected_up = ((mom20 > 0) & (previous <= 0)).astype(np.float64).to_numpy()
    expected_down = (
        ((mom20 < 0) & (previous >= 0)).astype(np.float64).to_numpy()
    )
    observed_up = matrix["mom20_sign_flip_up"].to_numpy(dtype=np.float64)
    observed_down = matrix["mom20_sign_flip_down"].to_numpy(dtype=np.float64)
    assert np.array_equal(observed_up[valid], expected_up[valid])
    assert np.array_equal(observed_down[valid], expected_down[valid])
    assert observed_up[valid].sum() > 0
    assert observed_down[valid].sum() > 0

    # Raw state age resets at state flips and otherwise increments uncapped.
    state = matrix["ema50_200_bull_state"].to_numpy(dtype=np.float64)
    state_age = matrix["ema50_200_state_age_bars"].to_numpy(dtype=np.float64)
    finite = np.isfinite(state)
    expected = np.full(len(state), np.nan, dtype=np.float64)
    run = 0.0
    previous_state = None
    for i in np.where(finite)[0]:
        if previous_state is None or state[i] != previous_state:
            run = 0.0
        else:
            run += 1.0
        previous_state = state[i]
        expected[i] = run
    assert np.array_equal(
        state_age.astype(np.float32), expected.astype(np.float32), equal_nan=True
    )
    fires = np.where(
        (matrix["ema50_200_cross_up"].to_numpy(dtype=np.float64) == 1.0)
        | (matrix["ema50_200_cross_down"].to_numpy(dtype=np.float64) == 1.0)
    )[0]
    assert len(fires) > 0
    assert np.all(state_age[fires] == 0.0)


def test_v29_divergence_matches_confirmed_pivot_definition() -> None:
    """Spec mirror: divergence must use smc_v1's confirmed-pivot machinery
    (one pivot truth, SWING_LOOKBACK=3) and fire only at the confirmation
    bar of a new pivot pair — never earlier (no lookahead)."""
    from gx1.features.smc_v1 import (
        SWING_LOOKBACK,
        _detect_swing_pivots,
        _track_recent_swings,
    )

    bars = _bars(4000, seed=19)
    matrix = _compute_v4(bars, timeframe="M5")
    n = len(bars)
    high = bars["high"].to_numpy(dtype=np.float64)
    low = bars["low"].to_numpy(dtype=np.float64)
    close = bars["close"].astype(np.float64)
    rsi = htf._rsi(close, 14)
    rsi.iloc[:14] = np.nan
    rsi_np = rsi.to_numpy(dtype=np.float64)
    rsi_valid = np.isfinite(rsi_np)
    sh_mask, sl_mask = _detect_swing_pivots(high, low, SWING_LOOKBACK)
    last_sh, prev_sh, last_sl, prev_sl = _track_recent_swings(
        sh_mask, sl_mask, SWING_LOOKBACK
    )
    lh = np.clip(last_sh, 0, n - 1)
    ph = np.clip(prev_sh, 0, n - 1)
    ll = np.clip(last_sl, 0, n - 1)
    pl = np.clip(prev_sl, 0, n - 1)
    new_sh = last_sh != np.roll(last_sh, 1)
    new_sh[0] = False
    new_sl = last_sl != np.roll(last_sl, 1)
    new_sl[0] = False
    bear_defined = (prev_sh >= 0) & rsi_valid[ph]
    bull_defined = (prev_sl >= 0) & rsi_valid[pl]
    expected_bear = np.where(
        bear_defined,
        (
            new_sh
            & bear_defined
            & (high[lh] > high[ph])
            & (rsi_np[lh] < rsi_np[ph])
        ).astype(np.float64),
        np.nan,
    )
    expected_bull = np.where(
        bull_defined,
        (
            new_sl
            & bull_defined
            & (low[ll] < low[pl])
            & (rsi_np[ll] > rsi_np[pl])
        ).astype(np.float64),
        np.nan,
    )
    observed_bear = matrix["bear_divergence_event"].to_numpy(dtype=np.float64)
    observed_bull = matrix["bull_divergence_event"].to_numpy(dtype=np.float64)
    assert np.array_equal(observed_bear, expected_bear, equal_nan=True)
    assert np.array_equal(observed_bull, expected_bull, equal_nan=True)

    atr14 = htf._atr(
        bars["high"].astype(np.float64),
        bars["low"].astype(np.float64),
        close,
        14,
    )
    atr_positive = atr14.where(atr14 > 0.0).to_numpy(dtype=np.float64)
    raw_bear_magnitude = (
        (rsi_np[ph] - rsi_np[lh]) / htf.RSI_WILDER_MIDLINE
    ) * ((high[lh] - high[ph]) / atr_positive[lh])
    raw_bull_magnitude = (
        (rsi_np[ll] - rsi_np[pl]) / htf.RSI_WILDER_MIDLINE
    ) * ((low[pl] - low[ll]) / atr_positive[ll])
    expected_bear_strength = np.where(
        bear_defined,
        np.where(expected_bear == 1.0, raw_bear_magnitude, 0.0),
        np.nan,
    )
    expected_bull_strength = np.where(
        bull_defined,
        np.where(expected_bull == 1.0, raw_bull_magnitude, 0.0),
        np.nan,
    )
    np.testing.assert_array_equal(
        matrix["bear_divergence_strength"].to_numpy(dtype=np.float32),
        expected_bear_strength.astype(np.float32),
    )
    np.testing.assert_array_equal(
        matrix["bull_divergence_strength"].to_numpy(dtype=np.float32),
        expected_bull_strength.astype(np.float32),
    )

    bear_fires = np.where(observed_bear == 1.0)[0]
    bull_fires = np.where(observed_bull == 1.0)[0]
    assert len(bear_fires) > 0
    assert len(bull_fires) > 0
    # Confirmation lag: the newly confirmed pivot of every firing pair sits
    # exactly SWING_LOOKBACK bars before the event bar.
    assert np.all(last_sh[bear_fires] == bear_fires - SWING_LOOKBACK)
    assert np.all(last_sl[bull_fires] == bull_fires - SWING_LOOKBACK)
    # Age resets to zero at every divergence event.
    observed_age = matrix["divergence_event_age_bars"].to_numpy(dtype=np.float64)
    assert np.all(observed_age[bear_fires] == 0.0)
    assert np.all(observed_age[bull_fires] == 0.0)

    first_confirmation = int(min(bear_fires[0], bull_fires[0]))
    prefix = htf.compute_v29_momentum_event_block_from_ohlc(
        bars.iloc[: first_confirmation + 1][["high", "low", "close"]]
    )
    full_local = htf.compute_v29_momentum_event_block_from_ohlc(
        bars[["high", "low", "close"]]
    )
    for name in (
        "bear_divergence_event",
        "bull_divergence_event",
        "bear_divergence_strength",
        "bull_divergence_strength",
    ):
        np.testing.assert_array_equal(
            prefix[name].to_numpy(dtype=np.float32),
            full_local[name].iloc[: first_confirmation + 1].to_numpy(
                dtype=np.float32
            ),
        )


def _engineered_divergence_bars() -> tuple[pd.DataFrame, int]:
    """Flat warmup, impulsive rally to peak A (high RSI), sharp decline, weak
    grind to a marginally higher peak B (lower RSI): a textbook bearish
    divergence whose B pivot confirms exactly SWING_LOOKBACK bars later."""
    closes = [100.0]
    for i in range(250):
        closes.append(closes[-1] + (0.05 if i % 2 == 0 else -0.05))
    for _ in range(10):
        closes.append(closes[-1] + 2.0)
    peak_a_close = closes[-1]
    for _ in range(8):
        closes.append(closes[-1] - 1.5)
    while closes[-1] <= peak_a_close + 0.5:
        closes.append(closes[-1] + 0.4)
        closes.append(closes[-1] - 0.2)
    peak_b = len(closes) - 2
    for _ in range(6):
        closes.append(closes[-1] - 1.0)
    for i in range(10):
        closes.append(closes[-1] + (0.05 if i % 2 == 0 else -0.05))
    close = np.asarray(closes, dtype=np.float64)
    open_ = np.concatenate([[close[0]], close[:-1]])
    rising = close >= open_
    high = np.where(rising, close + 0.3, open_ + 0.05)
    low = np.where(rising, open_ - 0.05, close - 0.3)
    index = pd.date_range(
        "2021-01-04", periods=len(close), freq="5min", tz="UTC"
    )
    bars = pd.DataFrame(
        {
            "open": open_,
            "high": high,
            "low": low,
            "close": close,
            "volume": np.full(len(close), 1.0),
        },
        index=index,
    )
    return bars, peak_b


def test_v29_divergence_fires_at_confirmation_and_never_early() -> None:
    from gx1.features.smc_v1 import SWING_LOOKBACK

    bars, peak_b = _engineered_divergence_bars()
    matrix = _compute_v4(bars, timeframe="M5")
    bear = matrix["bear_divergence_event"].fillna(0.0).to_numpy(
        dtype=np.float64
    )
    assert bear.sum() == 1.0
    assert bear[peak_b + SWING_LOOKBACK] == 1.0
    assert (
        matrix["bull_divergence_event"]
        .fillna(0.0)
        .to_numpy(dtype=np.float64)
        .sum()
        == 0.0
    )
    observed_age = matrix["divergence_event_age_bars"].to_numpy(dtype=np.float64)
    assert observed_age[peak_b + SWING_LOOKBACK] == 0.0
    # Causality: without the SWING_LOOKBACK confirmation bars after peak B the
    # pivot is unconfirmed and no divergence may exist anywhere.
    truncated = _compute_v4(bars.iloc[: peak_b + SWING_LOOKBACK], timeframe="M5")
    assert (
        truncated["bear_divergence_event"]
        .fillna(0.0)
        .to_numpy(dtype=np.float64)
        .sum()
        == 0.0
    )


def test_v29_event_columns_have_one_honest_warmup_prefix() -> None:
    bars = _bars(4000, seed=23)
    matrix = _compute_v4(bars, timeframe="M5")
    v29_names = (
        htf.MULTI_TF_V4_TREND_EVENT_FEATURES
        + htf.MULTI_TF_V4_MOMENTUM_EVENT_FEATURES
    )
    for name in v29_names:
        column = matrix[name].to_numpy(dtype=np.float64)
        finite = np.isfinite(column)
        assert finite.any(), name
        first = int(np.argmax(finite))
        assert finite[first:].all(), name
        assert not finite[:first].any(), name
    # Exact honest floors: local-layer min_periods (50/200), the file's own
    # 14-row RSI mask, the 20-bar momentum lag; +1 wherever the edge trigger
    # needs the previous bar.  Divergence floors are pivot/data-dependent and
    # are covered by the single-prefix loop above.
    expected_first_finite = {
        "ema50_200_spread_atr": 199,
        "ema50_200_bull_state": 199,
        "ema50_200_cross_up": 200,
        "ema50_200_cross_down": 200,
        "ema50_200_state_age_bars": 199,
        "price_x_ema50_cross_up": 50,
        "price_x_ema50_cross_down": 50,
        "price_x_ema200_cross_up": 200,
        "price_x_ema200_cross_down": 200,
        "price_vs_ema50_state_age_bars": 49,
        "price_vs_ema200_state_age_bars": 199,
        "rsi_cross_up_30": 15,
        "rsi_cross_down_70": 15,
        "rsi_cross_up_50": 15,
        "rsi_cross_down_50": 15,
        "mom20_sign_flip_up": 21,
        "mom20_sign_flip_down": 21,
    }
    for name, first_row in expected_first_finite.items():
        column = matrix[name].to_numpy(dtype=np.float64)
        assert int(np.argmax(np.isfinite(column))) == first_row, name
    warmup = htf.validate_causal_feature_matrix(
        matrix.to_numpy(dtype=np.float64),
        expected_width=htf.MULTI_TF_FEATURE_COUNT_V4,
        context="HTF_V4_V29_TEST",
    )
    assert warmup >= 200


def test_v4_closed_geometry_rejects_off_grid_source_timestamp() -> None:
    source_index = pd.DatetimeIndex(
        [
            pd.Timestamp("2026-07-24T20:50:00Z"),
            pd.Timestamp("2026-07-24T20:55:00.000001Z"),
        ]
    )

    with np.testing.assert_raises_regex(
        RuntimeError,
        "HTF_V4_SOURCE_TIMESTAMP_GEOMETRY_INVALID",
    ):
        htf.build_multi_tf_v4_closed_timestamp_indices(source_index)


def _declared_alias_pair_defects(
    pairs, emitted: tuple[str, ...]
) -> list[str]:
    """Report every way a declared alias pair fails to bind on this surface.

    ``build_multi_tf_v4_liveness_contract`` walks
    ``MULTI_TF_PER_BAR_FEATURES_V4`` in order and builds the duplicate pair as
    ``(already_seen_name, later_name)``.  A declared pair therefore only ever
    matches when both names are emitted AND they are written in that order.
    """

    order = {name: index for index, name in enumerate(emitted)}
    defects: list[str] = []
    for pair in pairs:
        if not isinstance(pair, tuple) or len(pair) != 2:
            defects.append(f"malformed:{pair!r}")
            continue
        first, second = pair
        missing = [name for name in (first, second) if name not in order]
        if missing:
            defects.append(f"not_emitted:{pair!r}:{missing}")
            continue
        if first == second:
            defects.append(f"self_pair:{pair!r}")
            continue
        if order[first] > order[second]:
            defects.append(f"reversed_against_surface_order:{pair!r}")
    return defects


def test_declared_alias_pairs_name_fields_the_surface_emits() -> None:
    """A declared alias may exist, but never silently and never stale.

    Same shape as
    ``test_every_semantic_exemption_is_declared_justified_and_still_real`` in
    tests/test_entry_full_input_liveness_contract.py.  Until 2026-08-15
    ``HTF_V4_DECLARED_ALIAS_PAIRS`` held three pairs of which five of the six
    names had already left ``MULTI_TF_PER_BAR_FEATURES_V4``: the exemption
    branch in the duplicate check could not fire for any of them, so the
    declaration had silently stopped protecting anything.  A stale entry is
    how a gate quietly stops binding.
    """

    emitted = htf.MULTI_TF_PER_BAR_FEATURES_V4
    assert (
        _declared_alias_pair_defects(htf.HTF_V4_DECLARED_ALIAS_PAIRS, emitted)
        == []
    )

    # The check must be able to FAIL, or an empty declaration would make this
    # test vacuous: the exact three pairs retired on 2026-08-15 are rejected.
    retired = (
        ("body_pct", "mtf_pattern_body_share"),
        ("upper_wick_pct", "mtf_pattern_upper_wick_share"),
        ("lower_wick_pct", "mtf_pattern_lower_wick_share"),
    )
    assert len(_declared_alias_pair_defects(retired, emitted)) == len(retired)


def test_mid_series_zero_range_bar_takes_the_sibling_share_convention() -> None:
    """A high == low bar after warmup must not abort the per-TF build.

    The per-TF ``body_pct`` used to divide by
    ``(high - low).where((high - low) > 0.0)``, so one zero-range bar put a
    NaN in the MIDDLE of the surface and ``validate_causal_feature_matrix`` --
    which this producer runs on its own output -- rejected the whole timeframe
    as "not one causal warmup prefix".  MEASURED on the complete declared
    native M5 tape (XAU_M5_NATIVE_2019_20260804_V4, 537,861 rows,
    2019-01-01..2026-08-04): 215 zero-range M5 bars, 24 after M15 resampling
    and 14 after H1 resampling, all of them past the warmup prefix -- so the
    abort was real, not hypothetical.

    ``body_pct`` itself was RETIRED on 2026-08-19 as an exact duplicate (see
    ``test_retired_per_tf_body_pct_is_exactly_the_unsigned_signed_twin``), but
    the convention it adopted is unchanged and now lives only in the sibling
    candle owner ``gx1.features.entry_candle_primitives_v1``: on a zero-range
    bar the range SHARE is an explicit 0.0.  This test asserts it on the
    surviving column, in the same position in the surface, so the mid-series
    hole cannot come back.

    ``mtf_candle_raw_zero_range_flag`` used to sit beside it and mark the row.
    It was retired on 2026-08-15 (constant post-warmup on H4/D1, hence a hard
    liveness RED with no scaleable exemption).  The distinction survives it
    exactly: the three range shares partition the range, so all three are zero
    if and only if ``high == low``.  That biconditional is asserted here on
    the per-TF surface, where the flag used to be read.
    """

    bars = _bars(4000, seed=77)
    zero_row = 3000
    close_price = float(bars["close"].iloc[zero_row])
    for column in ("open", "high", "low", "close"):
        bars.iloc[zero_row, bars.columns.get_loc(column)] = close_price

    observed = _compute_v4(bars, timeframe="M5")

    assert "mtf_candle_raw_zero_range_flag" not in observed.columns
    assert "body_pct" not in observed.columns
    assert observed["mtf_candle_raw_body_signed_range"].iloc[zero_row] == 0.0

    share_columns = (
        "mtf_candle_raw_body_signed_range",
        "mtf_candle_raw_upper_wick_share",
        "mtf_candle_raw_lower_wick_share",
    )
    shares = observed[list(share_columns)].to_numpy(dtype=np.float64)
    recovered = (shares == 0.0).all(axis=1)
    truth = (
        bars["high"].to_numpy(dtype=np.float64)
        == bars["low"].to_numpy(dtype=np.float64)
    )
    np.testing.assert_array_equal(recovered, truth)
    assert bool(recovered[zero_row])

    # The surviving body share has no warmup of its own (both operands are
    # finite from row 0), so ANY NaN in it is a mid-series hole by
    # construction.
    body_share = observed["mtf_candle_raw_body_signed_range"].to_numpy(
        dtype=np.float64
    )
    assert np.isfinite(body_share).all()

    # And a hole at exactly this row is what the gate rejects -- the failure
    # the retired NaN mask produced on every real timeframe that contains a
    # zero-range bar.
    holed = body_share.reshape(-1, 1).copy()
    holed[zero_row, 0] = np.nan
    with np.testing.assert_raises_regex(
        RuntimeError, "not one causal warmup prefix"
    ):
        htf.validate_causal_feature_matrix(
            holed, expected_width=1, context="HTF_V4_ZERO_RANGE_TEST"
        )


def test_retired_per_tf_body_pct_is_exactly_the_unsigned_signed_twin() -> None:
    """The arithmetic that justified retiring the per-TF ``body_pct``.

    ``body_pct`` emitted ``abs(close - open) / (high - low)`` where the range
    was strictly positive and the storage ``0.0`` where ``high == low``.  The
    sibling causal candle owner emits, from the same frame and into
    ``mtf_candle_raw_body_signed_range``, ``(close - open) / (high - low)``
    under the identical condition and the identical zero-range convention, so
    the retired field was ``abs`` of a column that stays on the surface, and
    only the survivor carries the SIGN.

    MEASURED on the complete declared native M5 tape
    (XAU_M5_NATIVE_2019_20260804_V4, 537,861 rows) resampled by this owner,
    post-warmup, on all five lanes, in float64 and in the served float32:
    max|body_pct - abs(twin)| == 0.0 exactly on M5 (537,657 rows), M15
    (179,154), H1 (44,669), H4 (11,524) and D1 (1,754); the twin is negative
    on 265,508 of the 537,657 M5 rows, so the discarded sign was real
    evidence.

    NOT VACUOUS.  Nothing here reads a name list: the expected value is
    recomputed from the frame's raw OHLC by the retired formula, so this test
    fails if the surviving twin's arithmetic changes (a different denominator,
    a clip, a different zero-range convention), not merely if a name moves.
    The rule-4 completeness claim -- that the bar's shape is fully described
    without ``body_pct`` -- is asserted as the exact range partition beside it.
    """

    bars = _bars(600, seed=1908)
    zero_row = 400
    close_price = float(bars["close"].iloc[zero_row])
    for column in ("open", "high", "low", "close"):
        bars.iloc[zero_row, bars.columns.get_loc(column)] = close_price

    observed = _compute_v4(bars, timeframe="M5")
    assert "body_pct" not in observed.columns

    open_ = bars["open"].to_numpy(dtype=np.float64)
    high = bars["high"].to_numpy(dtype=np.float64)
    low = bars["low"].to_numpy(dtype=np.float64)
    close = bars["close"].to_numpy(dtype=np.float64)
    bar_range = high - low
    positive = bar_range > 0.0
    assert positive.sum() > 0 and (~positive).sum() == 1

    # The retired producer's own formula, recomputed here from raw OHLC.
    retired_body_pct = np.zeros_like(bar_range)
    retired_body_pct[positive] = (
        np.abs(close - open_)[positive] / bar_range[positive]
    )

    # ``compute_per_bar_features_v4`` emits float32, so the retired field and
    # its twin met as float32 on the shipped surface: there the identity is
    # BIT-EXACT, which is what the tape measurement above reports.  Against a
    # float64 recomputation the only gap is that emission cast, bounded by
    # float32 machine epsilon -- a declared constant of the storage dtype, not
    # a tolerance chosen to make the test pass.
    twin = observed["mtf_candle_raw_body_signed_range"].to_numpy(
        dtype=np.float64
    )
    np.testing.assert_array_equal(
        np.abs(twin).astype(np.float32),
        retired_body_pct.astype(np.float32),
    )
    np.testing.assert_allclose(
        np.abs(twin),
        retired_body_pct,
        rtol=float(np.finfo(np.float32).eps),
        atol=0.0,
    )

    # The sign is the information the retirement ADDS, not removes.
    expected_sign = np.sign(close - open_)
    expected_sign[~positive] = 0.0
    np.testing.assert_array_equal(np.sign(twin), expected_sign)
    assert (twin < 0.0).sum() > 0 and (twin > 0.0).sum() > 0

    # Rule 4 completeness: the three retained shares partition the range
    # exactly, so the body share is not the only description of bar shape and
    # nothing about the candle's geometry left the learned path.
    upper = observed["mtf_candle_raw_upper_wick_share"].to_numpy(
        dtype=np.float64
    )
    lower = observed["mtf_candle_raw_lower_wick_share"].to_numpy(
        dtype=np.float64
    )
    # Same float32 emission bound as above; the partition itself is exact.
    eps32 = float(np.finfo(np.float32).eps)
    partition = np.abs(twin) + upper + lower
    np.testing.assert_allclose(partition[positive], 1.0, rtol=0.0, atol=4 * eps32)
    np.testing.assert_array_equal(partition[~positive], 0.0)
    np.testing.assert_allclose(
        upper[positive],
        (high - np.maximum(open_, close))[positive] / bar_range[positive],
        rtol=eps32,
        atol=0.0,
    )
    np.testing.assert_allclose(
        lower[positive],
        (np.minimum(open_, close) - low)[positive] / bar_range[positive],
        rtol=eps32,
        atol=0.0,
    )


def test_v31_vwap_slope_differences_a_rolling_window_not_a_session_accumulator() -> None:
    """The per-TF VWAP slope is the 5-bar difference of a ROLLING 5-bar VWAP.

    Until 2026-08-18 the emitted column differenced ``local_cycle_vwap``, which
    is a CUMULATIVE session VWAP on every intraday lane and resets at each
    session boundary, so on any window straddling a reset the subtrahend
    belonged to a different accumulation.  Both halves fail against the
    pre-change owner: the old name is asserted absent, and on the intraday lanes
    the emitted values must equal the rolling-5 difference, which the session
    accumulator demonstrably does not produce.
    """

    assert "vwap_local_cycle_slope_atr" not in htf.MULTI_TF_PER_BAR_FEATURES_V4
    assert "vwap_rolling5_slope_atr" in htf.MULTI_TF_PER_BAR_FEATURES_V4
    # The distance field still reads the session accumulator; only the slope moved.
    assert "vwap_local_cycle_dist_atr" in htf.MULTI_TF_PER_BAR_FEATURES_V4

    bars = _bars(4_000, seed=515)
    closed_indices = htf.build_multi_tf_v4_closed_timestamp_indices(bars.index)
    distinguishable = 0
    for timeframe in htf.MULTI_TF_RESAMPLE_RULES:
        resampled = htf._resample_ohlcv(bars, timeframe).loc[
            closed_indices[timeframe]
        ]
        close = resampled["close"].astype(np.float64)
        volume = resampled["volume"].astype(np.float64)
        _atr14, atr_positive = htf.wilder_atr14_positive(
            resampled["high"].astype(np.float64),
            resampled["low"].astype(np.float64),
            close,
        )
        rolling5 = htf._rolling_vwap(close, volume, 5)
        expected = ((rolling5 - rolling5.shift(5)) / atr_positive).to_numpy(
            dtype=np.float64
        )
        observed = _compute_v4(resampled, timeframe=timeframe)[
            "vwap_rolling5_slope_atr"
        ].to_numpy(dtype=np.float64)
        # The repaired column no longer depends on which local-cycle owner the
        # timeframe selects: the same formula, with the same honest warmup, on
        # every lane. Where the fixture is too short for a lane to define a
        # single row (D1 needs ~25 daily bars for rolling-5 + shift(5) + Wilder
        # ATR14), the emitted column must be entirely unavailable there rather
        # than parked at zero.
        assert np.array_equal(np.isfinite(observed), np.isfinite(expected)), timeframe
        defined = np.isfinite(expected) & np.isfinite(observed)
        if not defined.any():
            continue
        np.testing.assert_allclose(
            observed[defined], expected[defined], rtol=1e-6, atol=1e-9
        )

        if timeframe == "D1":
            # D1's retired operand already WAS the rolling 5-bar VWAP, so the
            # emitted float there is unchanged and nothing distinguishes them.
            continue
        session = htf._session_vwap(
            close,
            volume,
            bar_duration=pd.Timedelta(htf.MULTI_TF_RESAMPLE_RULES[timeframe]),
        )
        retired = ((session - session.shift(5)) / atr_positive).to_numpy(
            dtype=np.float64
        )
        comparable = defined & np.isfinite(retired)
        if not comparable.any():
            continue
        assert not np.allclose(
            observed[comparable], retired[comparable], rtol=1e-6, atol=1e-9
        ), timeframe
        distinguishable += 1
    # The fixture must actually exercise the difference on intraday lanes,
    # otherwise the repair claim rests on nothing.
    assert distinguishable >= 2
