#!/usr/bin/env python3
"""
Prebuilt Identity Gate for GX1 (TRUTH/SMOKE).

Purpose:
- Enforce that the replay is using the canonical prebuilt symlink.
- Verify that the prebuilt schema is clean (no prob_* columns).
- Fail early with a clear capsule if there is a mismatch.

Contract (when truth_or_smoke=True):
- Requires GX1_CANONICAL_PREBUILT_PATH environment variable to be set, or --prebuilt-parquet must point to canonical.
- Resolves the actual prebuilt file used by the replay.
- Asserts that the actual prebuilt is the canonical symlink (or resolves to canonical target).
- Checks schema for prob_* columns (must be absent).
- If mismatch: write PREBUILT_IDENTITY_FATAL.json capsule and exit code 2.
- Always write PREBUILT_IDENTITY.md atomically to output_dir (or /tmp fallback).
"""

from __future__ import annotations

import hashlib
import json
import os
import sys
import tempfile
import traceback
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, Optional

try:
    import pyarrow.parquet as pq
except ImportError:
    pq = None

# --- Utility functions (copied from env_identity_gate for self-containment) ---
def _now_utc_compact() -> str:
    return datetime.utcnow().strftime("%Y%m%d_%H%M%S")


def _safe_mkdir(path: Path) -> bool:
    try:
        path.mkdir(parents=True, exist_ok=True)
        return True
    except Exception:
        return False


def _fallback_dir() -> Path:
    root = Path(tempfile.gettempdir()) / "gx1_prebuilt_identity_gate"
    if not _safe_mkdir(root):
        root = Path("/tmp")
    run_dir = root / f"run_{_now_utc_compact()}_{os.getpid()}"
    _safe_mkdir(run_dir)
    return run_dir


def _choose_report_dir(output_dir: Path) -> Path:
    try:
        if output_dir is not None and _safe_mkdir(output_dir):
            return output_dir
    except Exception:
        pass
    return _fallback_dir()


def _write_text_atomic(path: Path, text: str) -> None:
    tmp_path = path.with_suffix(path.suffix + f".tmp.{os.getpid()}")
    with open(tmp_path, "w", encoding="utf-8") as f:
        f.write(text)
        f.flush()
        os.fsync(f.fileno())
    os.replace(tmp_path, path)


def _write_json_atomic(path: Path, obj: Dict[str, Any]) -> None:
    tmp_path = path.with_suffix(path.suffix + f".tmp.{os.getpid()}")
    with open(tmp_path, "w", encoding="utf-8") as f:
        json.dump(obj, f, indent=2, sort_keys=True)
        f.flush()
        os.fsync(f.fileno())
    os.replace(tmp_path, path)


def sha256_file(path: Path) -> str:
    """Compute SHA256 of a file."""
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(4096), b""):
            h.update(chunk)
    return h.hexdigest()


def check_schema_for_prob_columns(path: Path) -> tuple[bool, list[str]]:
    """Check if schema contains prob_* columns. Returns (has_prob, prob_columns)."""
    if pq is None:
        return False, []
    
    try:
        parquet_file = pq.ParquetFile(path)
        schema = parquet_file.schema_arrow
        column_names = [schema.field(i).name for i in range(len(schema))]
        prob_columns = [col for col in column_names if col.startswith("prob_")]
        return len(prob_columns) > 0, prob_columns
    except Exception as e:
        sys.stderr.write(f"[PREBUILT_IDENTITY_GATE] WARNING: Failed to read schema from {path}: {e}\n")
        return False, []


def _render_md(
    prebuilt_path: Path,
    realpath: Path,
    file_sha256: str,
    schema_summary: Dict[str, Any],
    canonical_path: Optional[Path],
    is_canonical: bool,
) -> str:
    """Renders the PREBUILT_IDENTITY report in Markdown format."""
    status = "✅ YES" if is_canonical else "❌ NO"
    
    lines = [
        f"# PREBUILT_IDENTITY",
        f"",
        f"## Prebuilt File",
        f"",
        f"- **Path:** `{prebuilt_path}`",
        f"- **Real Path:** `{realpath}`",
        f"- **Is Symlink:** {prebuilt_path.is_symlink()}",
        f"- **File SHA256:** `{file_sha256}`",
        f"",
        f"## Canonical Check",
        f"",
        f"- **Canonical Path:** `{canonical_path or 'N/A'}`",
        f"- **Is Canonical:** {status}",
        f"",
        f"## Schema Summary",
        f"",
        f"- **Total Columns:** {schema_summary.get('total_columns', 'N/A')}",
        f"- **Has prob_* Columns:** {schema_summary.get('has_prob_columns', False)}",
        f"- **prob_* Columns:** {schema_summary.get('prob_columns', [])}",
        f"",
        f"---",
        f"*Report generated by prebuilt_identity_gate.py at {datetime.utcnow().isoformat()}Z*",
    ]
    return "\n".join(lines)


def run_prebuilt_identity_gate_or_fatal(
    prebuilt_path: Path,
    output_dir: Path,
    truth_or_smoke: bool,
) -> None:
    """
    Run prebuilt identity gate and hard-fail (exit code 2) in TRUTH/SMOKE if mismatch.
    """
    if not truth_or_smoke:
        return
    
    report_dir = _choose_report_dir(output_dir)
    fatal_path = report_dir / "PREBUILT_IDENTITY_FATAL.json"
    md_path = report_dir / "PREBUILT_IDENTITY.md"
    
    # Resolve actual prebuilt path
    if not prebuilt_path.exists():
        msg = f"Prebuilt path does not exist: {prebuilt_path}"
        capsule = {
            "status": "FAIL",
            "message": msg,
            "prebuilt_path": str(prebuilt_path),
            "sys.executable": sys.executable,
            "sys.version": sys.version,
            "cwd": str(Path.cwd()),
        }
        _write_json_atomic(fatal_path, capsule)
        raise SystemExit(2)
    
    # Get real path (resolve symlink)
    try:
        realpath = prebuilt_path.resolve()
    except Exception as e:
        msg = f"Failed to resolve prebuilt path: {e}"
        capsule = {
            "status": "FAIL",
            "message": msg,
            "prebuilt_path": str(prebuilt_path),
            "error": str(e),
        }
        _write_json_atomic(fatal_path, capsule)
        raise SystemExit(2)
    
    # Get canonical path from env or infer from path
    canonical_path_str = os.getenv("GX1_CANONICAL_PREBUILT_PATH")
    canonical_path = None
    if canonical_path_str:
        canonical_path = Path(canonical_path_str).resolve()
    else:
        # Try to infer: look for canonical symlink in same directory
        parent_dir = prebuilt_path.parent
        # Common canonical symlink names
        for name in [
            "xauusd_m5_2024_features_v10_ctx.parquet",
            "xauusd_m5_2025_features_v10_ctx.parquet",
            prebuilt_path.name,  # If the path itself is the canonical name
        ]:
            candidate = parent_dir / name
            if candidate.is_symlink() or "canonical" in candidate.name.lower():
                canonical_path = candidate.resolve()
                break
    
    # Check if prebuilt is canonical
    is_canonical = False
    if canonical_path:
        # Check if realpath matches canonical target
        if canonical_path.is_symlink():
            canonical_target = canonical_path.resolve()
            is_canonical = (realpath == canonical_target) or (prebuilt_path == canonical_path)
        else:
            is_canonical = (realpath == canonical_path) or (prebuilt_path == canonical_path)
    else:
        # If no canonical specified, check if path itself looks canonical
        name_lower = prebuilt_path.name.lower()
        is_canonical = (
            "canonical" in name_lower or
            prebuilt_path.is_symlink()  # Symlinks are likely canonical
        )
    
    # Compute file SHA256
    try:
        file_sha256 = sha256_file(realpath)
    except Exception as e:
        msg = f"Failed to compute SHA256 for prebuilt: {e}"
        capsule = {
            "status": "FAIL",
            "message": msg,
            "prebuilt_path": str(prebuilt_path),
            "realpath": str(realpath),
            "error": str(e),
        }
        _write_json_atomic(fatal_path, capsule)
        raise SystemExit(2)
    
    # Check schema for prob_* columns
    has_prob, prob_columns = check_schema_for_prob_columns(realpath)
    
    schema_summary = {
        "total_columns": 0,
        "has_prob_columns": has_prob,
        "prob_columns": prob_columns,
    }
    
    if pq is not None:
        try:
            parquet_file = pq.ParquetFile(realpath)
            schema = parquet_file.schema_arrow
            schema_summary["total_columns"] = len(schema)
        except Exception:
            pass
    
    # TRIPWIRE: Hard-fail if not canonical in TRUTH/SMOKE
    if not is_canonical:
        msg = f"Prebuilt is not canonical: path={prebuilt_path}, realpath={realpath}, canonical={canonical_path}"
        capsule = {
            "status": "FAIL",
            "message": msg,
            "prebuilt_path": str(prebuilt_path),
            "realpath": str(realpath),
            "canonical_path": str(canonical_path) if canonical_path else None,
            "is_canonical": False,
            "sys.executable": sys.executable,
            "sys.version": sys.version,
            "cwd": str(Path.cwd()),
        }
        _write_json_atomic(fatal_path, capsule)
        raise SystemExit(2)
    
    # TRIPWIRE: Hard-fail if prob_* columns present
    if has_prob:
        msg = f"Prebuilt contains prob_* columns: {prob_columns}"
        capsule = {
            "status": "FAIL",
            "message": msg,
            "prebuilt_path": str(prebuilt_path),
            "realpath": str(realpath),
            "prob_columns": prob_columns,
            "schema_summary": schema_summary,
        }
        _write_json_atomic(fatal_path, capsule)
        raise SystemExit(2)
    
    # Write PREBUILT_IDENTITY.md
    md_content = _render_md(
        prebuilt_path=prebuilt_path,
        realpath=realpath,
        file_sha256=file_sha256,
        schema_summary=schema_summary,
        canonical_path=canonical_path,
        is_canonical=is_canonical,
    )
    _write_text_atomic(md_path, md_content)


if __name__ == "__main__":
    # CLI for testing
    import argparse
    
    parser = argparse.ArgumentParser(description="Test prebuilt identity gate")
    parser.add_argument("--prebuilt-path", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--truth", action="store_true", help="Run in TRUTH mode")
    args = parser.parse_args()
    
    run_prebuilt_identity_gate_or_fatal(
        prebuilt_path=args.prebuilt_path,
        output_dir=args.output_dir,
        truth_or_smoke=args.truth,
    )
    print("✅ Gate passed")
