#!/usr/bin/env python3
"""
RAW Candles Schema Gate for GX1 (TRUTH/SMOKE).

Purpose:
- Validate that the RAW candles parquet passed via `--data` contains OHLC columns.
- This gate is ONLY about candle-source (raw) and MUST NOT be used for prebuilt features.

Contract (when truth_or_smoke=True):
- Reads schema from raw_data_path (no full load; schema only).
- Requires one of two valid OHLC families (case-insensitive):
  A) {open, high, low, close}
  B) {candles.open, candles.high, candles.low, candles.close}
- Always writes RAW_CANDLES_SCHEMA_AUDIT.md
- If not satisfied: write RAW_CANDLES_SCHEMA_FATAL.json and exit code 2.
"""

from __future__ import annotations

import json
import os
import sys
import tempfile
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional

try:
    import pyarrow.parquet as pq
except ImportError:  # pragma: no cover
    pq = None


def _now_utc_compact() -> str:
    return datetime.utcnow().strftime("%Y%m%d_%H%M%S")


def _safe_mkdir(path: Path) -> bool:
    try:
        path.mkdir(parents=True, exist_ok=True)
        return True
    except Exception:
        return False


def _fallback_dir() -> Path:
    root = Path(tempfile.gettempdir()) / "gx1_raw_candles_schema_gate"
    if not _safe_mkdir(root):
        root = Path("/tmp")
    run_dir = root / f"run_{_now_utc_compact()}_{os.getpid()}"
    _safe_mkdir(run_dir)
    return run_dir


def _choose_report_dir(output_dir: Path) -> Path:
    try:
        if output_dir is not None and _safe_mkdir(output_dir):
            return output_dir
    except Exception:
        pass
    return _fallback_dir()


def _write_text_atomic(path: Path, text: str) -> None:
    tmp_path = path.with_suffix(path.suffix + f".tmp.{os.getpid()}")
    with open(tmp_path, "w", encoding="utf-8") as f:
        f.write(text)
        f.flush()
        os.fsync(f.fileno())
    os.replace(tmp_path, path)


def _write_json_atomic(path: Path, obj: Dict[str, Any]) -> None:
    tmp_path = path.with_suffix(path.suffix + f".tmp.{os.getpid()}")
    with open(tmp_path, "w", encoding="utf-8") as f:
        json.dump(obj, f, indent=2, sort_keys=True)
        f.flush()
        os.fsync(f.fileno())
    os.replace(tmp_path, path)


def _read_schema_columns(path: Path) -> Optional[List[str]]:
    if pq is None:
        return None
    try:
        parquet_file = pq.ParquetFile(path)
        return parquet_file.schema.names
    except Exception:
        return None


def _check_ohlc_columns(columns: List[str]) -> Dict[str, Any]:
    cols_lower = [c.lower() for c in columns]
    colset = set(cols_lower)

    direct = {"open", "high", "low", "close"}
    candles = {"candles.open", "candles.high", "candles.low", "candles.close"}

    direct_found = sorted([c for c in columns if c.lower() in direct])
    candles_found = sorted([c for c in columns if c.lower() in candles])

    missing_direct = sorted(list(direct - colset))
    missing_candles = sorted(list(candles - colset))

    return {
        "has_ohlc_direct": direct.issubset(colset),
        "has_ohlc_candles": candles.issubset(colset),
        "missing_fields_direct": missing_direct,
        "missing_fields_candles": missing_candles,
        "ohlc_direct_found": direct_found,
        "ohlc_candles_found": candles_found,
    }


def _render_md(raw_data_path: Path, columns: List[str], file_size: int, ohlc_check: Dict[str, Any]) -> str:
    ok = bool(ohlc_check.get("has_ohlc_direct") or ohlc_check.get("has_ohlc_candles"))
    status = "PASS" if ok else "FAIL"
    family = "direct" if ohlc_check.get("has_ohlc_direct") else "candles.*" if ohlc_check.get("has_ohlc_candles") else "none"

    lines = [
        "# RAW_CANDLES_SCHEMA_AUDIT",
        "",
        f"- **Status:** {status}",
        f"- **Raw data (--data):** `{raw_data_path}`",
        f"- **File size:** {file_size:,} bytes",
        f"- **Detected family:** {family}",
        "",
        "## Required families (one must be complete)",
        "",
        "- `{open, high, low, close}`",
        "- `{candles.open, candles.high, candles.low, candles.close}`",
        "",
        "## Column sample (first 50, sorted)",
        "",
        "```",
        ", ".join(sorted(columns)[:50]),
        "```",
        "",
        "---",
        f"*Report generated by raw_candles_schema_gate.py at {datetime.utcnow().isoformat()}Z*",
    ]
    return "\n".join(lines)


def run_raw_candles_schema_gate_or_fatal(output_dir: Path, truth_or_smoke: bool, raw_data_path: Path) -> None:
    if not truth_or_smoke:
        return

    report_dir = _choose_report_dir(output_dir)
    fatal_path = report_dir / "RAW_CANDLES_SCHEMA_FATAL.json"
    md_path = report_dir / "RAW_CANDLES_SCHEMA_AUDIT.md"

    if not raw_data_path.exists():
        # C) Fix: Suggest correct path and show candidates
        from gx1.utils.output_dir import resolve_gx1_data_root
        try:
            gx1_data_root = resolve_gx1_data_root()
            suggested_path = gx1_data_root / "data" / "data" / "raw" / "xauusd_m5_2025_bid_ask.parquet"
        except Exception:
            suggested_path = Path("/home/andre2/GX1_DATA/data/data/raw/xauusd_m5_2025_bid_ask.parquet")
        
        # Find candidates
        candidates = []
        try:
            if suggested_path.parent.exists():
                candidates = list(suggested_path.parent.glob("xauusd_m5*.parquet"))[:10]
        except Exception:
            pass
        
        msg = (
            f"Raw data path does not exist: {raw_data_path}\n"
            f"Suggested path: {suggested_path}\n"
            f"Candidates found: {[str(c) for c in candidates] if candidates else 'none'}"
        )
        capsule = {
            "status": "FAIL",
            "message": msg,
            "raw_data_path": str(raw_data_path),
            "suggested_path": str(suggested_path),
            "candidates": [str(c) for c in candidates] if candidates else [],
            "sys.executable": sys.executable,
            "sys.version": sys.version,
            "cwd": str(Path.cwd()),
            "report_dir": str(report_dir),
        }
        _write_json_atomic(fatal_path, capsule)
        raise SystemExit(2)

    columns = _read_schema_columns(raw_data_path)
    if not columns:
        msg = f"Failed to read parquet schema for raw data: {raw_data_path}"
        capsule = {
            "status": "FAIL",
            "message": msg,
            "raw_data_path": str(raw_data_path),
            "sys.executable": sys.executable,
            "sys.version": sys.version,
            "cwd": str(Path.cwd()),
            "report_dir": str(report_dir),
        }
        _write_json_atomic(fatal_path, capsule)
        raise SystemExit(2)

    try:
        file_size = raw_data_path.stat().st_size
    except Exception:
        file_size = 0

    ohlc_check = _check_ohlc_columns(columns)

    # Always write audit
    _write_text_atomic(md_path, _render_md(raw_data_path, columns, file_size, ohlc_check))

    if ohlc_check["has_ohlc_direct"] or ohlc_check["has_ohlc_candles"]:
        return

    msg = (
        "Raw data missing required OHLC columns. "
        "This is the candle-source (--data), not prebuilt features. "
        "Required: either {open, high, low, close} OR {candles.open, candles.high, candles.low, candles.close}."
    )
    capsule = {
        "status": "FAIL",
        "message": msg,
        "raw_data_path": str(raw_data_path),
        "file_size": file_size,
        "n_columns": len(columns),
        "detected_columns_sample": sorted(columns)[:50],
        "missing_fields_direct": ohlc_check["missing_fields_direct"],
        "missing_fields_candles": ohlc_check["missing_fields_candles"],
        "sys.executable": sys.executable,
        "sys.version": sys.version,
        "cwd": str(Path.cwd()),
        "report_dir": str(report_dir),
        "report_path": str(md_path),
    }
    _write_json_atomic(fatal_path, capsule)
    raise SystemExit(2)

