#!/usr/bin/env bash
set -euo pipefail

# Vedtak-gated plumbing smoke for the audited Entry foundation seq146 dataset.
# This never promotes, pins, starts shadow, or touches live/practice order paths.

REPO=/home/andre2/src/GX1_ENGINE
DATA=/home/andre2/GX1_DATA
PY=$REPO/.venv/bin/python

SOURCE_DATASET=$DATA/runs/FASE2B_REGIME_V4_20260605/v10_6yr_rebuild_20260628_foundation_seq146/v10_dataset_foundation_seq146_neutral_20260629_directional_smc
SMOKE_DATASET=$DATA/runs/FASE2B_REGIME_V4_20260605/v10_6yr_rebuild_20260628_foundation_seq146/v10_dataset_foundation_seq146_smoke
SMOKE_STEM=v10_foundation_seq146_smoke__HOLD_03B
M5_PREBUILT=$DATA/runs/FASE2B_REGIME_V4_20260605/v10_6yr_rebuild_20260626_spreadfix/cv3/xauusd_m5_CANONICAL_V3_2020_2026.parquet
FEATURE_AUDIT=$DATA/reports/entry_feature_foundation_audit_20260628_v1/foundation_seq146/ENTRY_FEATURE_FOUNDATION_AUDIT_latest.json
TARGET_AUDIT=$DATA/reports/entry_target_foundation_audit_20260628_v1/foundation_seq146/ENTRY_TARGET_FOUNDATION_AUDIT_latest.json
SPECIALIST_AUDIT=$DATA/reports/entry_specialist_feature_group_audit_20260628_v1/ENTRY_SPECIALIST_FEATURE_GROUP_AUDIT_latest.json
SMOKE_TRAIN_MANIFEST_DIR=$DATA/reports/entry_foundation_smoke_train_manifests_20260628_v1
SMOKE_BUNDLE_AUDIT_OUT=$DATA/reports/entry_foundation_smoke_bundle_audit_20260628_v1

VEDTAK="${ENTRY_FOUNDATION_SMOKE_VEDTAK:-}"
RUN_FLAVOR=foundation_seq146
SPECIALIST_CONTRACT_MODE=foundation_seq146
EXPECTED_SIGNAL_DIM=146
SMOKE_DATASET_SCHEMA=entry_foundation_seq146_smoke_dataset_v1
DEVICE=auto
EPOCHS=1
EARLY_STOP_PATIENCE="${ENTRY_FOUNDATION_SMOKE_EARLY_STOP_PATIENCE:-1}"
BATCH_SIZE=64
TRAIN_ROWS=4095
VAL_ROWS=1536
TEST_ROWS=1536
MATERIALIZE_ONLY=0
MANIFEST_ONLY=0
DRY_RUN=0
REFRESH_SMOKE=0
AUDIT_AFTER=1
# Post-smoke audit runs on the (idle, post-train) GPU by default — validated
# byte-identical edge verdict vs CPU on the run6 PASS bundle, ~2-3 min faster
# (SMART+MAXED resource directive). Falls back to CPU when no CUDA. Override
# with --audit-device cpu.
AUDIT_DEVICE=auto
AUDIT_BATCH_SIZE=512
REQUIRE_EDGE_AUDIT=1
SMOKE_BAD_PATH_WEIGHT="${ENTRY_FOUNDATION_SMOKE_BAD_PATH_WEIGHT:-1.00}"
SMOKE_BAD_PATH_QUALITY_RANK_WEIGHT="${ENTRY_FOUNDATION_SMOKE_BAD_PATH_QUALITY_RANK_WEIGHT:-2.00}"
SMOKE_BAD_PATH_QUALITY_RANK_MARGIN="${ENTRY_FOUNDATION_SMOKE_BAD_PATH_QUALITY_RANK_MARGIN:-0.25}"
SMOKE_BAD_PATH_QUALITY_RANK_QUANTILE="${ENTRY_FOUNDATION_SMOKE_BAD_PATH_QUALITY_RANK_QUANTILE:-0.25}"
SMOKE_BAD_PATH_PROB_PENALTY="${ENTRY_FOUNDATION_SMOKE_BAD_PATH_PROB_PENALTY:-0.24}"
SMOKE_PATH_QUALITY_RANK_WEIGHT="${ENTRY_FOUNDATION_SMOKE_PATH_QUALITY_RANK_WEIGHT:-2.00}"
SMOKE_PATH_QUALITY_RANK_MARGIN="${ENTRY_FOUNDATION_SMOKE_PATH_QUALITY_RANK_MARGIN:-0.25}"
SMOKE_PATH_QUALITY_RANK_QUANTILE="${ENTRY_FOUNDATION_SMOKE_PATH_QUALITY_RANK_QUANTILE:-0.25}"
SMOKE_PRED_BALANCE_ALPHA="${ENTRY_FOUNDATION_SMOKE_PRED_BALANCE_ALPHA:-0.05}"
SMOKE_PRED_BALANCE_TARGET="${ENTRY_FOUNDATION_SMOKE_PRED_BALANCE_TARGET:-label}"
SMOKE_PRED_BALANCE_CLASS_WEIGHTS="${ENTRY_FOUNDATION_SMOKE_PRED_BALANCE_CLASS_WEIGHTS:-1.0,1.0,1.0}"
SMOKE_DIRECTION_CE_SCALE="${ENTRY_FOUNDATION_SMOKE_DIRECTION_CE_SCALE:-1.30}"
SMOKE_TAIL_DIRECTION_CE_WEIGHT="${ENTRY_FOUNDATION_SMOKE_TAIL_DIRECTION_CE_WEIGHT:-0.35}"
SMOKE_TAIL_DIRECTION_QUALITY_QUANTILE="${ENTRY_FOUNDATION_SMOKE_TAIL_DIRECTION_QUALITY_QUANTILE:-0.70}"
SMOKE_TAIL_DIRECTION_MIN_BATCH="${ENTRY_FOUNDATION_SMOKE_TAIL_DIRECTION_MIN_BATCH:-8}"
SMOKE_CKPT_MONITOR="${ENTRY_FOUNDATION_SMOKE_CKPT_MONITOR:-dir_acc}"
SMOKE_CKPT_CLASS_BALANCE_GUARD_WEIGHT="${ENTRY_FOUNDATION_SMOKE_CKPT_CLASS_BALANCE_GUARD_WEIGHT:-0.0}"
SMOKE_CKPT_CLASS_BALANCE_MIN_PRED_TO_LABEL="${ENTRY_FOUNDATION_SMOKE_CKPT_CLASS_BALANCE_MIN_PRED_TO_LABEL:-0.0}"
SMOKE_CKPT_CLASS_BALANCE_MIN_PRED_RATE="${ENTRY_FOUNDATION_SMOKE_CKPT_CLASS_BALANCE_MIN_PRED_RATE:-0.0}"
SMOKE_CKPT_DIRECTION_SLICE_GUARD="${ENTRY_FOUNDATION_SMOKE_CKPT_DIRECTION_SLICE_GUARD:-0}"
SMOKE_DIRECTION_MIN_PRED_RATE_LOSS_WEIGHT="${ENTRY_FOUNDATION_SMOKE_DIRECTION_MIN_PRED_RATE_LOSS_WEIGHT:-0.0}"
SMOKE_DIRECTION_MIN_PRED_RATE_FRACTION="${ENTRY_FOUNDATION_SMOKE_DIRECTION_MIN_PRED_RATE_FRACTION:-0.0}"
SMOKE_DIRECTION_MIN_PRED_RATE_FLOOR="${ENTRY_FOUNDATION_SMOKE_DIRECTION_MIN_PRED_RATE_FLOOR:-0.0}"
SMOKE_DIRECTION_MIN_PRED_RATE_SOFTMAX_TEMPERATURE="${ENTRY_FOUNDATION_SMOKE_DIRECTION_MIN_PRED_RATE_SOFTMAX_TEMPERATURE:-1.0}"
SMOKE_DIRECTION_GLOBAL_PRIOR_MATCH_WEIGHT="${ENTRY_FOUNDATION_SMOKE_DIRECTION_GLOBAL_PRIOR_MATCH_WEIGHT:-0.0}"
SMOKE_DIRECTION_GLOBAL_PRIOR_MATCH_TOLERANCE="${ENTRY_FOUNDATION_SMOKE_DIRECTION_GLOBAL_PRIOR_MATCH_TOLERANCE:-0.02}"
SMOKE_DIRECTION_GLOBAL_PRIOR_MATCH_MIN_LABEL_RATE="${ENTRY_FOUNDATION_SMOKE_DIRECTION_GLOBAL_PRIOR_MATCH_MIN_LABEL_RATE:-0.10}"
SMOKE_DIRECTION_SLICE_MIN_PRED_RATE_LOSS_WEIGHT="${ENTRY_FOUNDATION_SMOKE_DIRECTION_SLICE_MIN_PRED_RATE_LOSS_WEIGHT:-0.0}"
SMOKE_DIRECTION_SLICE_MIN_PRED_RATE_FRACTION="${ENTRY_FOUNDATION_SMOKE_DIRECTION_SLICE_MIN_PRED_RATE_FRACTION:-0.0}"
SMOKE_DIRECTION_SLICE_MIN_PRED_RATE_FLOOR="${ENTRY_FOUNDATION_SMOKE_DIRECTION_SLICE_MIN_PRED_RATE_FLOOR:-0.0}"
SMOKE_DIRECTION_SLICE_MIN_LABEL_RATE="${ENTRY_FOUNDATION_SMOKE_DIRECTION_SLICE_MIN_LABEL_RATE:-0.10}"
SMOKE_DIRECTION_SLICE_MIN_ROWS="${ENTRY_FOUNDATION_SMOKE_DIRECTION_SLICE_MIN_ROWS:-8}"
SMOKE_DIRECTION_SLICE_CTX_CAT_INDICES="${ENTRY_FOUNDATION_SMOKE_DIRECTION_SLICE_CTX_CAT_INDICES:-0,1,2,3,4}"
SMOKE_DIRECTION_SLICE_RECALL_LOSS_WEIGHT="${ENTRY_FOUNDATION_SMOKE_DIRECTION_SLICE_RECALL_LOSS_WEIGHT:-0.0}"
SMOKE_DIRECTION_SLICE_RECALL_PROB_FLOOR="${ENTRY_FOUNDATION_SMOKE_DIRECTION_SLICE_RECALL_PROB_FLOOR:-0.30}"
SMOKE_DIRECTION_SLICE_RECALL_MIN_LABEL_RATE="${ENTRY_FOUNDATION_SMOKE_DIRECTION_SLICE_RECALL_MIN_LABEL_RATE:-0.10}"
SMOKE_DIRECTION_SLICE_RECALL_MIN_ROWS="${ENTRY_FOUNDATION_SMOKE_DIRECTION_SLICE_RECALL_MIN_ROWS:-8}"
SMOKE_DIRECTION_SLICE_BALANCED_CE_WEIGHT="${ENTRY_FOUNDATION_SMOKE_DIRECTION_SLICE_BALANCED_CE_WEIGHT:-0.0}"
SMOKE_DIRECTION_SLICE_BALANCED_CE_MIN_LABEL_RATE="${ENTRY_FOUNDATION_SMOKE_DIRECTION_SLICE_BALANCED_CE_MIN_LABEL_RATE:-0.10}"
SMOKE_DIRECTION_SLICE_BALANCED_CE_MIN_ROWS="${ENTRY_FOUNDATION_SMOKE_DIRECTION_SLICE_BALANCED_CE_MIN_ROWS:-8}"
SMOKE_DIRECTION_SLICE_TRUE_MARGIN_WEIGHT="${ENTRY_FOUNDATION_SMOKE_DIRECTION_SLICE_TRUE_MARGIN_WEIGHT:-0.0}"
SMOKE_DIRECTION_SLICE_TRUE_MARGIN="${ENTRY_FOUNDATION_SMOKE_DIRECTION_SLICE_TRUE_MARGIN:-0.10}"
SMOKE_DIRECTION_SLICE_TRUE_MARGIN_MIN_LABEL_RATE="${ENTRY_FOUNDATION_SMOKE_DIRECTION_SLICE_TRUE_MARGIN_MIN_LABEL_RATE:-0.10}"
SMOKE_DIRECTION_SLICE_TRUE_MARGIN_MIN_ROWS="${ENTRY_FOUNDATION_SMOKE_DIRECTION_SLICE_TRUE_MARGIN_MIN_ROWS:-8}"
SMOKE_DIRECTION_SLICE_ACCURACY_EDGE_WEIGHT="${ENTRY_FOUNDATION_SMOKE_DIRECTION_SLICE_ACCURACY_EDGE_WEIGHT:-0.0}"
SMOKE_DIRECTION_SLICE_ACCURACY_EDGE_MARGIN="${ENTRY_FOUNDATION_SMOKE_DIRECTION_SLICE_ACCURACY_EDGE_MARGIN:-0.02}"
SMOKE_DIRECTION_SLICE_ACCURACY_EDGE_MIN_LABEL_RATE="${ENTRY_FOUNDATION_SMOKE_DIRECTION_SLICE_ACCURACY_EDGE_MIN_LABEL_RATE:-0.10}"
SMOKE_DIRECTION_SLICE_ACCURACY_EDGE_MIN_ROWS="${ENTRY_FOUNDATION_SMOKE_DIRECTION_SLICE_ACCURACY_EDGE_MIN_ROWS:-8}"
SMOKE_DIRECTION_SLICE_PRIOR_MATCH_WEIGHT="${ENTRY_FOUNDATION_SMOKE_DIRECTION_SLICE_PRIOR_MATCH_WEIGHT:-0.0}"
SMOKE_DIRECTION_SLICE_PRIOR_MATCH_TOLERANCE="${ENTRY_FOUNDATION_SMOKE_DIRECTION_SLICE_PRIOR_MATCH_TOLERANCE:-0.02}"
SMOKE_DIRECTION_SLICE_PRIOR_MATCH_MIN_LABEL_RATE="${ENTRY_FOUNDATION_SMOKE_DIRECTION_SLICE_PRIOR_MATCH_MIN_LABEL_RATE:-0.10}"
SMOKE_DIRECTION_SLICE_PRIOR_MATCH_MIN_ROWS="${ENTRY_FOUNDATION_SMOKE_DIRECTION_SLICE_PRIOR_MATCH_MIN_ROWS:-8}"
SMOKE_DIRECTION_SLICE_LOSS_AGGREGATION="${ENTRY_FOUNDATION_SMOKE_DIRECTION_SLICE_LOSS_AGGREGATION:-mean}"
SMOKE_DIRECTION_SLICE_BALANCED_SAMPLER="${ENTRY_FOUNDATION_SMOKE_DIRECTION_SLICE_BALANCED_SAMPLER:-0}"
SMOKE_DIRECTION_SLICE_BALANCED_SAMPLER_MIN_ROWS="${ENTRY_FOUNDATION_SMOKE_DIRECTION_SLICE_BALANCED_SAMPLER_MIN_ROWS:-8}"
SMOKE_DIRECTION_SLICE_HARD_RED_STOP_PATIENCE="${ENTRY_FOUNDATION_SMOKE_DIRECTION_SLICE_HARD_RED_STOP_PATIENCE:-0}"
SMOKE_DIRECTION_SLICE_HARD_RED_STOP_MIN_EPOCHS="${ENTRY_FOUNDATION_SMOKE_DIRECTION_SLICE_HARD_RED_STOP_MIN_EPOCHS:-6}"
SMOKE_DIRECTION_VS_FLAT_MARGIN_WEIGHT="${ENTRY_FOUNDATION_SMOKE_DIRECTION_VS_FLAT_MARGIN_WEIGHT:-0.0}"
SMOKE_DIRECTION_VS_FLAT_MARGIN="${ENTRY_FOUNDATION_SMOKE_DIRECTION_VS_FLAT_MARGIN:-0.0}"
SMOKE_HIER_LEGACY_CE_MULT="${ENTRY_FOUNDATION_SMOKE_HIER_LEGACY_CE_MULT:-0.35}"
SMOKE_HIER_TRADE_WEIGHT="${ENTRY_FOUNDATION_SMOKE_HIER_TRADE_WEIGHT:-0.85}"
SMOKE_HIER_SIDE_WEIGHT="${ENTRY_FOUNDATION_SMOKE_HIER_SIDE_WEIGHT:-0.85}"
SMOKE_HIER_UTILITY_WEIGHT="${ENTRY_FOUNDATION_SMOKE_HIER_UTILITY_WEIGHT:-0.20}"
SMOKE_HIER_BAD_PATH_WEIGHT="${ENTRY_FOUNDATION_SMOKE_HIER_BAD_PATH_WEIGHT:-0.35}"
SMOKE_HIER_MAE_WEIGHT="${ENTRY_FOUNDATION_SMOKE_HIER_MAE_WEIGHT:-0.15}"
SMOKE_HIER_SIDE_VALIDITY_WEIGHT="${ENTRY_FOUNDATION_SMOKE_HIER_SIDE_VALIDITY_WEIGHT:-0.0}"
SMOKE_HIER_SIDE_VALIDITY_MIN_UTILITY_BPS="${ENTRY_FOUNDATION_SMOKE_HIER_SIDE_VALIDITY_MIN_UTILITY_BPS:-10.0}"
SMOKE_HIER_SIDE_VALIDITY_POS_WEIGHT_CAP="${ENTRY_FOUNDATION_SMOKE_HIER_SIDE_VALIDITY_POS_WEIGHT_CAP:-20.0}"
SMOKE_HIER_POCKET_ABSTAIN_WEIGHT="${ENTRY_FOUNDATION_SMOKE_HIER_POCKET_ABSTAIN_WEIGHT:-0.0}"
SMOKE_HIER_POCKET_SIDE_MARGIN_WEIGHT="${ENTRY_FOUNDATION_SMOKE_HIER_POCKET_SIDE_MARGIN_WEIGHT:-0.0}"
SMOKE_HIER_POCKET_UTILITY_MARGIN_BPS="${ENTRY_FOUNDATION_SMOKE_HIER_POCKET_UTILITY_MARGIN_BPS:-10.0}"
SMOKE_TRENDLINE_RAIL_AUX_WEIGHT="${ENTRY_FOUNDATION_SMOKE_TRENDLINE_RAIL_AUX_WEIGHT:-0.0}"
SMOKE_TRENDLINE_RAIL_WRONG_SIDE_WEIGHT="${ENTRY_FOUNDATION_SMOKE_TRENDLINE_RAIL_WRONG_SIDE_WEIGHT:-0.0}"
SMOKE_TRENDLINE_RAIL_RISING_WRONG_SHORT_WEIGHT="${ENTRY_FOUNDATION_SMOKE_TRENDLINE_RAIL_RISING_WRONG_SHORT_WEIGHT:-$SMOKE_TRENDLINE_RAIL_WRONG_SIDE_WEIGHT}"
SMOKE_TRENDLINE_RAIL_FALLING_WRONG_LONG_WEIGHT="${ENTRY_FOUNDATION_SMOKE_TRENDLINE_RAIL_FALLING_WRONG_LONG_WEIGHT:-$SMOKE_TRENDLINE_RAIL_WRONG_SIDE_WEIGHT}"
SMOKE_TRENDLINE_RAIL_FINAL_MARGIN_WEIGHT="${ENTRY_FOUNDATION_SMOKE_TRENDLINE_RAIL_FINAL_MARGIN_WEIGHT:-0.0}"
SMOKE_TRENDLINE_RAIL_HIER_MARGIN_WEIGHT="${ENTRY_FOUNDATION_SMOKE_TRENDLINE_RAIL_HIER_MARGIN_WEIGHT:-0.0}"
SMOKE_TRENDLINE_RAIL_FLAT_TRADE_WEIGHT="${ENTRY_FOUNDATION_SMOKE_TRENDLINE_RAIL_FLAT_TRADE_WEIGHT:-0.0}"
SMOKE_TRENDLINE_RAIL_UTILITY_MARGIN_WEIGHT="${ENTRY_FOUNDATION_SMOKE_TRENDLINE_RAIL_UTILITY_MARGIN_WEIGHT:-0.0}"
SMOKE_TRENDLINE_RAIL_MARGIN="${ENTRY_FOUNDATION_SMOKE_TRENDLINE_RAIL_MARGIN:-0.50}"
SMOKE_TRENDLINE_RAIL_UTILITY_MARGIN_BPS="${ENTRY_FOUNDATION_SMOKE_TRENDLINE_RAIL_UTILITY_MARGIN_BPS:-5.0}"
SMOKE_ENABLE_XAU_DIRECTION_REPAIR_HEADS=0
SMOKE_RESIDUAL_SCALE="${ENTRY_FOUNDATION_SMOKE_RESIDUAL_SCALE:-0.35}"
SMOKE_ANCHOR_EPS="${ENTRY_FOUNDATION_SMOKE_ANCHOR_EPS:-1e-6}"
SMOKE_ANCHOR_GATE_INIT="${ENTRY_FOUNDATION_SMOKE_ANCHOR_GATE_INIT:-1.0}"
SMOKE_SYMMETRIC_NEGATIVES="${ENTRY_FOUNDATION_SMOKE_SYMMETRIC_NEGATIVES:-1}"
SMOKE_FLAT_CLASS_WEIGHT_FLOOR="${ENTRY_FOUNDATION_SMOKE_FLAT_CLASS_WEIGHT_FLOOR:-1.0}"
SMOKE_SPECIALIST_GATE_ENTROPY_WEIGHT="${ENTRY_FOUNDATION_SMOKE_SPECIALIST_GATE_ENTROPY_WEIGHT:-0.05}"
SMOKE_SPECIALIST_GATE_BALANCE_WEIGHT="${ENTRY_FOUNDATION_SMOKE_SPECIALIST_GATE_BALANCE_WEIGHT:-0.25}"
SMOKE_SPECIALIST_GATE_MIN_MEAN="${ENTRY_FOUNDATION_SMOKE_SPECIALIST_GATE_MIN_MEAN:-0.02}"
SMOKE_LR="${ENTRY_FOUNDATION_SMOKE_LR:-3e-4}"
SMOKE_WEIGHT_DECAY="${ENTRY_FOUNDATION_SMOKE_WEIGHT_DECAY:-1e-5}"
SMOKE_GRAD_CLIP_NORM="${ENTRY_FOUNDATION_SMOKE_GRAD_CLIP_NORM:-1.0}"
SMOKE_RUN_MEM="${ENTRY_FOUNDATION_SMOKE_RUN_MEM:-22G}"
SMOKE_RUN_SWAP="${ENTRY_FOUNDATION_SMOKE_RUN_SWAP:-2G}"
SMOKE_CAPPED_RUNNER=scripts/gx1_capped_run.sh

usage() {
  cat <<'EOF'
Usage:
  scripts/run_entry_foundation_seq146_smoke_train.sh --vedtak <id> [options]

Options:
  --vedtak <id>        Required explicit user decision id for this smoke train.
  --device <auto|cpu|cuda>
  --epochs <n>         Default: 1
  --early-stop-patience <n>  Default: 1 (epochs without val improvement before stop)
  --batch-size <n>     Default: 64
  --train-rows <n>     Default: 4095
  --val-rows <n>       Default: 1536
  --test-rows <n>      Default: 1536
  --materialize-only   Build the small smoke dataset, then stop.
  --manifest-only      Run real preflight and write the pre-train manifest, then stop.
  --refresh-smoke      Rebuild the small smoke dataset before training/dry-run.
  --challenger-seq215  Use the audited seq215 challenger dataset and 8-specialist
                       challenger_seq215 contract.
  --smart-seq520       Use the audited smart seq520 smoke dataset and
                       smart_seq520_candidate contract. Still requires smart
                       smoke-readiness, clean git and explicit SMART vedtak.
  --dry-run            Print the train command, then stop.
  --skip-smoke-audit   Do not run the post-train smoke bundle audit.
  --audit-device <auto|cpu|cuda>
                       Default: cpu
  --audit-batch-size <n>
                       Default: 128
  --require-edge-audit Require edge diagnostics in the post-train audit. Default.
  --no-require-edge-audit
                       Plumbing-only audit; candidate-readiness will not pass.

This is a smoke/plumbing path only. It writes a non-promoted bundle under the
foundation seq146 run directory, audits the produced bundle including its active
head contract, and does not pin, promote, shadow, or trade.

Real training preflight reruns:
  scripts/entry_next_edge_control.sh verify --quiet
  scripts/entry_next_edge_control.sh foundation-guardrails --quiet
  scripts/entry_next_edge_control.sh train-readiness --quiet

Dry-run prints those preflight commands but does not recurse through them.
Real training writes a pre-train run manifest before gx1_capped_run starts.
Real training also requires a clean git worktree; use --manifest-only for proof
when the repo is intentionally dirty.
Set ENTRY_FOUNDATION_SMOKE_RUN_MEM/SWAP to lower the hard cgroup cap for
RAM-constrained overnight runs.

Smoke edge recipe env:
  ENTRY_FOUNDATION_SMOKE_BAD_PATH_WEIGHT                 Default: 1.00
  ENTRY_FOUNDATION_SMOKE_BAD_PATH_QUALITY_RANK_WEIGHT    Default: 2.00
  ENTRY_FOUNDATION_SMOKE_BAD_PATH_QUALITY_RANK_MARGIN    Default: 0.25
  ENTRY_FOUNDATION_SMOKE_BAD_PATH_QUALITY_RANK_QUANTILE  Default: 0.25
  ENTRY_FOUNDATION_SMOKE_PATH_QUALITY_RANK_WEIGHT        Default: 2.00
  ENTRY_FOUNDATION_SMOKE_PATH_QUALITY_RANK_MARGIN        Default: 0.25
  ENTRY_FOUNDATION_SMOKE_PATH_QUALITY_RANK_QUANTILE      Default: 0.25
  ENTRY_FOUNDATION_SMOKE_PRED_BALANCE_ALPHA              Default: 0.05
  ENTRY_FOUNDATION_SMOKE_PRED_BALANCE_TARGET             Default: label
  ENTRY_FOUNDATION_SMOKE_PRED_BALANCE_CLASS_WEIGHTS      Default: 1.0,1.0,1.0
  ENTRY_FOUNDATION_SMOKE_DIRECTION_CE_SCALE              Default: 1.30
  ENTRY_FOUNDATION_SMOKE_TAIL_DIRECTION_CE_WEIGHT        Default: 0.35
  ENTRY_FOUNDATION_SMOKE_TAIL_DIRECTION_QUALITY_QUANTILE Default: 0.70
  ENTRY_FOUNDATION_SMOKE_TAIL_DIRECTION_MIN_BATCH        Default: 8
  ENTRY_FOUNDATION_SMOKE_CKPT_CLASS_BALANCE_GUARD_WEIGHT Default: 0.0
  ENTRY_FOUNDATION_SMOKE_CKPT_CLASS_BALANCE_MIN_PRED_TO_LABEL Default: 0.0
  ENTRY_FOUNDATION_SMOKE_CKPT_CLASS_BALANCE_MIN_PRED_RATE Default: 0.0
  ENTRY_FOUNDATION_SMOKE_CKPT_DIRECTION_SLICE_GUARD Default: 0
  ENTRY_FOUNDATION_SMOKE_DIRECTION_MIN_PRED_RATE_LOSS_WEIGHT Default: 0.0
  ENTRY_FOUNDATION_SMOKE_DIRECTION_MIN_PRED_RATE_FRACTION Default: 0.0
  ENTRY_FOUNDATION_SMOKE_DIRECTION_MIN_PRED_RATE_FLOOR Default: 0.0
  ENTRY_FOUNDATION_SMOKE_DIRECTION_MIN_PRED_RATE_SOFTMAX_TEMPERATURE Default: 1.0
  ENTRY_FOUNDATION_SMOKE_DIRECTION_GLOBAL_PRIOR_MATCH_WEIGHT Default: 0.0
  ENTRY_FOUNDATION_SMOKE_DIRECTION_GLOBAL_PRIOR_MATCH_TOLERANCE Default: 0.02
  ENTRY_FOUNDATION_SMOKE_DIRECTION_GLOBAL_PRIOR_MATCH_MIN_LABEL_RATE Default: 0.10
  ENTRY_FOUNDATION_SMOKE_DIRECTION_SLICE_BALANCED_CE_WEIGHT Default: 0.0
  ENTRY_FOUNDATION_SMOKE_DIRECTION_SLICE_BALANCED_CE_MIN_LABEL_RATE Default: 0.10
  ENTRY_FOUNDATION_SMOKE_DIRECTION_SLICE_BALANCED_CE_MIN_ROWS Default: 8
  ENTRY_FOUNDATION_SMOKE_DIRECTION_SLICE_TRUE_MARGIN_WEIGHT Default: 0.0
  ENTRY_FOUNDATION_SMOKE_DIRECTION_SLICE_TRUE_MARGIN Default: 0.10
  ENTRY_FOUNDATION_SMOKE_DIRECTION_SLICE_TRUE_MARGIN_MIN_LABEL_RATE Default: 0.10
  ENTRY_FOUNDATION_SMOKE_DIRECTION_SLICE_TRUE_MARGIN_MIN_ROWS Default: 8
  ENTRY_FOUNDATION_SMOKE_DIRECTION_SLICE_ACCURACY_EDGE_WEIGHT Default: 0.0
  ENTRY_FOUNDATION_SMOKE_DIRECTION_SLICE_ACCURACY_EDGE_MARGIN Default: 0.02
  ENTRY_FOUNDATION_SMOKE_DIRECTION_SLICE_ACCURACY_EDGE_MIN_LABEL_RATE Default: 0.10
  ENTRY_FOUNDATION_SMOKE_DIRECTION_SLICE_ACCURACY_EDGE_MIN_ROWS Default: 8
  ENTRY_FOUNDATION_SMOKE_DIRECTION_SLICE_PRIOR_MATCH_WEIGHT Default: 0.0
  ENTRY_FOUNDATION_SMOKE_DIRECTION_SLICE_PRIOR_MATCH_TOLERANCE Default: 0.02
  ENTRY_FOUNDATION_SMOKE_DIRECTION_SLICE_PRIOR_MATCH_MIN_LABEL_RATE Default: 0.10
  ENTRY_FOUNDATION_SMOKE_DIRECTION_SLICE_PRIOR_MATCH_MIN_ROWS Default: 8
  ENTRY_FOUNDATION_SMOKE_DIRECTION_SLICE_HARD_RED_STOP_PATIENCE Default: 0
  ENTRY_FOUNDATION_SMOKE_DIRECTION_SLICE_HARD_RED_STOP_MIN_EPOCHS Default: 6
  ENTRY_FOUNDATION_SMOKE_DIRECTION_VS_FLAT_MARGIN_WEIGHT Default: 0.0
  ENTRY_FOUNDATION_SMOKE_DIRECTION_VS_FLAT_MARGIN Default: 0.0
  ENTRY_FOUNDATION_SMOKE_HIER_LEGACY_CE_MULT             Default: 0.35
  ENTRY_FOUNDATION_SMOKE_HIER_SIDE_VALIDITY_WEIGHT        Default: 0.0
  ENTRY_FOUNDATION_SMOKE_HIER_SIDE_VALIDITY_MIN_UTILITY_BPS Default: 10.0
  ENTRY_FOUNDATION_SMOKE_HIER_SIDE_VALIDITY_POS_WEIGHT_CAP Default: 20.0
  ENTRY_FOUNDATION_SMOKE_HIER_POCKET_ABSTAIN_WEIGHT      Default: 0.0
  ENTRY_FOUNDATION_SMOKE_HIER_POCKET_SIDE_MARGIN_WEIGHT  Default: 0.0
  ENTRY_FOUNDATION_SMOKE_HIER_POCKET_UTILITY_MARGIN_BPS  Default: 10.0
  ENTRY_FOUNDATION_SMOKE_RESIDUAL_SCALE                  Default: 0.35
  ENTRY_FOUNDATION_SMOKE_ANCHOR_EPS                      Default: 1e-6
  ENTRY_FOUNDATION_SMOKE_ANCHOR_GATE_INIT                Default: 1.0
  ENTRY_FOUNDATION_SMOKE_EARLY_STOP_PATIENCE             Default: 1
  ENTRY_FOUNDATION_SMOKE_FLAT_CLASS_WEIGHT_FLOOR         Default: 1.0 (CE-side FLAT sample weight)
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --vedtak) VEDTAK="$2"; shift 2 ;;
    --device) DEVICE="$2"; shift 2 ;;
    --epochs) EPOCHS="$2"; shift 2 ;;
    --early-stop-patience) EARLY_STOP_PATIENCE="$2"; shift 2 ;;
    --batch-size) BATCH_SIZE="$2"; shift 2 ;;
    --train-rows) TRAIN_ROWS="$2"; REFRESH_SMOKE=1; shift 2 ;;
    --val-rows) VAL_ROWS="$2"; REFRESH_SMOKE=1; shift 2 ;;
    --test-rows) TEST_ROWS="$2"; REFRESH_SMOKE=1; shift 2 ;;
    --challenger-seq215)
      RUN_FLAVOR=challenger_seq215
      SOURCE_DATASET=$DATA/runs/FASE2B_REGIME_V4_20260605/v10_6yr_rebuild_20260628_foundation_seq146/v10_dataset_challenger_seq215_neutral_20260630
      SMOKE_DATASET=$DATA/runs/FASE2B_REGIME_V4_20260605/v10_6yr_rebuild_20260628_foundation_seq146/v10_dataset_challenger_seq215_smoke_20260630
      SMOKE_STEM=v10_challenger_seq215_smoke__HOLD_03B
      FEATURE_AUDIT=$DATA/reports/entry_feature_foundation_audit_20260628_v1/challenger_seq215_20260630/ENTRY_FEATURE_FOUNDATION_AUDIT_latest.json
      TARGET_AUDIT=$DATA/reports/entry_target_foundation_audit_20260628_v1/challenger_seq215_20260630/ENTRY_TARGET_FOUNDATION_AUDIT_latest.json
      SPECIALIST_AUDIT=$DATA/reports/entry_specialist_feature_group_audit_20260628_v1/challenger_seq215_20260630_contract8/ENTRY_SPECIALIST_FEATURE_GROUP_AUDIT_latest.json
      SMOKE_BUNDLE_AUDIT_OUT=$DATA/reports/entry_foundation_smoke_bundle_audit_20260628_v1/challenger_seq215_20260630
      SPECIALIST_CONTRACT_MODE=challenger_seq215
      EXPECTED_SIGNAL_DIM=215
      SMOKE_DATASET_SCHEMA=entry_foundation_seq215_smoke_dataset_v1
      REFRESH_SMOKE=1
      shift
      ;;
    --smart-seq520)
      RUN_FLAVOR=smart_seq520
      SOURCE_DATASET=$DATA/runs/FASE2B_REGIME_V4_20260605/v10_6yr_rebuild_20260626_spreadfix/v10_dataset_6yr_smartctx_xau_direction_repair
      SMOKE_DATASET=$DATA/runs/FASE2B_REGIME_V4_20260605/v10_6yr_rebuild_20260626_spreadfix/v10_dataset_6yr_smartctx_xau_direction_repair_smoke
      SMOKE_STEM=v10_smart_seq520_smoke__HOLD_03B
      FEATURE_AUDIT=$DATA/reports/entry_feature_foundation_audit_20260628_v1/smart_seq520_candidate_20260630/ENTRY_FEATURE_FOUNDATION_AUDIT_latest.json
      TARGET_AUDIT=$DATA/reports/entry_target_foundation_audit_20260628_v1/smart_seq520_candidate_20260630/ENTRY_TARGET_FOUNDATION_AUDIT_latest.json
      SPECIALIST_AUDIT=$DATA/reports/entry_specialist_feature_group_audit_20260628_v1/smart_seq520_candidate_20260630/ENTRY_SPECIALIST_FEATURE_GROUP_AUDIT_latest.json
      SMOKE_BUNDLE_AUDIT_OUT=$DATA/reports/entry_foundation_smoke_bundle_audit_20260628_v1/smart_seq520_candidate
      SPECIALIST_CONTRACT_MODE=smart_seq520_candidate
      EXPECTED_SIGNAL_DIM=520
      SMOKE_DATASET_SCHEMA=entry_smart_seq520_smoke_dataset_v1
      SMOKE_ENABLE_XAU_DIRECTION_REPAIR_HEADS=1
      # Pre-set ENTRY_FOUNDATION_SMOKE_* env deliberately overrides the smart
      # auto-recipe below — must be LOUD, never silent (weld-audit 2026-07-02).
      if [[ -z "${ENTRY_FOUNDATION_SMOKE_PRED_BALANCE_ALPHA+x}" ]]; then
        SMOKE_PRED_BALANCE_ALPHA=0.50
      else
        echo "WARNING: smart auto-recipe PRED_BALANCE_ALPHA=0.50 overridden by env: ${SMOKE_PRED_BALANCE_ALPHA}" >&2
      fi
      if [[ -z "${ENTRY_FOUNDATION_SMOKE_DIRECTION_CE_SCALE+x}" ]]; then
        SMOKE_DIRECTION_CE_SCALE=4.00
      else
        echo "WARNING: smart auto-recipe DIRECTION_CE_SCALE=4.00 overridden by env: ${SMOKE_DIRECTION_CE_SCALE}" >&2
      fi
      if [[ -z "${ENTRY_FOUNDATION_SMOKE_PRED_BALANCE_CLASS_WEIGHTS+x}" ]]; then
        SMOKE_PRED_BALANCE_CLASS_WEIGHTS=1.0,1.0,4.0
      else
        echo "WARNING: smart auto-recipe PRED_BALANCE_CLASS_WEIGHTS=1.0,1.0,4.0 overridden by env: ${SMOKE_PRED_BALANCE_CLASS_WEIGHTS}" >&2
      fi
      if [[ -z "${ENTRY_FOUNDATION_SMOKE_CKPT_CLASS_BALANCE_GUARD_WEIGHT+x}" ]]; then
        SMOKE_CKPT_CLASS_BALANCE_GUARD_WEIGHT=0.50
      else
        echo "WARNING: smart auto-recipe CKPT_CLASS_BALANCE_GUARD_WEIGHT=0.50 overridden by env: ${SMOKE_CKPT_CLASS_BALANCE_GUARD_WEIGHT}" >&2
      fi
      if [[ -z "${ENTRY_FOUNDATION_SMOKE_CKPT_CLASS_BALANCE_MIN_PRED_TO_LABEL+x}" ]]; then
        SMOKE_CKPT_CLASS_BALANCE_MIN_PRED_TO_LABEL=0.35
      else
        echo "WARNING: smart auto-recipe CKPT_CLASS_BALANCE_MIN_PRED_TO_LABEL=0.35 overridden by env: ${SMOKE_CKPT_CLASS_BALANCE_MIN_PRED_TO_LABEL}" >&2
      fi
      if [[ -z "${ENTRY_FOUNDATION_SMOKE_CKPT_CLASS_BALANCE_MIN_PRED_RATE+x}" ]]; then
        SMOKE_CKPT_CLASS_BALANCE_MIN_PRED_RATE=0.05
      else
        echo "WARNING: smart auto-recipe CKPT_CLASS_BALANCE_MIN_PRED_RATE=0.05 overridden by env: ${SMOKE_CKPT_CLASS_BALANCE_MIN_PRED_RATE}" >&2
      fi
      if [[ -z "${ENTRY_FOUNDATION_SMOKE_CKPT_DIRECTION_SLICE_GUARD+x}" ]]; then
        SMOKE_CKPT_DIRECTION_SLICE_GUARD=1
      else
        echo "WARNING: smart auto-recipe CKPT_DIRECTION_SLICE_GUARD=1 overridden by env: ${SMOKE_CKPT_DIRECTION_SLICE_GUARD}" >&2
      fi
      if [[ -z "${ENTRY_FOUNDATION_SMOKE_DIRECTION_MIN_PRED_RATE_LOSS_WEIGHT+x}" ]]; then
        SMOKE_DIRECTION_MIN_PRED_RATE_LOSS_WEIGHT=12.00
      else
        echo "WARNING: smart auto-recipe DIRECTION_MIN_PRED_RATE_LOSS_WEIGHT=12.00 overridden by env: ${SMOKE_DIRECTION_MIN_PRED_RATE_LOSS_WEIGHT}" >&2
      fi
      if [[ -z "${ENTRY_FOUNDATION_SMOKE_DIRECTION_MIN_PRED_RATE_FRACTION+x}" ]]; then
        SMOKE_DIRECTION_MIN_PRED_RATE_FRACTION=0.50
      else
        echo "WARNING: smart auto-recipe DIRECTION_MIN_PRED_RATE_FRACTION=0.50 overridden by env: ${SMOKE_DIRECTION_MIN_PRED_RATE_FRACTION}" >&2
      fi
      if [[ -z "${ENTRY_FOUNDATION_SMOKE_DIRECTION_MIN_PRED_RATE_FLOOR+x}" ]]; then
        SMOKE_DIRECTION_MIN_PRED_RATE_FLOOR=0.05
      else
        echo "WARNING: smart auto-recipe DIRECTION_MIN_PRED_RATE_FLOOR=0.05 overridden by env: ${SMOKE_DIRECTION_MIN_PRED_RATE_FLOOR}" >&2
      fi
      if [[ -z "${ENTRY_FOUNDATION_SMOKE_DIRECTION_MIN_PRED_RATE_SOFTMAX_TEMPERATURE+x}" ]]; then
        SMOKE_DIRECTION_MIN_PRED_RATE_SOFTMAX_TEMPERATURE=0.05
      else
        echo "WARNING: smart auto-recipe DIRECTION_MIN_PRED_RATE_SOFTMAX_TEMPERATURE=0.05 overridden by env: ${SMOKE_DIRECTION_MIN_PRED_RATE_SOFTMAX_TEMPERATURE}" >&2
      fi
      if [[ -z "${ENTRY_FOUNDATION_SMOKE_DIRECTION_GLOBAL_PRIOR_MATCH_WEIGHT+x}" ]]; then
        SMOKE_DIRECTION_GLOBAL_PRIOR_MATCH_WEIGHT=8.00
      else
        echo "WARNING: smart auto-recipe DIRECTION_GLOBAL_PRIOR_MATCH_WEIGHT=8.00 overridden by env: ${SMOKE_DIRECTION_GLOBAL_PRIOR_MATCH_WEIGHT}" >&2
      fi
      if [[ -z "${ENTRY_FOUNDATION_SMOKE_DIRECTION_GLOBAL_PRIOR_MATCH_TOLERANCE+x}" ]]; then
        SMOKE_DIRECTION_GLOBAL_PRIOR_MATCH_TOLERANCE=0.02
      else
        echo "WARNING: smart auto-recipe DIRECTION_GLOBAL_PRIOR_MATCH_TOLERANCE=0.02 overridden by env: ${SMOKE_DIRECTION_GLOBAL_PRIOR_MATCH_TOLERANCE}" >&2
      fi
      if [[ -z "${ENTRY_FOUNDATION_SMOKE_DIRECTION_GLOBAL_PRIOR_MATCH_MIN_LABEL_RATE+x}" ]]; then
        SMOKE_DIRECTION_GLOBAL_PRIOR_MATCH_MIN_LABEL_RATE=0.10
      else
        echo "WARNING: smart auto-recipe DIRECTION_GLOBAL_PRIOR_MATCH_MIN_LABEL_RATE=0.10 overridden by env: ${SMOKE_DIRECTION_GLOBAL_PRIOR_MATCH_MIN_LABEL_RATE}" >&2
      fi
      if [[ -z "${ENTRY_FOUNDATION_SMOKE_DIRECTION_SLICE_MIN_PRED_RATE_LOSS_WEIGHT+x}" ]]; then
        SMOKE_DIRECTION_SLICE_MIN_PRED_RATE_LOSS_WEIGHT=8.00
      else
        echo "WARNING: smart auto-recipe DIRECTION_SLICE_MIN_PRED_RATE_LOSS_WEIGHT=8.00 overridden by env: ${SMOKE_DIRECTION_SLICE_MIN_PRED_RATE_LOSS_WEIGHT}" >&2
      fi
      if [[ -z "${ENTRY_FOUNDATION_SMOKE_DIRECTION_SLICE_MIN_PRED_RATE_FRACTION+x}" ]]; then
        SMOKE_DIRECTION_SLICE_MIN_PRED_RATE_FRACTION=0.50
      fi
      if [[ -z "${ENTRY_FOUNDATION_SMOKE_DIRECTION_SLICE_MIN_PRED_RATE_FLOOR+x}" ]]; then
        SMOKE_DIRECTION_SLICE_MIN_PRED_RATE_FLOOR=0.05
      fi
      if [[ -z "${ENTRY_FOUNDATION_SMOKE_DIRECTION_SLICE_RECALL_LOSS_WEIGHT+x}" ]]; then
        SMOKE_DIRECTION_SLICE_RECALL_LOSS_WEIGHT=4.00
      else
        echo "WARNING: smart auto-recipe DIRECTION_SLICE_RECALL_LOSS_WEIGHT=4.00 overridden by env: ${SMOKE_DIRECTION_SLICE_RECALL_LOSS_WEIGHT}" >&2
      fi
      if [[ -z "${ENTRY_FOUNDATION_SMOKE_DIRECTION_SLICE_BALANCED_CE_WEIGHT+x}" ]]; then
        SMOKE_DIRECTION_SLICE_BALANCED_CE_WEIGHT=2.00
      else
        echo "WARNING: smart auto-recipe DIRECTION_SLICE_BALANCED_CE_WEIGHT=2.00 overridden by env: ${SMOKE_DIRECTION_SLICE_BALANCED_CE_WEIGHT}" >&2
      fi
      if [[ -z "${ENTRY_FOUNDATION_SMOKE_DIRECTION_SLICE_BALANCED_CE_MIN_LABEL_RATE+x}" ]]; then
        SMOKE_DIRECTION_SLICE_BALANCED_CE_MIN_LABEL_RATE=0.10
      else
        echo "WARNING: smart auto-recipe DIRECTION_SLICE_BALANCED_CE_MIN_LABEL_RATE=0.10 overridden by env: ${SMOKE_DIRECTION_SLICE_BALANCED_CE_MIN_LABEL_RATE}" >&2
      fi
      if [[ -z "${ENTRY_FOUNDATION_SMOKE_DIRECTION_SLICE_BALANCED_CE_MIN_ROWS+x}" ]]; then
        SMOKE_DIRECTION_SLICE_BALANCED_CE_MIN_ROWS=8
      else
        echo "WARNING: smart auto-recipe DIRECTION_SLICE_BALANCED_CE_MIN_ROWS=8 overridden by env: ${SMOKE_DIRECTION_SLICE_BALANCED_CE_MIN_ROWS}" >&2
      fi
      if [[ -z "${ENTRY_FOUNDATION_SMOKE_DIRECTION_SLICE_TRUE_MARGIN_WEIGHT+x}" ]]; then
        SMOKE_DIRECTION_SLICE_TRUE_MARGIN_WEIGHT=2.00
      else
        echo "WARNING: smart auto-recipe DIRECTION_SLICE_TRUE_MARGIN_WEIGHT=2.00 overridden by env: ${SMOKE_DIRECTION_SLICE_TRUE_MARGIN_WEIGHT}" >&2
      fi
      if [[ -z "${ENTRY_FOUNDATION_SMOKE_DIRECTION_SLICE_TRUE_MARGIN+x}" ]]; then
        SMOKE_DIRECTION_SLICE_TRUE_MARGIN=0.10
      else
        echo "WARNING: smart auto-recipe DIRECTION_SLICE_TRUE_MARGIN=0.10 overridden by env: ${SMOKE_DIRECTION_SLICE_TRUE_MARGIN}" >&2
      fi
      if [[ -z "${ENTRY_FOUNDATION_SMOKE_DIRECTION_SLICE_TRUE_MARGIN_MIN_LABEL_RATE+x}" ]]; then
        SMOKE_DIRECTION_SLICE_TRUE_MARGIN_MIN_LABEL_RATE=0.10
      else
        echo "WARNING: smart auto-recipe DIRECTION_SLICE_TRUE_MARGIN_MIN_LABEL_RATE=0.10 overridden by env: ${SMOKE_DIRECTION_SLICE_TRUE_MARGIN_MIN_LABEL_RATE}" >&2
      fi
      if [[ -z "${ENTRY_FOUNDATION_SMOKE_DIRECTION_SLICE_TRUE_MARGIN_MIN_ROWS+x}" ]]; then
        SMOKE_DIRECTION_SLICE_TRUE_MARGIN_MIN_ROWS=8
      else
        echo "WARNING: smart auto-recipe DIRECTION_SLICE_TRUE_MARGIN_MIN_ROWS=8 overridden by env: ${SMOKE_DIRECTION_SLICE_TRUE_MARGIN_MIN_ROWS}" >&2
      fi
      if [[ -z "${ENTRY_FOUNDATION_SMOKE_DIRECTION_SLICE_ACCURACY_EDGE_WEIGHT+x}" ]]; then
        SMOKE_DIRECTION_SLICE_ACCURACY_EDGE_WEIGHT=4.00
      else
        echo "WARNING: smart auto-recipe DIRECTION_SLICE_ACCURACY_EDGE_WEIGHT=4.00 overridden by env: ${SMOKE_DIRECTION_SLICE_ACCURACY_EDGE_WEIGHT}" >&2
      fi
      if [[ -z "${ENTRY_FOUNDATION_SMOKE_DIRECTION_SLICE_ACCURACY_EDGE_MARGIN+x}" ]]; then
        SMOKE_DIRECTION_SLICE_ACCURACY_EDGE_MARGIN=0.02
      else
        echo "WARNING: smart auto-recipe DIRECTION_SLICE_ACCURACY_EDGE_MARGIN=0.02 overridden by env: ${SMOKE_DIRECTION_SLICE_ACCURACY_EDGE_MARGIN}" >&2
      fi
      if [[ -z "${ENTRY_FOUNDATION_SMOKE_DIRECTION_SLICE_ACCURACY_EDGE_MIN_LABEL_RATE+x}" ]]; then
        SMOKE_DIRECTION_SLICE_ACCURACY_EDGE_MIN_LABEL_RATE=0.10
      else
        echo "WARNING: smart auto-recipe DIRECTION_SLICE_ACCURACY_EDGE_MIN_LABEL_RATE=0.10 overridden by env: ${SMOKE_DIRECTION_SLICE_ACCURACY_EDGE_MIN_LABEL_RATE}" >&2
      fi
      if [[ -z "${ENTRY_FOUNDATION_SMOKE_DIRECTION_SLICE_ACCURACY_EDGE_MIN_ROWS+x}" ]]; then
        SMOKE_DIRECTION_SLICE_ACCURACY_EDGE_MIN_ROWS=8
      else
        echo "WARNING: smart auto-recipe DIRECTION_SLICE_ACCURACY_EDGE_MIN_ROWS=8 overridden by env: ${SMOKE_DIRECTION_SLICE_ACCURACY_EDGE_MIN_ROWS}" >&2
      fi
      if [[ -z "${ENTRY_FOUNDATION_SMOKE_DIRECTION_SLICE_PRIOR_MATCH_WEIGHT+x}" ]]; then
        SMOKE_DIRECTION_SLICE_PRIOR_MATCH_WEIGHT=3.00
      else
        echo "WARNING: smart auto-recipe DIRECTION_SLICE_PRIOR_MATCH_WEIGHT=3.00 overridden by env: ${SMOKE_DIRECTION_SLICE_PRIOR_MATCH_WEIGHT}" >&2
      fi
      if [[ -z "${ENTRY_FOUNDATION_SMOKE_DIRECTION_SLICE_PRIOR_MATCH_TOLERANCE+x}" ]]; then
        SMOKE_DIRECTION_SLICE_PRIOR_MATCH_TOLERANCE=0.02
      else
        echo "WARNING: smart auto-recipe DIRECTION_SLICE_PRIOR_MATCH_TOLERANCE=0.02 overridden by env: ${SMOKE_DIRECTION_SLICE_PRIOR_MATCH_TOLERANCE}" >&2
      fi
      if [[ -z "${ENTRY_FOUNDATION_SMOKE_DIRECTION_SLICE_PRIOR_MATCH_MIN_LABEL_RATE+x}" ]]; then
        SMOKE_DIRECTION_SLICE_PRIOR_MATCH_MIN_LABEL_RATE=0.10
      else
        echo "WARNING: smart auto-recipe DIRECTION_SLICE_PRIOR_MATCH_MIN_LABEL_RATE=0.10 overridden by env: ${SMOKE_DIRECTION_SLICE_PRIOR_MATCH_MIN_LABEL_RATE}" >&2
      fi
      if [[ -z "${ENTRY_FOUNDATION_SMOKE_DIRECTION_SLICE_PRIOR_MATCH_MIN_ROWS+x}" ]]; then
        SMOKE_DIRECTION_SLICE_PRIOR_MATCH_MIN_ROWS=8
      else
        echo "WARNING: smart auto-recipe DIRECTION_SLICE_PRIOR_MATCH_MIN_ROWS=8 overridden by env: ${SMOKE_DIRECTION_SLICE_PRIOR_MATCH_MIN_ROWS}" >&2
      fi
      if [[ -z "${ENTRY_FOUNDATION_SMOKE_DIRECTION_SLICE_LOSS_AGGREGATION+x}" ]]; then
        SMOKE_DIRECTION_SLICE_LOSS_AGGREGATION=mean_max
      else
        echo "WARNING: smart auto-recipe DIRECTION_SLICE_LOSS_AGGREGATION=mean_max overridden by env: ${SMOKE_DIRECTION_SLICE_LOSS_AGGREGATION}" >&2
      fi
      if [[ -z "${ENTRY_FOUNDATION_SMOKE_DIRECTION_SLICE_BALANCED_SAMPLER+x}" ]]; then
        SMOKE_DIRECTION_SLICE_BALANCED_SAMPLER=1
      else
        echo "WARNING: smart auto-recipe DIRECTION_SLICE_BALANCED_SAMPLER=1 overridden by env: ${SMOKE_DIRECTION_SLICE_BALANCED_SAMPLER}" >&2
      fi
      if [[ -z "${ENTRY_FOUNDATION_SMOKE_DIRECTION_SLICE_BALANCED_SAMPLER_MIN_ROWS+x}" ]]; then
        SMOKE_DIRECTION_SLICE_BALANCED_SAMPLER_MIN_ROWS=8
      else
        echo "WARNING: smart auto-recipe DIRECTION_SLICE_BALANCED_SAMPLER_MIN_ROWS=8 overridden by env: ${SMOKE_DIRECTION_SLICE_BALANCED_SAMPLER_MIN_ROWS}" >&2
      fi
      if [[ -z "${ENTRY_FOUNDATION_SMOKE_DIRECTION_SLICE_HARD_RED_STOP_PATIENCE+x}" ]]; then
        SMOKE_DIRECTION_SLICE_HARD_RED_STOP_PATIENCE=3
      else
        echo "WARNING: smart auto-recipe DIRECTION_SLICE_HARD_RED_STOP_PATIENCE=3 overridden by env: ${SMOKE_DIRECTION_SLICE_HARD_RED_STOP_PATIENCE}" >&2
      fi
      if [[ -z "${ENTRY_FOUNDATION_SMOKE_DIRECTION_SLICE_HARD_RED_STOP_MIN_EPOCHS+x}" ]]; then
        SMOKE_DIRECTION_SLICE_HARD_RED_STOP_MIN_EPOCHS=6
      else
        echo "WARNING: smart auto-recipe DIRECTION_SLICE_HARD_RED_STOP_MIN_EPOCHS=6 overridden by env: ${SMOKE_DIRECTION_SLICE_HARD_RED_STOP_MIN_EPOCHS}" >&2
      fi
      if [[ -z "${ENTRY_FOUNDATION_SMOKE_DIRECTION_VS_FLAT_MARGIN_WEIGHT+x}" ]]; then
        SMOKE_DIRECTION_VS_FLAT_MARGIN_WEIGHT=4.00
      else
        echo "WARNING: smart auto-recipe DIRECTION_VS_FLAT_MARGIN_WEIGHT=4.00 overridden by env: ${SMOKE_DIRECTION_VS_FLAT_MARGIN_WEIGHT}" >&2
      fi
      if [[ -z "${ENTRY_FOUNDATION_SMOKE_DIRECTION_VS_FLAT_MARGIN+x}" ]]; then
        SMOKE_DIRECTION_VS_FLAT_MARGIN=0.10
      else
        echo "WARNING: smart auto-recipe DIRECTION_VS_FLAT_MARGIN=0.10 overridden by env: ${SMOKE_DIRECTION_VS_FLAT_MARGIN}" >&2
      fi
      if [[ -z "${ENTRY_FOUNDATION_SMOKE_HIER_LEGACY_CE_MULT+x}" ]]; then
        SMOKE_HIER_LEGACY_CE_MULT=1.00
      else
        echo "WARNING: smart auto-recipe HIER_LEGACY_CE_MULT=1.00 overridden by env: ${SMOKE_HIER_LEGACY_CE_MULT}" >&2
      fi
      if [[ -z "${ENTRY_FOUNDATION_SMOKE_HIER_TRADE_WEIGHT+x}" ]]; then
        SMOKE_HIER_TRADE_WEIGHT=2.00
      fi
      if [[ -z "${ENTRY_FOUNDATION_SMOKE_HIER_SIDE_WEIGHT+x}" ]]; then
        SMOKE_HIER_SIDE_WEIGHT=1.75
      fi
      if [[ -z "${ENTRY_FOUNDATION_SMOKE_HIER_UTILITY_WEIGHT+x}" ]]; then
        SMOKE_HIER_UTILITY_WEIGHT=1.00
      fi
      if [[ -z "${ENTRY_FOUNDATION_SMOKE_HIER_BAD_PATH_WEIGHT+x}" ]]; then
        SMOKE_HIER_BAD_PATH_WEIGHT=1.25
      fi
      if [[ -z "${ENTRY_FOUNDATION_SMOKE_HIER_MAE_WEIGHT+x}" ]]; then
        SMOKE_HIER_MAE_WEIGHT=0.35
      fi
      if [[ -z "${ENTRY_FOUNDATION_SMOKE_HIER_SIDE_VALIDITY_WEIGHT+x}" ]]; then
        SMOKE_HIER_SIDE_VALIDITY_WEIGHT=1.50
      fi
      if [[ -z "${ENTRY_FOUNDATION_SMOKE_HIER_SIDE_VALIDITY_MIN_UTILITY_BPS+x}" ]]; then
        SMOKE_HIER_SIDE_VALIDITY_MIN_UTILITY_BPS=15.0
      fi
      if [[ -z "${ENTRY_FOUNDATION_SMOKE_HIER_SIDE_VALIDITY_POS_WEIGHT_CAP+x}" ]]; then
        SMOKE_HIER_SIDE_VALIDITY_POS_WEIGHT_CAP=8.0
      fi
      if [[ -z "${ENTRY_FOUNDATION_SMOKE_HIER_POCKET_ABSTAIN_WEIGHT+x}" ]]; then
        SMOKE_HIER_POCKET_ABSTAIN_WEIGHT=5.00
      fi
      if [[ -z "${ENTRY_FOUNDATION_SMOKE_HIER_POCKET_SIDE_MARGIN_WEIGHT+x}" ]]; then
        SMOKE_HIER_POCKET_SIDE_MARGIN_WEIGHT=3.00
      fi
      if [[ -z "${ENTRY_FOUNDATION_SMOKE_HIER_POCKET_UTILITY_MARGIN_BPS+x}" ]]; then
        SMOKE_HIER_POCKET_UTILITY_MARGIN_BPS=30.0
      fi
      if [[ -z "${ENTRY_FOUNDATION_SMOKE_TRENDLINE_RAIL_AUX_WEIGHT+x}" ]]; then
        SMOKE_TRENDLINE_RAIL_AUX_WEIGHT=1.00
      else
        echo "WARNING: smart auto-recipe TRENDLINE_RAIL_AUX_WEIGHT=1.00 overridden by env: ${SMOKE_TRENDLINE_RAIL_AUX_WEIGHT}" >&2
      fi
      if [[ -z "${ENTRY_FOUNDATION_SMOKE_TRENDLINE_RAIL_WRONG_SIDE_WEIGHT+x}" ]]; then
        SMOKE_TRENDLINE_RAIL_WRONG_SIDE_WEIGHT=1.50
      else
        echo "WARNING: smart auto-recipe TRENDLINE_RAIL_WRONG_SIDE_WEIGHT=1.50 overridden by env: ${SMOKE_TRENDLINE_RAIL_WRONG_SIDE_WEIGHT}" >&2
      fi
      if [[ -z "${ENTRY_FOUNDATION_SMOKE_TRENDLINE_RAIL_RISING_WRONG_SHORT_WEIGHT+x}" ]]; then
        SMOKE_TRENDLINE_RAIL_RISING_WRONG_SHORT_WEIGHT=1.50
      fi
      if [[ -z "${ENTRY_FOUNDATION_SMOKE_TRENDLINE_RAIL_FALLING_WRONG_LONG_WEIGHT+x}" ]]; then
        SMOKE_TRENDLINE_RAIL_FALLING_WRONG_LONG_WEIGHT=1.75
      fi
      if [[ -z "${ENTRY_FOUNDATION_SMOKE_TRENDLINE_RAIL_FINAL_MARGIN_WEIGHT+x}" ]]; then
        SMOKE_TRENDLINE_RAIL_FINAL_MARGIN_WEIGHT=5.00
      fi
      if [[ -z "${ENTRY_FOUNDATION_SMOKE_TRENDLINE_RAIL_HIER_MARGIN_WEIGHT+x}" ]]; then
        SMOKE_TRENDLINE_RAIL_HIER_MARGIN_WEIGHT=4.00
      fi
      if [[ -z "${ENTRY_FOUNDATION_SMOKE_TRENDLINE_RAIL_FLAT_TRADE_WEIGHT+x}" ]]; then
        SMOKE_TRENDLINE_RAIL_FLAT_TRADE_WEIGHT=3.00
      fi
      if [[ -z "${ENTRY_FOUNDATION_SMOKE_TRENDLINE_RAIL_UTILITY_MARGIN_WEIGHT+x}" ]]; then
        SMOKE_TRENDLINE_RAIL_UTILITY_MARGIN_WEIGHT=5.00
      fi
      if [[ -z "${ENTRY_FOUNDATION_SMOKE_TRENDLINE_RAIL_MARGIN+x}" ]]; then
        SMOKE_TRENDLINE_RAIL_MARGIN=1.00
      fi
      if [[ -z "${ENTRY_FOUNDATION_SMOKE_TRENDLINE_RAIL_UTILITY_MARGIN_BPS+x}" ]]; then
        SMOKE_TRENDLINE_RAIL_UTILITY_MARGIN_BPS=30.0
      fi
      if [[ -z "${ENTRY_FOUNDATION_SMOKE_FLAT_CLASS_WEIGHT_FLOOR+x}" ]]; then
        SMOKE_FLAT_CLASS_WEIGHT_FLOOR=1.00
      fi
      if [[ -z "${ENTRY_FOUNDATION_SMOKE_ANCHOR_GATE_INIT+x}" ]]; then
        SMOKE_ANCHOR_GATE_INIT=0.0
      else
        echo "WARNING: smart auto-recipe ANCHOR_GATE_INIT=0.0 overridden by env: ${SMOKE_ANCHOR_GATE_INIT}" >&2
      fi
      if [[ -z "${ENTRY_FOUNDATION_SMOKE_BAD_PATH_PROB_PENALTY+x}" ]]; then
        SMOKE_BAD_PATH_PROB_PENALTY=0.0
      else
        echo "WARNING: smart auto-recipe BAD_PATH_PROB_PENALTY=0.0 overridden by env: ${SMOKE_BAD_PATH_PROB_PENALTY}" >&2
      fi
      REFRESH_SMOKE=0
      shift
      ;;
    --materialize-only) MATERIALIZE_ONLY=1; shift ;;
    --manifest-only) MANIFEST_ONLY=1; shift ;;
    --refresh-smoke) REFRESH_SMOKE=1; shift ;;
    --dry-run) DRY_RUN=1; shift ;;
    --skip-smoke-audit) AUDIT_AFTER=0; shift ;;
    --audit-device) AUDIT_DEVICE="$2"; shift 2 ;;
    --audit-batch-size) AUDIT_BATCH_SIZE="$2"; shift 2 ;;
    --require-edge-audit) REQUIRE_EDGE_AUDIT=1; shift ;;
    --no-require-edge-audit) REQUIRE_EDGE_AUDIT=0; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "FATAL: unknown arg: $1" >&2; usage >&2; exit 2 ;;
  esac
done

if [[ -z "${VEDTAK:-}" ]]; then
  echo "FATAL: --vedtak is required for foundation seq146 smoke train." >&2
  echo "This is still a train command, so it must be an explicit user decision." >&2
  exit 2
fi
if [[ "$RUN_FLAVOR" = "challenger_seq215" && "$MATERIALIZE_ONLY" != "1" && "$VEDTAK" != *"SEQ215"* ]]; then
  echo "FATAL: challenger seq215 smoke manifest/train/dry-run requires an explicit SEQ215 vedtak id." >&2
  echo "Use a new id such as ENTRY_FOUNDATION_SMOKE_TRAIN_20260630_SEQ215_V1 after gates are green." >&2
  exit 2
fi
if [[ "$RUN_FLAVOR" = "smart_seq520" && "$MATERIALIZE_ONLY" != "1" && "$VEDTAK" != *"SMART"* && "$VEDTAK" != *"SEQ520"* ]]; then
  echo "FATAL: smart seq520 smoke train requires an explicit SMART/SEQ520 vedtak id." >&2
  echo "Use a reviewed id only after smart post-rebuild, smoke-readiness and trainability gates are green." >&2
  exit 2
fi

case "$DEVICE" in
  auto|cpu|cuda) ;;
  *) echo "FATAL: --device must be auto, cpu, or cuda; got $DEVICE" >&2; exit 2 ;;
esac
case "$AUDIT_DEVICE" in
  auto|cpu|cuda) ;;
  *) echo "FATAL: --audit-device must be auto, cpu, or cuda; got $AUDIT_DEVICE" >&2; exit 2 ;;
esac
if [[ "$REQUIRE_EDGE_AUDIT" = "1" && "$AUDIT_AFTER" != "1" && "$MATERIALIZE_ONLY" != "1" ]]; then
  echo "FATAL: --require-edge-audit cannot be combined with --skip-smoke-audit." >&2
  echo "Candidate-readiness requires a post-smoke audit with edge diagnostics." >&2
  exit 2
fi
if [[ "$MANIFEST_ONLY" = "1" && "$DRY_RUN" = "1" ]]; then
  echo "FATAL: --manifest-only cannot be combined with --dry-run." >&2
  exit 2
fi

cd "$REPO"

require_clean_git_for_real_train() {
  GIT_STATUS_SHORT=$(git status --short)
  if [[ -n "$GIT_STATUS_SHORT" ]]; then
    echo "FATAL: real foundation smoke train requires clean git worktree." >&2
    echo "Use --dry-run or --manifest-only for inspection/proof without starting trainer." >&2
    echo "$GIT_STATUS_SHORT" >&2
    exit 2
  fi
}

require_foundation_contract_ready_for_manifest_only() {
  "$PY" - <<'PY'
import json
import sys
from pathlib import Path

path = Path("/home/andre2/GX1_DATA/reports/entry_training_readiness_20260628_v1/ENTRY_TRAINING_READINESS_latest.json")
report = json.loads(path.read_text(encoding="utf-8"))
if not report.get("foundation_contract_ready_for_smoke"):
    print("FATAL: manifest-only requires foundation_contract_ready_for_smoke=true.", file=sys.stderr)
    print(f"Readiness decision: {report.get('decision')}", file=sys.stderr)
    print(f"Readiness failures: {len(report.get('failures') or [])}", file=sys.stderr)
    print(f"Readiness report: {path}", file=sys.stderr)
    raise SystemExit(2)
PY
}

if [[ "$MATERIALIZE_ONLY" = "1" || "$REFRESH_SMOKE" = "1" || ! -f "$SMOKE_DATASET/SMOKE_DATASET_MANIFEST.json" ]]; then
  if [[ "$RUN_FLAVOR" = "smart_seq520" ]]; then
    if [[ "$DRY_RUN" = "1" && "$MATERIALIZE_ONLY" != "1" && "$REFRESH_SMOKE" != "1" ]]; then
      echo "WARNING: smart seq520 smoke dataset manifest is missing; dry-run prints the command only: $SMOKE_DATASET" >&2
    else
    echo "FATAL: smart seq520 smoke train cannot materialize/refresh the smoke dataset directly." >&2
    echo "Run the explicit smart post-rebuild refresh gate first; this train wrapper consumes only proven smart smoke artifacts." >&2
    exit 2
    fi
  else
    "$PY" -m gx1.scripts.materialize_entry_foundation_smoke_dataset_v1 \
      --source-dir "$SOURCE_DATASET" \
      --out-dir "$SMOKE_DATASET" \
      --stem "$SMOKE_STEM" \
      --feature-audit-json "$FEATURE_AUDIT" \
      --target-audit-json "$TARGET_AUDIT" \
      --specialist-audit-json "$SPECIALIST_AUDIT" \
      --schema-version "$SMOKE_DATASET_SCHEMA" \
      --train-rows "$TRAIN_ROWS" \
      --val-rows "$VAL_ROWS" \
      --test-rows "$TEST_ROWS" \
      --quiet
  fi
else
  echo "Using existing smoke dataset: $SMOKE_DATASET"
fi

if [[ "$MATERIALIZE_ONLY" = "1" ]]; then
  echo "Smoke dataset materialized: $SMOKE_DATASET"
  exit 0
fi

PREFLIGHT_GUARDRAILS_JSON="$DATA/reports/entry_foundation_guardrails_20260628_v1/ENTRY_FOUNDATION_GUARDRAILS_latest.json"
PREFLIGHT_READINESS_JSON="$DATA/reports/entry_training_readiness_20260628_v1/ENTRY_TRAINING_READINESS_latest.json"
if [[ "$RUN_FLAVOR" = "smart_seq520" ]]; then
  PREFLIGHT_GUARDRAILS_JSON="$DATA/reports/entry_smart_seq520_smoke_readiness_20260630_v1/ENTRY_SMART_SEQ520_SMOKE_READINESS_latest.json"
  PREFLIGHT_READINESS_JSON="$DATA/reports/entry_smart_seq520_trainability_readiness_20260630_v1/ENTRY_SMART_SEQ520_TRAINABILITY_READINESS_latest.json"
fi

if [[ "$DRY_RUN" != "1" ]]; then
  if [[ "$RUN_FLAVOR" = "smart_seq520" ]]; then
    scripts/entry_next_edge_control.sh smart-smoke-readiness --quiet
    scripts/entry_next_edge_control.sh smart-trainability-readiness --quiet
    if [[ "$MANIFEST_ONLY" != "1" ]]; then
      require_clean_git_for_real_train
    fi
  else
    scripts/entry_next_edge_control.sh verify --quiet
    scripts/entry_next_edge_control.sh foundation-guardrails --quiet
    if [[ "$MANIFEST_ONLY" = "1" ]]; then
      scripts/entry_next_edge_control.sh train-readiness --quiet --no-fail-on-not-ready
      require_foundation_contract_ready_for_manifest_only
    else
      require_clean_git_for_real_train
      scripts/entry_next_edge_control.sh train-readiness --quiet
    fi
  fi
fi

STAMP=$(date -u '+%Y%m%dT%H%M%SZ')
OUT_BUNDLE=$DATA/runs/FASE2B_REGIME_V4_20260605/v10_6yr_rebuild_20260628_foundation_seq146/v10_entry_${RUN_FLAVOR}_smoke_$STAMP
PRETRAIN_MANIFEST=$SMOKE_TRAIN_MANIFEST_DIR/ENTRY_FOUNDATION_SMOKE_TRAIN_RUN_MANIFEST_$STAMP.json
RUN_MODE=real_train
if [[ "$MANIFEST_ONLY" = "1" ]]; then
  RUN_MODE=manifest_only
fi

CMD=(
  env
  GX1_DATA="$DATA"
  GX1_REGIME_V4=1
  GX1_TREND_REGIME_FROM_D1=1
  GX1_ALLOW_LEGACY_ENTRY_V10_RESEARCH=20260627_ALLOW_LEGACY_ENTRY_V10_RESEARCH
  GX1_ENTRY_ALLOW_TRAIN_ENV_OVERRIDES=1
  GX1_PERTF_CLOSED_BAR=1
  ENTRY_AUX_BAD_PATH_WEIGHT="$SMOKE_BAD_PATH_WEIGHT"
  ENTRY_BAD_PATH_QUALITY_RANK_WEIGHT="$SMOKE_BAD_PATH_QUALITY_RANK_WEIGHT"
  ENTRY_BAD_PATH_QUALITY_RANK_MARGIN="$SMOKE_BAD_PATH_QUALITY_RANK_MARGIN"
  ENTRY_BAD_PATH_QUALITY_RANK_QUANTILE="$SMOKE_BAD_PATH_QUALITY_RANK_QUANTILE"
  ENTRY_BAD_PATH_PROB_PENALTY="$SMOKE_BAD_PATH_PROB_PENALTY"
  ENTRY_PATH_QUALITY_RANK_WEIGHT="$SMOKE_PATH_QUALITY_RANK_WEIGHT"
  ENTRY_PATH_QUALITY_RANK_MARGIN="$SMOKE_PATH_QUALITY_RANK_MARGIN"
  ENTRY_PATH_QUALITY_RANK_QUANTILE="$SMOKE_PATH_QUALITY_RANK_QUANTILE"
  ENTRY_PRED_BALANCE_ALPHA="$SMOKE_PRED_BALANCE_ALPHA"
  ENTRY_PRED_BALANCE_TARGET="$SMOKE_PRED_BALANCE_TARGET"
  ENTRY_PRED_BALANCE_CLASS_WEIGHTS="$SMOKE_PRED_BALANCE_CLASS_WEIGHTS"
  ENTRY_DIRECTION_CE_SCALE="$SMOKE_DIRECTION_CE_SCALE"
  ENTRY_TAIL_DIRECTION_CE_WEIGHT="$SMOKE_TAIL_DIRECTION_CE_WEIGHT"
  ENTRY_TAIL_DIRECTION_QUALITY_QUANTILE="$SMOKE_TAIL_DIRECTION_QUALITY_QUANTILE"
  ENTRY_TAIL_DIRECTION_MIN_BATCH="$SMOKE_TAIL_DIRECTION_MIN_BATCH"
  GX1_V10_CKPT_MONITOR="$SMOKE_CKPT_MONITOR"
  ENTRY_CKPT_CLASS_BALANCE_GUARD_WEIGHT="$SMOKE_CKPT_CLASS_BALANCE_GUARD_WEIGHT"
  ENTRY_CKPT_CLASS_BALANCE_MIN_PRED_TO_LABEL="$SMOKE_CKPT_CLASS_BALANCE_MIN_PRED_TO_LABEL"
  ENTRY_CKPT_CLASS_BALANCE_MIN_PRED_RATE="$SMOKE_CKPT_CLASS_BALANCE_MIN_PRED_RATE"
  ENTRY_CKPT_DIRECTION_SLICE_GUARD="$SMOKE_CKPT_DIRECTION_SLICE_GUARD"
  ENTRY_DIRECTION_MIN_PRED_RATE_LOSS_WEIGHT="$SMOKE_DIRECTION_MIN_PRED_RATE_LOSS_WEIGHT"
  ENTRY_DIRECTION_MIN_PRED_RATE_FRACTION="$SMOKE_DIRECTION_MIN_PRED_RATE_FRACTION"
  ENTRY_DIRECTION_MIN_PRED_RATE_FLOOR="$SMOKE_DIRECTION_MIN_PRED_RATE_FLOOR"
  ENTRY_DIRECTION_MIN_PRED_RATE_SOFTMAX_TEMPERATURE="$SMOKE_DIRECTION_MIN_PRED_RATE_SOFTMAX_TEMPERATURE"
  ENTRY_DIRECTION_GLOBAL_PRIOR_MATCH_WEIGHT="$SMOKE_DIRECTION_GLOBAL_PRIOR_MATCH_WEIGHT"
  ENTRY_DIRECTION_GLOBAL_PRIOR_MATCH_TOLERANCE="$SMOKE_DIRECTION_GLOBAL_PRIOR_MATCH_TOLERANCE"
  ENTRY_DIRECTION_GLOBAL_PRIOR_MATCH_MIN_LABEL_RATE="$SMOKE_DIRECTION_GLOBAL_PRIOR_MATCH_MIN_LABEL_RATE"
  ENTRY_DIRECTION_SLICE_MIN_PRED_RATE_LOSS_WEIGHT="$SMOKE_DIRECTION_SLICE_MIN_PRED_RATE_LOSS_WEIGHT"
  ENTRY_DIRECTION_SLICE_MIN_PRED_RATE_FRACTION="$SMOKE_DIRECTION_SLICE_MIN_PRED_RATE_FRACTION"
  ENTRY_DIRECTION_SLICE_MIN_PRED_RATE_FLOOR="$SMOKE_DIRECTION_SLICE_MIN_PRED_RATE_FLOOR"
  ENTRY_DIRECTION_SLICE_MIN_LABEL_RATE="$SMOKE_DIRECTION_SLICE_MIN_LABEL_RATE"
  ENTRY_DIRECTION_SLICE_MIN_ROWS="$SMOKE_DIRECTION_SLICE_MIN_ROWS"
  ENTRY_DIRECTION_SLICE_CTX_CAT_INDICES="$SMOKE_DIRECTION_SLICE_CTX_CAT_INDICES"
  ENTRY_DIRECTION_SLICE_RECALL_LOSS_WEIGHT="$SMOKE_DIRECTION_SLICE_RECALL_LOSS_WEIGHT"
  ENTRY_DIRECTION_SLICE_RECALL_PROB_FLOOR="$SMOKE_DIRECTION_SLICE_RECALL_PROB_FLOOR"
  ENTRY_DIRECTION_SLICE_RECALL_MIN_LABEL_RATE="$SMOKE_DIRECTION_SLICE_RECALL_MIN_LABEL_RATE"
  ENTRY_DIRECTION_SLICE_RECALL_MIN_ROWS="$SMOKE_DIRECTION_SLICE_RECALL_MIN_ROWS"
  ENTRY_DIRECTION_SLICE_BALANCED_CE_WEIGHT="$SMOKE_DIRECTION_SLICE_BALANCED_CE_WEIGHT"
  ENTRY_DIRECTION_SLICE_BALANCED_CE_MIN_LABEL_RATE="$SMOKE_DIRECTION_SLICE_BALANCED_CE_MIN_LABEL_RATE"
  ENTRY_DIRECTION_SLICE_BALANCED_CE_MIN_ROWS="$SMOKE_DIRECTION_SLICE_BALANCED_CE_MIN_ROWS"
  ENTRY_DIRECTION_SLICE_TRUE_MARGIN_WEIGHT="$SMOKE_DIRECTION_SLICE_TRUE_MARGIN_WEIGHT"
  ENTRY_DIRECTION_SLICE_TRUE_MARGIN="$SMOKE_DIRECTION_SLICE_TRUE_MARGIN"
  ENTRY_DIRECTION_SLICE_TRUE_MARGIN_MIN_LABEL_RATE="$SMOKE_DIRECTION_SLICE_TRUE_MARGIN_MIN_LABEL_RATE"
  ENTRY_DIRECTION_SLICE_TRUE_MARGIN_MIN_ROWS="$SMOKE_DIRECTION_SLICE_TRUE_MARGIN_MIN_ROWS"
  ENTRY_DIRECTION_SLICE_ACCURACY_EDGE_WEIGHT="$SMOKE_DIRECTION_SLICE_ACCURACY_EDGE_WEIGHT"
  ENTRY_DIRECTION_SLICE_ACCURACY_EDGE_MARGIN="$SMOKE_DIRECTION_SLICE_ACCURACY_EDGE_MARGIN"
  ENTRY_DIRECTION_SLICE_ACCURACY_EDGE_MIN_LABEL_RATE="$SMOKE_DIRECTION_SLICE_ACCURACY_EDGE_MIN_LABEL_RATE"
  ENTRY_DIRECTION_SLICE_ACCURACY_EDGE_MIN_ROWS="$SMOKE_DIRECTION_SLICE_ACCURACY_EDGE_MIN_ROWS"
  ENTRY_DIRECTION_SLICE_PRIOR_MATCH_WEIGHT="$SMOKE_DIRECTION_SLICE_PRIOR_MATCH_WEIGHT"
  ENTRY_DIRECTION_SLICE_PRIOR_MATCH_TOLERANCE="$SMOKE_DIRECTION_SLICE_PRIOR_MATCH_TOLERANCE"
  ENTRY_DIRECTION_SLICE_PRIOR_MATCH_MIN_LABEL_RATE="$SMOKE_DIRECTION_SLICE_PRIOR_MATCH_MIN_LABEL_RATE"
  ENTRY_DIRECTION_SLICE_PRIOR_MATCH_MIN_ROWS="$SMOKE_DIRECTION_SLICE_PRIOR_MATCH_MIN_ROWS"
  ENTRY_DIRECTION_SLICE_LOSS_AGGREGATION="$SMOKE_DIRECTION_SLICE_LOSS_AGGREGATION"
  ENTRY_DIRECTION_SLICE_BALANCED_SAMPLER="$SMOKE_DIRECTION_SLICE_BALANCED_SAMPLER"
  ENTRY_DIRECTION_SLICE_BALANCED_SAMPLER_MIN_ROWS="$SMOKE_DIRECTION_SLICE_BALANCED_SAMPLER_MIN_ROWS"
  ENTRY_DIRECTION_SLICE_HARD_RED_STOP_PATIENCE="$SMOKE_DIRECTION_SLICE_HARD_RED_STOP_PATIENCE"
  ENTRY_DIRECTION_SLICE_HARD_RED_STOP_MIN_EPOCHS="$SMOKE_DIRECTION_SLICE_HARD_RED_STOP_MIN_EPOCHS"
  ENTRY_DIRECTION_VS_FLAT_MARGIN_WEIGHT="$SMOKE_DIRECTION_VS_FLAT_MARGIN_WEIGHT"
  ENTRY_DIRECTION_VS_FLAT_MARGIN="$SMOKE_DIRECTION_VS_FLAT_MARGIN"
  ENTRY_HIER_LEGACY_CE_MULT="$SMOKE_HIER_LEGACY_CE_MULT"
  ENTRY_HIER_TRADE_WEIGHT="$SMOKE_HIER_TRADE_WEIGHT"
  ENTRY_HIER_SIDE_WEIGHT="$SMOKE_HIER_SIDE_WEIGHT"
  ENTRY_HIER_UTILITY_WEIGHT="$SMOKE_HIER_UTILITY_WEIGHT"
  ENTRY_HIER_BAD_PATH_WEIGHT="$SMOKE_HIER_BAD_PATH_WEIGHT"
  ENTRY_HIER_MAE_WEIGHT="$SMOKE_HIER_MAE_WEIGHT"
  ENTRY_RESIDUAL_SCALE="$SMOKE_RESIDUAL_SCALE"
  ENTRY_ANCHOR_EPS="$SMOKE_ANCHOR_EPS"
  ENTRY_HIER_SIDE_VALIDITY_WEIGHT="$SMOKE_HIER_SIDE_VALIDITY_WEIGHT"
  ENTRY_HIER_SIDE_VALIDITY_MIN_UTILITY_BPS="$SMOKE_HIER_SIDE_VALIDITY_MIN_UTILITY_BPS"
  ENTRY_HIER_SIDE_VALIDITY_POS_WEIGHT_CAP="$SMOKE_HIER_SIDE_VALIDITY_POS_WEIGHT_CAP"
  ENTRY_HIER_POCKET_ABSTAIN_WEIGHT="$SMOKE_HIER_POCKET_ABSTAIN_WEIGHT"
  ENTRY_HIER_POCKET_SIDE_MARGIN_WEIGHT="$SMOKE_HIER_POCKET_SIDE_MARGIN_WEIGHT"
  ENTRY_HIER_POCKET_UTILITY_MARGIN_BPS="$SMOKE_HIER_POCKET_UTILITY_MARGIN_BPS"
  ENTRY_TRENDLINE_RAIL_AUX_WEIGHT="$SMOKE_TRENDLINE_RAIL_AUX_WEIGHT"
  ENTRY_TRENDLINE_RAIL_WRONG_SIDE_WEIGHT="$SMOKE_TRENDLINE_RAIL_WRONG_SIDE_WEIGHT"
  ENTRY_TRENDLINE_RAIL_RISING_WRONG_SHORT_WEIGHT="$SMOKE_TRENDLINE_RAIL_RISING_WRONG_SHORT_WEIGHT"
  ENTRY_TRENDLINE_RAIL_FALLING_WRONG_LONG_WEIGHT="$SMOKE_TRENDLINE_RAIL_FALLING_WRONG_LONG_WEIGHT"
  ENTRY_TRENDLINE_RAIL_FINAL_MARGIN_WEIGHT="$SMOKE_TRENDLINE_RAIL_FINAL_MARGIN_WEIGHT"
  ENTRY_TRENDLINE_RAIL_HIER_MARGIN_WEIGHT="$SMOKE_TRENDLINE_RAIL_HIER_MARGIN_WEIGHT"
  ENTRY_TRENDLINE_RAIL_FLAT_TRADE_WEIGHT="$SMOKE_TRENDLINE_RAIL_FLAT_TRADE_WEIGHT"
  ENTRY_TRENDLINE_RAIL_UTILITY_MARGIN_WEIGHT="$SMOKE_TRENDLINE_RAIL_UTILITY_MARGIN_WEIGHT"
  ENTRY_TRENDLINE_RAIL_MARGIN="$SMOKE_TRENDLINE_RAIL_MARGIN"
  ENTRY_TRENDLINE_RAIL_UTILITY_MARGIN_BPS="$SMOKE_TRENDLINE_RAIL_UTILITY_MARGIN_BPS"
  ENTRY_SYMMETRIC_NEGATIVES="$SMOKE_SYMMETRIC_NEGATIVES"
  ENTRY_FLAT_CLASS_WEIGHT_FLOOR="$SMOKE_FLAT_CLASS_WEIGHT_FLOOR"
  ENTRY_SPECIALIST_GATE_ENTROPY_WEIGHT="$SMOKE_SPECIALIST_GATE_ENTROPY_WEIGHT"
  ENTRY_SPECIALIST_GATE_BALANCE_WEIGHT="$SMOKE_SPECIALIST_GATE_BALANCE_WEIGHT"
  ENTRY_SPECIALIST_GATE_MIN_MEAN="$SMOKE_SPECIALIST_GATE_MIN_MEAN"
  "$PY" -m gx1.models.entry_v10.entry_v10_ctx_train_v3
  --train
  --vedtak "$VEDTAK"
  --device "$DEVICE"
  --dataset_dir "$SMOKE_DATASET"
  --dataset_train_parquet "$SMOKE_DATASET/${SMOKE_STEM}_train.parquet"
  --out_bundle_dir "$OUT_BUNDLE"
  --m5-prebuilt-path "$M5_PREBUILT"
  --epochs "$EPOCHS"
  --lr "$SMOKE_LR"
  --batch_size "$BATCH_SIZE"
  --early-stopping-patience "$EARLY_STOP_PATIENCE"
  --early-stopping-min-delta 0.0
  --num-workers 0
  --multi-tf-seq-len 16
  --per-tf-seq-len-h4 8
  --per-tf-seq-len-d1 8
  --grad-accum-steps 1
  --grad-clip-norm "$SMOKE_GRAD_CLIP_NORM"
  --weight-decay "$SMOKE_WEIGHT_DECAY"
  --enable-tf-agreement-head
  --enable-path-quality-variance-head
  --enable-position-size-head
  --enable-dip-head
  --enable-forecast-head
  --enable-timing-head
  --enable-tail-risk-head
  --enable-vol-forecast-head
  --enable-mtf-direction-head
  --enable-specialist-fusion
  --specialist-audit-json "$SPECIALIST_AUDIT"
  --specialist-contract-mode "$SPECIALIST_CONTRACT_MODE"
  --specialist-num-layers 1
  --specialist-fusion-scale 0.25
)

if [[ "$SMOKE_ENABLE_XAU_DIRECTION_REPAIR_HEADS" = "1" ]]; then
  CMD+=(
    --enable-xau-direction-repair-heads
    --anchor-gate-init "$SMOKE_ANCHOR_GATE_INIT"
  )
fi

AUDIT_CMD=(
  scripts/entry_next_edge_control.sh
  audit-smoke-bundle
  --bundle-dir "$OUT_BUNDLE"
  --dataset-dir "$SMOKE_DATASET"
  --device "$AUDIT_DEVICE"
  --batch-size "$AUDIT_BATCH_SIZE"
  --require-head-contract
  --out-dir "$SMOKE_BUNDLE_AUDIT_OUT"
  --target-audit-json "$TARGET_AUDIT"
  --pretrain-manifest-json "$PRETRAIN_MANIFEST"
)
if [[ "$REQUIRE_EDGE_AUDIT" = "1" ]]; then
  AUDIT_CMD+=(--require-edge --edge-test-scope strict)
fi

if [[ "$DRY_RUN" = "1" ]]; then
  if [[ "$RUN_FLAVOR" = "smart_seq520" ]]; then
    echo "Real-train preflight command: scripts/entry_next_edge_control.sh smart-smoke-readiness --quiet"
    echo "Real-train preflight command: scripts/entry_next_edge_control.sh smart-trainability-readiness --quiet"
  else
    echo "Real-train preflight command: scripts/entry_next_edge_control.sh verify --quiet"
    echo "Real-train preflight command: scripts/entry_next_edge_control.sh foundation-guardrails --quiet"
    echo "Real-train preflight command: scripts/entry_next_edge_control.sh train-readiness --quiet"
  fi
  echo "Pre-train run manifest path: $PRETRAIN_MANIFEST"
  echo "Smoke resource cap: mem=$SMOKE_RUN_MEM swap=$SMOKE_RUN_SWAP runner=$SMOKE_CAPPED_RUNNER num_workers=0"
  printf 'Capped smoke train command:'
  printf ' %q' "$SMOKE_CAPPED_RUNNER" --mem "$SMOKE_RUN_MEM" --swap "$SMOKE_RUN_SWAP" -- "${CMD[@]}"
  printf '\n'
  printf 'Smoke train command:'
  printf ' %q' "${CMD[@]}"
  printf '\n'
  if [[ "$AUDIT_AFTER" = "1" ]]; then
    printf 'Post-smoke audit command:'
    printf ' %q' "${AUDIT_CMD[@]}"
    printf '\n'
  else
    echo "Post-smoke audit command: skipped by --skip-smoke-audit"
  fi
  exit 0
fi

mkdir -p "$SMOKE_TRAIN_MANIFEST_DIR"
FEATURE_AUDIT_JSON="$FEATURE_AUDIT" \
TARGET_AUDIT_JSON="$TARGET_AUDIT" \
SPECIALIST_CONTRACT_MODE="$SPECIALIST_CONTRACT_MODE" \
EXPECTED_SIGNAL_DIM="$EXPECTED_SIGNAL_DIM" \
RUN_FLAVOR="$RUN_FLAVOR" \
SMOKE_RUN_MEM="$SMOKE_RUN_MEM" \
SMOKE_RUN_SWAP="$SMOKE_RUN_SWAP" \
"$PY" - "$PRETRAIN_MANIFEST" "$VEDTAK" "$OUT_BUNDLE" "$SOURCE_DATASET" "$SMOKE_DATASET" \
  "$SMOKE_DATASET/SMOKE_DATASET_MANIFEST.json" "$M5_PREBUILT" "$SPECIALIST_AUDIT" \
  "$PREFLIGHT_GUARDRAILS_JSON" \
  "$PREFLIGHT_READINESS_JSON" \
  "$AUDIT_AFTER" "$REQUIRE_EDGE_AUDIT" "$DEVICE" "$EPOCHS" "$BATCH_SIZE" "$TRAIN_ROWS" "$VAL_ROWS" "$TEST_ROWS" \
  "$RUN_MODE" "${CMD[@]}" __AUDIT_CMD__ "${AUDIT_CMD[@]}" <<'PY'
import json
import hashlib
import os
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

manifest_path = Path(sys.argv[1])
repo = Path("/home/andre2/src/GX1_ENGINE")
sep = "__AUDIT_CMD__"
sep_idx = sys.argv.index(sep)
train_cmd = sys.argv[20:sep_idx]
audit_cmd = sys.argv[sep_idx + 1:]


def git(*args: str) -> str:
    proc = subprocess.run(["git", "-C", str(repo), *args], text=True, capture_output=True, check=False)
    return (proc.stdout if proc.returncode == 0 else proc.stderr).strip()


def read_json(path: str | Path) -> dict:
    p = Path(path)
    return json.loads(p.read_text(encoding="utf-8"))


def sha256_file(path: str | Path) -> str:
    p = Path(path)
    h = hashlib.sha256()
    with p.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def artifact_fingerprint(path: str | Path | None) -> dict:
    if not path:
        return {
            "path": None,
            "exists": False,
            "size_bytes": 0,
            "mtime_ns": 0,
            "sha256": "",
        }
    p = Path(path).expanduser().resolve()
    exists = p.exists() and p.is_file()
    stat = p.stat() if exists else None
    return {
        "path": str(p),
        "exists": bool(exists),
        "size_bytes": int(stat.st_size) if stat is not None else 0,
        "mtime_ns": int(stat.st_mtime_ns) if stat is not None else 0,
        "sha256": sha256_file(p) if exists else "",
    }


def run_artifact_fingerprints(paths: dict) -> dict:
    return {
        key: artifact_fingerprint(path)
        for key, path in paths.items()
        if key != "training_readiness"
    }


def command_env_value(command: list[str], name: str) -> str | None:
    prefix = f"{name}="
    for item in command:
        if isinstance(item, str) and item.startswith(prefix):
            return item[len(prefix):]
    return None


def command_arg_value(command: list[str], flag: str) -> str | None:
    for idx, item in enumerate(command):
        if item == flag and idx + 1 < len(command):
            return command[idx + 1]
    return None


def feature_contract_summary(report: dict) -> dict:
    emitted = report.get("emitted_contracts") if isinstance(report.get("emitted_contracts"), dict) else {}
    source_by_split = {
        str(split): {
            "source_field_count": int((contract or {}).get("foundation_structure_source_field_count") or 0),
            "source_missing_count": int((contract or {}).get("foundation_structure_source_missing_count") or 0),
        }
        for split, contract in emitted.items()
        if isinstance(contract, dict)
    }
    return {
        "decision": report.get("decision"),
        "selected_feature_count": report.get("selected_feature_count"),
        "foundation_required_feature_count": report.get("foundation_required_feature_count"),
        "foundation_objective_coverage_all_present": report.get("foundation_objective_coverage_all_present"),
        "foundation_objective_coverage": [
            {
                "objective": row.get("objective"),
                "present_count": row.get("present_count"),
                "required_count": row.get("required_count"),
                "missing_count": row.get("missing_count"),
            }
            for row in report.get("foundation_objective_coverage", [])
            if isinstance(row, dict)
        ],
        "foundation_objective_liveness_all_live": report.get("foundation_objective_liveness_all_live"),
        "foundation_objective_liveness": [
            {
                "split": row.get("split"),
                "objective": row.get("objective"),
                "observed_count": row.get("observed_count"),
                "required_count": row.get("required_count"),
                "missing_count": row.get("missing_count"),
                "nonfinite_count": row.get("nonfinite_count"),
                "near_constant_count": row.get("near_constant_count"),
                "mean_active_rate": row.get("mean_active_rate"),
            }
            for row in report.get("foundation_objective_liveness", [])
            if isinstance(row, dict)
        ],
        "foundation_source_field_liveness_all_live": report.get("foundation_source_field_liveness_all_live"),
        "min_required_source_active_rate": report.get("min_required_source_active_rate"),
        "min_required_source_active_count": report.get("min_required_source_active_count"),
        "foundation_source_field_liveness": [
            {
                "split": row.get("split"),
                "source_field": row.get("source_field"),
                "source_kind": row.get("source_kind"),
                "observed": row.get("observed"),
                "n": row.get("n"),
                "nonfinite_count": row.get("nonfinite_count"),
                "active_count": row.get("active_count"),
                "active_rate": row.get("active_rate"),
                "near_constant": row.get("near_constant"),
            }
            for row in report.get("foundation_source_field_liveness", [])
            if isinstance(row, dict)
        ],
        "foundation_source_fields_by_split": source_by_split,
        "failures": report.get("failures") or [],
    }


def specialist_contract_summary(report: dict) -> dict:
    architecture = report.get("architecture_contract") if isinstance(report.get("architecture_contract"), dict) else {}
    recommended = architecture.get("recommended_fusion") if isinstance(architecture.get("recommended_fusion"), dict) else {}
    raw_indices = architecture.get("specialist_input_indices") if isinstance(architecture.get("specialist_input_indices"), dict) else {}
    from gx1.models.entry_v10.entry_v10_ctx_train_v3 import _load_specialist_fusion_contract

    contract_mode = os.environ.get("SPECIALIST_CONTRACT_MODE", "foundation_seq146")
    expected_signal_dim = int(os.environ.get("EXPECTED_SIGNAL_DIM", "146"))
    trainer_indices, trainer_meta = _load_specialist_fusion_contract(
        Path(specialist_audit_path),
        expected_signal_dim=expected_signal_dim,
        contract_mode=contract_mode,
    )
    return {
        "decision": report.get("decision"),
        "signal_field_count": report.get("signal_field_count"),
        "selected_feature_count": report.get("selected_feature_count"),
        "required_training_specialists": report.get("required_training_specialists") or [],
        "architecture_specialist_groups": sorted(
            str(name) for name, values in raw_indices.items() if list(values or [])
        ),
        "trainable_specialists": trainer_meta.get("trainable_specialists") or sorted(trainer_indices),
        "trainer_loader_group_feature_counts": trainer_meta.get("group_feature_counts") or {},
        "excluded_specialist_groups": trainer_meta.get("excluded_specialist_groups") or {},
        "specialist_model_contract_valid": report.get("specialist_model_contract_valid"),
        "specialist_model_contract_failures": report.get("specialist_model_contract_failures") or [],
        "specialist_model_contract": report.get("specialist_model_contract") or {},
        "architecture_active_heads": recommended.get("active_heads") or recommended.get("heads") or [],
        "architecture_blocked_heads": recommended.get("blocked_heads") or [],
        "foundation_objective_routing_all_present_and_expected": report.get(
            "foundation_objective_routing_all_present_and_expected"
        ),
        "specialist_input_liveness_all_live": report.get("specialist_input_liveness_all_live"),
        "specialist_input_liveness": [
            {
                "split": row.get("split"),
                "specialist": row.get("specialist"),
                "live_feature_count": row.get("live_feature_count"),
                "feature_count": row.get("feature_count"),
                "min_required_live_feature_count": row.get("min_required_live_feature_count"),
                "nonfinite_count": row.get("nonfinite_count"),
                "mean_active_rate": row.get("mean_active_rate"),
            }
            for row in report.get("specialist_input_liveness", [])
            if isinstance(row, dict)
        ],
        "foundation_objective_routing": [
            {
                "objective": row.get("objective"),
                "expected_specialist": row.get("expected_specialist"),
                "routed_to_expected_count": row.get("routed_to_expected_count"),
                "required_count": row.get("required_count"),
                "missing_count": row.get("missing_count"),
                "misrouted_count": row.get("misrouted_count"),
            }
            for row in report.get("foundation_objective_routing", [])
            if isinstance(row, dict)
        ],
        "failures": report.get("failures") or [],
    }


def target_contract_summary(report: dict) -> dict:
    head_contract = report.get("target_head_contract") if isinstance(report.get("target_head_contract"), dict) else {}
    return {
        "decision": report.get("decision"),
        "active_training_heads": head_contract.get("active_training_heads") or [],
        "blocked_heads": head_contract.get("blocked_heads") or [],
        "failures": report.get("failures") or [],
    }


def worktree_contract_summary(report: dict) -> dict:
    critical_gate_review = (
        report.get("foundation_cleanup_critical_gate_review")
        if isinstance(report.get("foundation_cleanup_critical_gate_review"), dict)
        else {}
    )
    return {
        "decision": report.get("decision"),
        "dirty_count": report.get("dirty_count"),
        "foundation_cleanup_dirty_count": report.get("foundation_cleanup_dirty_count"),
        "review_before_stage_dirty_count": report.get("review_before_stage_dirty_count"),
        "foundation_cleanup_stage_ready": report.get("foundation_cleanup_stage_ready"),
        "foundation_cleanup_critical_gate_review": {
            "critical_gate_path_count": critical_gate_review.get("critical_gate_path_count"),
            "ok_count": critical_gate_review.get("ok_count"),
            "missing_from_repo": critical_gate_review.get("missing_from_repo") or [],
            "dirty_missing_from_stage": critical_gate_review.get("dirty_missing_from_stage") or [],
        },
        "stage_plan_safe": report.get("stage_plan_safe"),
        "post_stage_verification": report.get("foundation_cleanup_post_stage_verification") or {},
    }


def smoke_dataset_contract_summary(report: dict) -> dict:
    provenance = report.get("audit_provenance") if isinstance(report.get("audit_provenance"), dict) else {}
    artifacts = provenance.get("artifacts") if isinstance(provenance.get("artifacts"), dict) else {}
    splits = report.get("splits") if isinstance(report.get("splits"), dict) else {}
    return {
        "schema_version": report.get("schema_version"),
        "source_dir": report.get("source_dir"),
        "out_dir": report.get("out_dir"),
        "audit_provenance_schema_version": provenance.get("schema_version"),
        "audit_provenance_all_artifacts_present": provenance.get("all_artifacts_present"),
        "audit_provenance_all_artifact_hashes_present": provenance.get("all_artifact_hashes_present"),
        "audit_provenance_artifacts": {
            str(name): {
                "path": row.get("path"),
                "sha256": row.get("sha256"),
                "decision": row.get("decision"),
                "dataset_dir": row.get("dataset_dir"),
            }
            for name, row in artifacts.items()
            if isinstance(row, dict)
        },
        "split_hashes": {
            str(split): {
                "rows": row.get("rows"),
                "label_counts": row.get("label_counts"),
                "source_manifest": row.get("source_manifest"),
                "source_manifest_sha256": row.get("source_manifest_sha256"),
                "out_path": row.get("out_path"),
                "out_parquet_sha256": row.get("out_parquet_sha256"),
                "out_manifest": row.get("out_manifest"),
                "out_manifest_sha256": row.get("out_manifest_sha256"),
            }
            for split, row in splits.items()
            if isinstance(row, dict)
        },
    }


def gate_decision(report: dict, name: str) -> str:
    for gate in report.get("gates") or []:
        if isinstance(gate, dict) and str(gate.get("name")) == name:
            return str(gate.get("decision") or "")
    return ""


run_flavor = os.environ.get("RUN_FLAVOR", "foundation_seq146")
readiness = read_json(sys.argv[10])
artifacts = readiness.get("artifacts") if isinstance(readiness.get("artifacts"), dict) else {}
feature_audit_path = os.environ.get("FEATURE_AUDIT_JSON") or artifacts.get("feature_audit")
target_audit_path = os.environ.get("TARGET_AUDIT_JSON") or artifacts.get("target_audit")
specialist_audit_path = sys.argv[8]
worktree_hygiene_path = artifacts.get("worktree_hygiene")
feature_audit = read_json(feature_audit_path) if feature_audit_path else {}
target_audit = read_json(target_audit_path) if target_audit_path else {}
specialist_audit = read_json(specialist_audit_path)
worktree_hygiene = read_json(worktree_hygiene_path) if worktree_hygiene_path else {}
smoke_dataset_manifest = read_json(sys.argv[6])
readiness_artifact_key = "smart_trainability_readiness" if run_flavor == "smart_seq520" else "training_readiness"
guardrails_artifact_key = "smart_smoke_readiness" if run_flavor == "smart_seq520" else "foundation_guardrails"
artifact_paths = {
    readiness_artifact_key: sys.argv[10],
    "feature_audit": feature_audit_path,
    "target_audit": target_audit_path,
    "specialist_audit": specialist_audit_path,
    guardrails_artifact_key: sys.argv[9],
    "smoke_dataset_manifest": sys.argv[6],
    "worktree_hygiene": worktree_hygiene_path,
}
artifact_paths = {key: path for key, path in artifact_paths.items() if path}
artifact_sha256 = {
    key: sha256_file(path)
    for key, path in artifact_paths.items()
}
readiness_artifact_fingerprints = readiness.get("artifact_fingerprints") or {}
if run_flavor != "foundation_seq146":
    readiness_artifact_fingerprints = run_artifact_fingerprints(artifact_paths)
    for key, fingerprint in readiness_artifact_fingerprints.items():
        if not fingerprint.get("exists"):
            print(f"FATAL: non-foundation manifest artifact fingerprint missing: {key}", file=sys.stderr)
            raise SystemExit(2)
        if str(fingerprint.get("sha256") or "") != str(artifact_sha256.get(key) or ""):
            print(f"FATAL: non-foundation manifest artifact fingerprint hash mismatch: {key}", file=sys.stderr)
            raise SystemExit(2)


payload = {
    "schema_version": "entry_foundation_smoke_train_run_manifest_v1",
    "created_utc": datetime.now(timezone.utc).isoformat(),
    "run_kind": f"vedtak_gated_{run_flavor}_smoke_train",
    "run_mode": sys.argv[19],
    "vedtak": sys.argv[2],
    "specialist_contract_mode": os.environ.get("SPECIALIST_CONTRACT_MODE", "foundation_seq146"),
    "out_bundle_dir": sys.argv[3],
    "promotion_shadow_live_allowed": False,
    "trainer_started_by_manifest_writer": False,
    "preflight_gates": (
        {
            "smart_smoke_readiness": "PASS_BEFORE_MANIFEST",
            "smart_trainability_readiness": "PASS_BEFORE_MANIFEST",
        }
        if run_flavor == "smart_seq520"
        else {
            "foundation_verify": "PASS_BEFORE_MANIFEST",
            "foundation_guardrails": "PASS_BEFORE_MANIFEST",
            "train_readiness": "PASS_BEFORE_MANIFEST",
        }
    ),
    "inputs": {
        "source_dataset_dir": sys.argv[4],
        "smoke_dataset_dir": sys.argv[5],
        "smoke_dataset_manifest": sys.argv[6],
        "m5_prebuilt_path": sys.argv[7],
        "feature_audit_json": feature_audit_path,
        "target_audit_json": target_audit_path,
        "specialist_audit_json": sys.argv[8],
        guardrails_artifact_key + "_json": sys.argv[9],
        readiness_artifact_key + "_json": sys.argv[10],
        "worktree_hygiene_json": worktree_hygiene_path,
    },
    "artifact_sha256": {
        key: value
        for key, value in artifact_sha256.items()
    },
    "preflight_contracts": {
        readiness_artifact_key: {
            "decision": readiness.get("decision"),
            "foundation_contract_ready_for_smoke": readiness.get("foundation_contract_ready_for_smoke"),
            "smoke_training_allowed_with_explicit_vedtak": readiness.get(
                "smoke_training_allowed_with_explicit_vedtak"
            ),
            "smart_smoke_train_allowed_with_explicit_vedtak": readiness.get(
                "smart_smoke_train_allowed_with_explicit_vedtak"
            ),
            "artifact_provenance_decision": gate_decision(readiness, "artifact_provenance"),
            "artifact_fingerprints": readiness_artifact_fingerprints,
            "execution_blockers": readiness.get("execution_blockers") or [],
        },
        "feature_foundation": feature_contract_summary(feature_audit),
        "target_foundation": target_contract_summary(target_audit),
        "specialist_contract": specialist_contract_summary(specialist_audit),
        "smoke_dataset": smoke_dataset_contract_summary(smoke_dataset_manifest),
        "worktree_hygiene": worktree_contract_summary(worktree_hygiene),
    },
    "options": {
        "audit_after": sys.argv[11] == "1",
        "require_edge_audit": sys.argv[12] == "1",
        "device": sys.argv[13],
        "epochs": int(sys.argv[14]),
        "batch_size": int(sys.argv[15]),
        "train_rows": int(sys.argv[16]),
        "val_rows": int(sys.argv[17]),
        "test_rows": int(sys.argv[18]),
        "manifest_only": sys.argv[19] == "manifest_only",
        "memory_cap": os.environ.get("SMOKE_RUN_MEM"),
        "swap_cap": os.environ.get("SMOKE_RUN_SWAP"),
        "cgroup_runner": "scripts/gx1_capped_run.sh",
        "uses_gx1_capped_run": True,
        "num_workers": int(command_arg_value(train_cmd, "--num-workers") or -1),
        "early_stopping_patience": int(command_arg_value(train_cmd, "--early-stopping-patience") or -1),
    },
    "smoke_recipe_env": {
        name: command_env_value(train_cmd, name)
        for name in [
            "GX1_ENTRY_ALLOW_TRAIN_ENV_OVERRIDES",
            "ENTRY_AUX_BAD_PATH_WEIGHT",
            "ENTRY_BAD_PATH_QUALITY_RANK_WEIGHT",
            "ENTRY_BAD_PATH_QUALITY_RANK_MARGIN",
            "ENTRY_BAD_PATH_QUALITY_RANK_QUANTILE",
            "ENTRY_BAD_PATH_PROB_PENALTY",
            "ENTRY_PATH_QUALITY_RANK_WEIGHT",
            "ENTRY_PATH_QUALITY_RANK_MARGIN",
            "ENTRY_PATH_QUALITY_RANK_QUANTILE",
            "ENTRY_PRED_BALANCE_ALPHA",
            "ENTRY_PRED_BALANCE_TARGET",
            "ENTRY_PRED_BALANCE_CLASS_WEIGHTS",
            "ENTRY_DIRECTION_CE_SCALE",
            "ENTRY_TAIL_DIRECTION_CE_WEIGHT",
            "ENTRY_TAIL_DIRECTION_QUALITY_QUANTILE",
            "ENTRY_TAIL_DIRECTION_MIN_BATCH",
            "GX1_V10_CKPT_MONITOR",
            "ENTRY_CKPT_CLASS_BALANCE_GUARD_WEIGHT",
            "ENTRY_CKPT_CLASS_BALANCE_MIN_PRED_TO_LABEL",
            "ENTRY_CKPT_CLASS_BALANCE_MIN_PRED_RATE",
            "ENTRY_CKPT_DIRECTION_SLICE_GUARD",
            "ENTRY_DIRECTION_MIN_PRED_RATE_LOSS_WEIGHT",
            "ENTRY_DIRECTION_MIN_PRED_RATE_FRACTION",
            "ENTRY_DIRECTION_MIN_PRED_RATE_FLOOR",
            "ENTRY_DIRECTION_MIN_PRED_RATE_SOFTMAX_TEMPERATURE",
            "ENTRY_DIRECTION_GLOBAL_PRIOR_MATCH_WEIGHT",
            "ENTRY_DIRECTION_GLOBAL_PRIOR_MATCH_TOLERANCE",
            "ENTRY_DIRECTION_GLOBAL_PRIOR_MATCH_MIN_LABEL_RATE",
            "ENTRY_DIRECTION_SLICE_MIN_PRED_RATE_LOSS_WEIGHT",
            "ENTRY_DIRECTION_SLICE_MIN_PRED_RATE_FRACTION",
            "ENTRY_DIRECTION_SLICE_MIN_PRED_RATE_FLOOR",
            "ENTRY_DIRECTION_SLICE_MIN_LABEL_RATE",
            "ENTRY_DIRECTION_SLICE_MIN_ROWS",
            "ENTRY_DIRECTION_SLICE_CTX_CAT_INDICES",
            "ENTRY_DIRECTION_SLICE_RECALL_LOSS_WEIGHT",
            "ENTRY_DIRECTION_SLICE_RECALL_PROB_FLOOR",
            "ENTRY_DIRECTION_SLICE_RECALL_MIN_LABEL_RATE",
            "ENTRY_DIRECTION_SLICE_RECALL_MIN_ROWS",
            "ENTRY_DIRECTION_SLICE_BALANCED_CE_WEIGHT",
            "ENTRY_DIRECTION_SLICE_BALANCED_CE_MIN_LABEL_RATE",
            "ENTRY_DIRECTION_SLICE_BALANCED_CE_MIN_ROWS",
            "ENTRY_DIRECTION_SLICE_TRUE_MARGIN_WEIGHT",
            "ENTRY_DIRECTION_SLICE_TRUE_MARGIN",
            "ENTRY_DIRECTION_SLICE_TRUE_MARGIN_MIN_LABEL_RATE",
            "ENTRY_DIRECTION_SLICE_TRUE_MARGIN_MIN_ROWS",
            "ENTRY_DIRECTION_SLICE_ACCURACY_EDGE_WEIGHT",
            "ENTRY_DIRECTION_SLICE_ACCURACY_EDGE_MARGIN",
            "ENTRY_DIRECTION_SLICE_ACCURACY_EDGE_MIN_LABEL_RATE",
            "ENTRY_DIRECTION_SLICE_ACCURACY_EDGE_MIN_ROWS",
            "ENTRY_DIRECTION_SLICE_PRIOR_MATCH_WEIGHT",
            "ENTRY_DIRECTION_SLICE_PRIOR_MATCH_TOLERANCE",
            "ENTRY_DIRECTION_SLICE_PRIOR_MATCH_MIN_LABEL_RATE",
            "ENTRY_DIRECTION_SLICE_PRIOR_MATCH_MIN_ROWS",
            "ENTRY_DIRECTION_SLICE_LOSS_AGGREGATION",
            "ENTRY_DIRECTION_SLICE_BALANCED_SAMPLER",
            "ENTRY_DIRECTION_SLICE_BALANCED_SAMPLER_MIN_ROWS",
            "ENTRY_DIRECTION_SLICE_HARD_RED_STOP_PATIENCE",
            "ENTRY_DIRECTION_SLICE_HARD_RED_STOP_MIN_EPOCHS",
            "ENTRY_DIRECTION_VS_FLAT_MARGIN_WEIGHT",
            "ENTRY_DIRECTION_VS_FLAT_MARGIN",
            "ENTRY_HIER_LEGACY_CE_MULT",
            "ENTRY_HIER_TRADE_WEIGHT",
            "ENTRY_HIER_SIDE_WEIGHT",
            "ENTRY_HIER_UTILITY_WEIGHT",
            "ENTRY_HIER_BAD_PATH_WEIGHT",
            "ENTRY_HIER_MAE_WEIGHT",
            "ENTRY_RESIDUAL_SCALE",
            "ENTRY_ANCHOR_EPS",
            "ENTRY_HIER_SIDE_VALIDITY_WEIGHT",
            "ENTRY_HIER_SIDE_VALIDITY_MIN_UTILITY_BPS",
            "ENTRY_HIER_SIDE_VALIDITY_POS_WEIGHT_CAP",
            "ENTRY_HIER_POCKET_ABSTAIN_WEIGHT",
            "ENTRY_HIER_POCKET_SIDE_MARGIN_WEIGHT",
            "ENTRY_HIER_POCKET_UTILITY_MARGIN_BPS",
            "ENTRY_TRENDLINE_RAIL_AUX_WEIGHT",
            "ENTRY_TRENDLINE_RAIL_WRONG_SIDE_WEIGHT",
            "ENTRY_TRENDLINE_RAIL_RISING_WRONG_SHORT_WEIGHT",
            "ENTRY_TRENDLINE_RAIL_FALLING_WRONG_LONG_WEIGHT",
            "ENTRY_TRENDLINE_RAIL_FINAL_MARGIN_WEIGHT",
            "ENTRY_TRENDLINE_RAIL_HIER_MARGIN_WEIGHT",
            "ENTRY_TRENDLINE_RAIL_FLAT_TRADE_WEIGHT",
            "ENTRY_TRENDLINE_RAIL_UTILITY_MARGIN_WEIGHT",
            "ENTRY_TRENDLINE_RAIL_MARGIN",
            "ENTRY_TRENDLINE_RAIL_UTILITY_MARGIN_BPS",
            "ENTRY_SYMMETRIC_NEGATIVES",
            "ENTRY_FLAT_CLASS_WEIGHT_FLOOR",
            "ENTRY_SPECIALIST_GATE_ENTROPY_WEIGHT",
            "ENTRY_SPECIALIST_GATE_BALANCE_WEIGHT",
            "ENTRY_SPECIALIST_GATE_MIN_MEAN",
        ]
    },
    "commands": {
        "train": train_cmd,
        "post_smoke_audit": audit_cmd,
    },
    "git": {
        "repo": str(repo),
        "commit": git("rev-parse", "HEAD"),
        "branch": git("rev-parse", "--abbrev-ref", "HEAD"),
        "status_short": git("status", "--short").splitlines(),
    },
}
manifest_path.parent.mkdir(parents=True, exist_ok=True)
manifest_path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
latest = manifest_path.parent / "ENTRY_FOUNDATION_SMOKE_TRAIN_RUN_MANIFEST_latest.json"
latest.write_text(manifest_path.read_text(encoding="utf-8"), encoding="utf-8")
print(f"Pre-train run manifest written: {manifest_path}")
PY

if [[ "$MANIFEST_ONLY" = "1" ]]; then
  echo "Manifest-only stop before training: $PRETRAIN_MANIFEST"
  exit 0
fi

"$SMOKE_CAPPED_RUNNER" --mem "$SMOKE_RUN_MEM" --swap "$SMOKE_RUN_SWAP" -- "${CMD[@]}"
echo "Smoke bundle export completed; post-smoke audit pending: $OUT_BUNDLE"
if [[ "$AUDIT_AFTER" = "1" ]]; then
  if "${AUDIT_CMD[@]}"; then
    echo "Smoke bundle accepted by post-smoke audit: $OUT_BUNDLE"
  else
    AUDIT_RC=$?
    if [[ "$REQUIRE_EDGE_AUDIT" = "1" ]]; then
      echo "Post-smoke edge audit failed; removing rejected smoke bundle: $OUT_BUNDLE" >&2
      rm -rf -- "$OUT_BUNDLE"
    fi
    exit "$AUDIT_RC"
  fi
else
  echo "Smoke bundle audit skipped by --skip-smoke-audit: $OUT_BUNDLE"
fi
