name: CI
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install Poetry
        run: pipx install poetry
      - name: Install deps
        run: |
          poetry install --no-root --no-interaction --no-ansi
      - name: Ruff (lint)
        run: poetry run ruff check .
      - name: Black (format check)
        run: poetry run black --check .
      - name: Debug env
        run: |
          pwd
          ls -R
          poetry --version
          poetry run python -V
          poetry run python -c "import sys,os; print('PYTHONPATH=',os.getenv('PYTHONPATH')); print('sys.path='); print('\n'.join(sys.path))"
      - name: Pytest
        env:
          PYTHONPATH: src
        run: |
          set -e
          poetry run pytest -vv